### ISSUE TITLE
No indication that the number of rows for a CSV is limited to 1 million

### ISSUE THREAD

**Issue by xhoenner** [aodn/aodn-portal#1140]
Google Chrome, v35.0.1916.114
[Portal Build Info]
Base URL: http://imos.aodn.org.au/imos123/home
Build date: 23/05/2014 10:07
Version: 3.24.0-rc3
Instance name: AODN
Environment: production

Steps to reproduce:
Select for instance 'IMOS - AATAMS Facility Satellite Relay Tagging Program - Delayed mode data'.
Go to step 2. Select none as Spatial extent. Go to Step 3, click Download as CSV.

What does happen:
You download a CSV with a subset of the data you've selected (first 1 million rows I suspect), not the entire dataset.

What should happen:
A message should warn you that you won't be able to download all the data that you've selected as it is larger than 1 million rows, and that you should therefore subset the data that you've selected.

**Comment by pblain** [comment]
Added to backlog https://github.com/aodn/backlog/issues/394
