### ISSUE TITLE
Support for CARS data

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#122]
just a quick remark regarding the idea of displaying CARS data on the portal or in a GIS software via an ArcGIS file format for example :

You might already know but what you find in the CARS data is not an actual climatology (that is to say variables values at regular intervals along a year) but information that the user can use to build its own climatology (choosing its own time interval along the year). At the moment the portal enables us to display only those information (annual mean temperature, annual cosine temperature, annual sine temperature, etc...) which is not very interesting and relevant to display. If we would provide such information in ArcGIS format then the users might also be disappointed.

At term, I'm wondering if we could setup a service behind the portal which would do the computation and enable the user to display the actual climatology with a chosen time interval and so that we can go through different values over time (animation) like with HF radar.

Cheers,

Guillaume Galibert

**Comment by smancini** [comment]
Testing
