### ISSUE TITLE
Failed test: Info tab links

### ISSUE THREAD

**Issue by aodntester** [aodn/aodn-portal#1222]
### To reproduce on RC

Add layer: sst.L3C-3d.ngt.n19/sea_surface_temperature
### What happens
The layer comes from serverUri:http://rs-data1-mel.csiro.au/ncWMS/wms, the portal is marking up a bad link called "This OGC WFS service returns filtered geographic information. The returned data is available in multiple formats including CSV."
### What should happen 
Portal code should not markup broken links from externally provided metadata

T2006: Info tab links correctly labelled
https://aodn.testrail.com/index.php?/tests/view/2006

**Comment by dnahodil** [comment]
Fixed as #1613
