### ISSUE TITLE
Access to latest data - e.g. Radar

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#126]
Ability to access the latest radar data (24 hour animation) from one site (the one I am more interested in). I want a quick access to this layer without having to select a layer and then select the dates for the animation. I just want to enter the url like for example http://imos.aodn.org.au/webportal/radar/SAG/latest and it will bring me the latest animation.

**Comment by danfruehauf** [comment]
@pblain This is achievable now using the direct link to the collection. So is this still relevant?

**Comment by pblain** [comment]
Yes, and we don't have animations now anyway.
