### ISSUE TITLE
The origin of organisation in search should include organisation in cited responsible party.

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1294]
Upon reporting of bug #1292 it was discovered that portal2 is only deriving organisation name for searching purposes from Point of contact in the metadata record. As implemented into 123 as per discussion between @pblain and @atkinsn the portal derives organisations from both the point of contact and the cited responsible party.

Due to this it is possible that users of portal2 are not able to discover the full extent of records that they may expect eg, a search for IMOS records only results in 2 pages but it is known there should be a lot more pages.

**Comment by smancini** [comment]
Not relevant anymore
