### ISSUE TITLE
Grails build gives different WAR than our build process

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#1325]
Matt Pageat from AusCover/CSIRO tried building our Portal from source when he was investigating an issue with their deployment. He noted that the WAR he got from Grails was not the same as the one we provided.

> I did build the portal code from source with grails but my war didn’t work (various errors in tomcat startup). Your war did work straight out of the box (thank you). The two wars are slightly different in size (43 MB vs 41 MB for grails build). A recursive diff of the two exploded wars gives:
-          330 files different between the two
  -   I haven’t looked into details but we could expect a number of them to differ only by build date.
  -   There are 4850 odd files in each war.
-          Some libs are in yours (prod/) but not in the grails build (grails/)
  -   Only in prod/WEB-INF/lib: cas-client-core-3.2.1.jar
  -   Only in grails/WEB-INF/lib: commons-beanutils-1.8.0.jar
  -   Only in prod/WEB-INF/lib: commons-beanutils-1.8.3.jar
  -   Only in prod/WEB-INF/lib: commons-logging-1.1.jar
  -   Only in prod/WEB-INF/lib: liquibase-core-2.0.1.jar
  -   Only in prod/WEB-INF/lib: quartz-1.6.1.jar
  -   Only in prod/WEB-INF/lib: shiro-cas-1.2.0.jar
  -   Only in prod/WEB-INF/lib: shiro-core-1.2.0.jar
  -   Only in prod/WEB-INF/lib: shiro-ehcache-1.2.0.jar
  -   Only in prod/WEB-INF/lib: shiro-quartz-1.2.0.jar
  -   Only in prod/WEB-INF/lib: shiro-spring-1.2.0.jar
  -   Only in prod/WEB-INF/lib: shiro-web-1.2.0.jar

We didn't investigate any further as the problem was fixed by using a newer WAR built by our build process. But I thought it was worth recording his findings in case others try to build from source.

**Comment by danfruehauf** [comment]
This issue is lacking tags.

To be honest I don't think we should build with grails. Jenkins build those things with maven - correct me if I'm wrong - and that is what should work.

**Comment by dnahodil** [comment]
We use the Grails build wherever possible (including building our WARs in Jenkins). The only reason we use maven is to run the tests because Grails doesn't run the Jasmine test phase.

I didn't give this issue any labels because I don't expect us to look into it unless it started causing us problems. Just like some of the enhancements it's here as a record rather than as a thing to do.

**Comment by danfruehauf** [comment]
So AFAIK jenkins uses grails to build WARs now and maven only for the JS tests. So... keep this open or?

**Comment by dnahodil** [comment]
Jenkins always used Grails to build the wars, that's why it was interesting that the final war was different.

Maybe when we merge the 2.4.4 upgrade we can compare the output of Jenkins to that of a build on a dev machine. If it's the same we can close this issue. If it's different we might decide to look into it.

**Comment by danfruehauf** [comment]
Yep. I thought it refers to the fact that jenkins used to build the war with `mvn package`, but alright, now I understand.

**Comment by dnahodil** [comment]
I think the move to 2.4.4 is a good time to either look into this a little, or to accept that we don't care.

**Comment by danfruehauf** [comment]
Then should be revisited after #1694 is merged (commented just to have the link to the PR).

**Comment by dnahodil** [comment]
Looks to me like this is still a problem in Grails 2.4.4.

I don't think we're really going to look into it unless it causes us a problem.

**Comment by danfruehauf** [comment]
:+1:
