### ISSUE TITLE
Ability to configure per-Portal what facets are shown

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#136]
It might be an idea to have a per-instance configuration as to which facets are shown in the faceted search. It might be the case that a facet is always going to be empty on a particular Portal, or that you just don't want to have users searching by that facet.

An alternative is to remove unused facets from GeoNetwork but that might not be as flexible.

**Comment by danfruehauf** [comment]
I think that's solved by https://github.com/aodn/aodn-portal/pull/1764
