### ISSUE TITLE
Facets not finding all records

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1451]
Instance name: IMOS
            App version: 3.34.2
            Build date: Tue Oct 14 14:39:14 EST 2014
            Build number: 222
            Git ref: f08cc35e78df0d2b5511405d57e3d260e7a1941d

I have only come across this for one result I'm not going to sit here and count every single record to check for others though (as it might just be this particular one) I have checked a couple of other random ones and they look ok.

Steps to reproduce:

Select from the measured parameter Physical Water> Turbidity > Turbidity of the water body. Note the number of results at this present time there are 8 showing up.

Click start new search to clear all selected facets then go through the results list and make a note of how many results have the parameter Turbidity of the water body.

 What should happen:

Should count 8

What does happen:

Count 9: (Seems that WQM and CTD is missing from the facet list)

IMOS - Australian National Mooring Network (ANMN) Facility - WQM and CTD burst averaged data products

-IMOS - SOOP-Temperate Merchant Vessel (TMV) sub-facility - Data collected on the Spirit of Tasmania I during transect between Melbourne and Devonport (Delayed mode)

-IMOS - ANMN National Reference Stations - Maria and North Stradbroke Islands - Near real-time water quality

-IMOS - Facility for Automated Intelligent Monitoring of Marine Systems (FAIMMS)

-IMOS - ANMN National Reference Stations - Darwin and Yongala - Near real-time meteorology and oceanographical data

-IMOS - SOOP-Temperate Merchant Vessel (TMV) sub-facility - Data collected on the Spirit of Tasmania I during transect between Melbourne and Devonport (Near real-time)

-Sensors on Tropical Research Vessels: Enhanced Measurements from Ships of Opportunity (SOOP)

-IMOS - ABOS Southern Ocean Time Series (SOTS) - Pulse mooring data

-IMOS - Australian National Mooring Network (ANMN) - CTD Profiles

**Comment by smancini** [comment]
Testing
