### ISSUE TITLE
No Visible loading indicator on first collection added

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1452]
Instance name: IMOS
            App version: 3.34.2
            Build date: Tue Oct 14 14:39:14 EST 2014
            Build number: 222
            Git ref: f08cc35e78df0d2b5511405d57e3d260e7a1941d

Steps to reproduce:

Add Argo collection to map look for loading symbol next to collection name in active list

What should happen:

Should see loading symbol immediately and the zoom symbol and check box for turning collection visibility on/off

What does happen:

Collection loads on map but the three symbols mentioned above do not appear until collection is loaded.

**Comment by smancini** [comment]
Testing
