### ISSUE TITLE
Specific Filters

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#1477]
How to reproduce
- Select SOOP SST (or similar)

What I expect to happen
- On Step 2 the Filters title reads "Filters"

What I does happen
- On Step 2 the Filters title reads "Specific Filters"

![image](https://cloud.githubusercontent.com/assets/2802359/5019961/3caa5208-6b18-11e4-8fd9-e6f45a8f62ff.png)

**Comment by smancini** [comment]
Testing
