### ISSUE TITLE
Some ncWMS styles missing from drop-down

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#1483]
Found in version:

```
IMOS Portal v3.35.0, build date: Fri Nov 07 14:49:57 EST 2014
```

**How to reproduce**
Open an ACORN layer
Go to the styles tab
Open the styles drop-down

**What should happen**
Should see the various vector styles available (boxfill, vector, fancyvec, trivec, barb, stumpvec, etc.)

**What does happen**
You only see two styles available, boxfill and vector.

**Notes**
This happened when we moved the ncWMS layers out of the database. The styles information returned from ncWMS in the `GetMetadata` request is not as complete as the information in `GetCapabilities` which the scanner uses. We might need to improve the GetMetadata response from ncWMS.

**Comment by smancini** [comment]
Testing
