### ISSUE TITLE
estimateSizeForLayer ajax request is made twice per collection

### ISSUE THREAD

**Issue by pmbohm** [aodn/aodn-portal#1485]
### To reproduce
- With Firebug open
- Add a collection to the portal

Note: on Master, using Firefox with no browser caching 
### What happens
- The estimateSizeForLayer ajax request is made on collection load and as no subsetting has yet been done this is often a complex calculation taking time to return a response and server load.
- -- wait till this finishes and got to Step 3
- The estimateSizeForLayer ajax request is called again even though no subsetting has been done. 
### What should happen
- The estimateSizeForLayer ajax request should not be made on collection load. 
- The request could be made if we have a reasonable expectation that the response will come from cache? pre seed? The two requests then should be identical between collection load and Step 3

**Comment by smancini** [comment]
Testing
