### ISSUE TITLE
Catami layers not loading in production

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#1494]
Noticed by @atkinsn in prod

```
IMOS Portal v3.35.0, build date: Fri Nov 07 14:49:57 EST 2014
```

The Catami layers do not load (see: https://imos.aodn.org.au/imos123/home?uuid=85fc8d5b-b970-41fd-94ef-5e658d1e13b7). There is no apparent error and no message as to why.

**Comment by smancini** [comment]
Testing
