### ISSUE TITLE
Problem with the vocab picker in geonetwork

### ISSUE THREAD

**Issue by smancini** [aodn/aodn-portal#1499]
How to reproduce

Open and edit a metadata record 
Add a new data parameter
Add a new parameter name or a new platform
Use the vocab picker to select the appropriate term.

What should happen

The picker should only display corresponding vocabulary terms and not any classification that are used by the faceted search in step 1 of the portal.

For example, when adding a new parameter name and searching for terms that contains "current", the term "current direction in the water body" is a valid term while "current" is its corresponding classification used in step 1 of the portal.
"Current" should not be available in the picker.

What does happen

Vocabulary terms and classification are displayed within the picker.

Notes

This is a Geonetwork bug but I was not sure in which repo to include it.

**Comment by smancini** [comment]
Natalia and I have tried to use the thesaurus picker on catalogue-rc and it lokks like it is still not working properly.
Classification are still displayed within the picker

**Comment by jonescc** [comment]
GeoNetwork wasn't deployed last iteration.  The version of GeoNetwork in systest needs to be deployed to production and catalogue-rc for this to be tested.

**Comment by pblain** [comment]
The GN deployment task to fix this is on the board (in the release row).
