### ISSUE TITLE
Previous/Next buttons active on initial load of Step 1

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1508]
I am seeing this on Production and Systest.

Steps to reproduce:
1. Refresh portal look to bottom left of screen
2. Click step 2 on steps bar.

What should happen:
1. No buttons there
2. Nothing

What does happen:
1. There are buttons there (definitely shouldn't be a previous button on step 1)
2. User can move to step 2 without adding any collections

**Comment by smancini** [comment]
Testing
