### ISSUE TITLE
Non ncWMS Filters do not load if Step 1 or 3 accessed before they load

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1517]
Instance name: IMOS
            App version: 3.36.3
            Build date: Thu Nov 27 14:31:24 EST 2014
            Build number: 282
            Git ref: 96ed7befea521587e2a1631957f9d8445da26a2d

Steps to reproduce:

Add any non-ncWMS collection.

AS soon as taken to step 2 click back to step 1 or forward to step 3.

Then go back to step 2

What should happen:

Spatial and Temporal extents are successfully loaded.

What does happen:

Just see a blank space where they should be

**Comment by pblain** [comment]
@pmbohm agreed.  I'll add the accordion feature to the backlog for hopeful inclusion next iteration.  I'll close this bug because we are not going to fix it directly.

**Comment by pblain** [comment]
Accordion feature alone will not fix. Re-opening.
