### ISSUE TITLE
Disclaimer text no longer shown when direct linking to collection

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#1544]
**Steps to reproduce**
Use a link (e.g.: https://imos.aodn.org.au/imos123/home?uuid=52f09a23-63a2-4c14-8b3b-1fc7c8167281) to direct access a collection on the Portal.

**What should happen**
The Portal should display a pop-up with a disclaimer and terms-of-use for the data.

**What does happen**
Currently the production Portal pops-up a number of links (one of which is a link to the disclaimer page on the help forum) instead of this text. I guess this pop up just presents the same data as the Portal footer (as that used to be the disclaimer but isn't any more).

![screenshot from 2015-01-05 14 55 13](https://cloud.githubusercontent.com/assets/2774917/5609093/3c22f266-94eb-11e4-959a-dd3d7ec0df17.png)

**Comment by pblain** [comment]
I don't think we need this pop-up because the disclaimer (etc) links are displayed at the bottom of the portal - which conforms with standard practice.  I assume the pop-up was introduced before we had the links.

**Comment by dnahodil** [comment]
I think the disclaimer used to be on the landing/splash page. So if you went directly to the map you wouldn't see it (hence the pop-up). If you're happy, though, we can just remove this pop-up completely.

**Comment by anguss00** [comment]
I've just picked up this issue, should I delete the pop-up @pblain, @dnahodil?

**Comment by dnahodil** [comment]
Yeah, when I spoke to @pblain he's keen to just remove the popup completely.

**Comment by anguss00** [comment]
:+1:
