### ISSUE TITLE
Duplicates in ANMN NRS - Maria and North Stradbroke Islands - Near real-time meteorology and sea surface temperature

### ISSUE THREAD

**Issue by ggalibert** [aodn/aodn-portal#1545]
@mhidas this is an issue that has been reported to me by a user just before Chrismas.

<b>What to do :</b>
-On step 1 select the data collection 
IMOS - ANMN National Reference Stations - Maria and North Stradbroke Islands - Near real-time meteorology and sea surface temperature .
-On step 2 filter temporally from 2014/06/12 to 2014/06/13 and choosing site code NRSMAI.
-On step 3 choose download as CSV and then download as un-subsetted netcdf..

<b>What to expect :</b>
We retrieve a CSV file with unique data values per time stamp.
We retrieve the relevant netcdf file.

<b>What happens :</b>
In the CSV, from 2014-06-12T01:06:28 there are duplicates of same values, only the field index is different. These duplicated rows also happen to have their boolean fields (air_temperature_b, etc...) not documented.
We retrieve an empty failed netcdf in addition to the relevant one, like if an old version of the netcdf was still present somewhere and would affect the CSV content?

**Comment by ggalibert** [comment]
![screenshot from 2015-01-05 16 54 45](https://cloud.githubusercontent.com/assets/3498686/5609765/05ca4c4e-94fc-11e4-9902-c25e35f21b43.png)

**Comment by mhidas** [comment]
Thanks @ggalibert, I'll take a look at it soon.

**Comment by dnahodil** [comment]
Hey guys.

I've just moved this issue to the content repo as it is a content issue rather than a Portal one.
https://github.com/aodn/content/issues/72

Cheers,
