### ISSUE TITLE
Strange symbols on results

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1548]
Instance name: IMOS
            App version: 3.38.1
            Build date: Tue Jan 06 16:22:45 EST 2015
            Build number: 306
            Git ref: 7c92c8bb3b4dd016b4e65fb0e26d09019939109c
        -->

Steps to reproduce:

Look at step 1 results,

What should happen:

Attributes of metadata should be listed ie 
Organisation - Integrated marine observing system.
Platform - drifting subsurface profiling float
Date range - 2008-2015
Parameters - Temperature

What does happen:

Ugly little symbols are there that aren't very informative.

![symbols](https://cloud.githubusercontent.com/assets/2906602/5655714/8e011d92-9725-11e4-901d-03679e44576c.jpg)

**Comment by pblain** [comment]
This is because there is a task half completed.

**Comment by pblain** [comment]
The preceding dashes should be removed

**Comment by pblain** [comment]
Fixed with completion of search result updates
