### ISSUE TITLE
Bug on catalogue-123 when wanting to visualise metadata records as XML files

### ISSUE THREAD

**Issue by xhoenner** [aodn/aodn-portal#1556]
This is a bug occurring on catalogue-123 only.

<h3>Steps to reproduce:<h3>

Go to catalogue-123.aodn.org.au
Log in.
Hit the 'Search' button.
Click on any link to view a metadata record as an XML file (see below).

![image](https://cloud.githubusercontent.com/assets/3443821/5712916/893b8354-9b0a-11e4-9373-a0a5bcb73b25.png)

<h3>What happens:<h3>

SSL connection error, port 80 gets added at the end of catalogue-123.aodn.org.au

![image](https://cloud.githubusercontent.com/assets/3443821/5712940/b5a2fddc-9b0a-11e4-98dc-df5a100f0882.png)

<h3>What should happen:<h3>

The URL shouldn't have this ':80' after catalogue-123.aodn.org.au

**Comment by danfruehauf** [comment]
Talking to @jonescc we have decided to apply the quickest fix available as in newer versions of Geonetwork the whole interface has changed and this bug probably not present.

The quickest fix I think is available is to manually modify both `port` and `securePort` settings to be 443.

**Comment by danfruehauf** [comment]
On every geonetwork instance, the following query against its DB will solve the problem:
```
update settings set value='443' where name='port' and value='80';
```

**Comment by danfruehauf** [comment]
Fix applied on catalogue-systet.aodn.org.au

**Comment by anguss00** [comment]
Going to fix catalogue-rc

**Comment by anguss00** [comment]
Going to fix catalogue-123 now

**Comment by danfruehauf** [comment]
@anguss00 Can be closed?

**Comment by anguss00** [comment]
Yep
