### ISSUE TITLE
Cannot remove layer that fails to load

### ISSUE THREAD

**Issue by anguss00** [aodn/aodn-portal#1566]
Instance name: imos.aodn.org.au
App version: 3.37.1
Build date: Tue Dec 09 11:43:38 EST 2014
Build number: 296
Git ref: d1d0c70c7622d89aeac6e6a93e2deb589db798d4

Steps to reproduce: select IMOS - AATAMS Facility Satellite Relay Tagging Program - Argos locations which has an issue with filters in production (red triangle of doom appears). Click on remove layer icon to blow it away.

Expected behaviour: Layer is blown away.

Observed behaviour: Layer refuses to leave. Cannot delete the layer from step 2.

**Comment by pmbohm** [comment]
Damm. to late the collection/layer works now. Do you know what the error was so i can fake it broken again @anguss00

**Comment by dnahodil** [comment]
It was just a layer on an unknown server. So if you cripple the host checker to always return false then you'll have dozens of broken layers to choose from!

**Comment by pmbohm** [comment]
Cant reproduce. Even hacking the layer name so the map cant find the layer (which will cause the red triangle) will not cause this bug
