### ISSUE TITLE
Share collection URL is incorrect

### ISSUE THREAD

**Issue by danfruehauf** [aodn/aodn-portal#1574]
Share collection link on step 3 is misconfigured. For instance:
https://portal-edge.aodn.org.au/imos?uuid=4402cb50-e20a-44ee-93e6-4728259250d2

The correct link should be:
https://portal-edge.aodn.org.au/imos/home?uuid=4402cb50-e20a-44ee-93e6-4728259250d2

Steps to reproduce:
 * Add a collection
 * Go to step 3
 * Copy & paste the "share" link in a new browser window

What happens:
 * You end up in the landing page

What should happen:
 * You have the shared collection loaded on your map

**Comment by dnahodil** [comment]
Good spotting, @danfruehauf.

I'm looking into this and will fix it in 3.40.1

**Comment by danfruehauf** [comment]
Should be a quick fix (quicker than writing that bug report).
