### ISSUE TITLE
Empty Space to right of results

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1589]
Instance name: IMOS
            App version: 3.40.2
            Build date: Wed Feb 04 17:00:40 EST 2015
            Build number: 338
            Git ref: fa518e0bcace90ff148d31b9768925466bb0d433

Labeling as a bug but not technically a bug....

Steps to reproduce:

Proceed to step 1

Look at results list

What does happen:

The results in the list are smaller than they used to be (but still the same number of results on the page) and they do not reach all the way to the right of the panel (I understand this is because there is less detail in the results themselves)  

What should happen:

Should reach to the right of the panel or be more zoomed in/larger

**Comment by danfruehauf** [comment]
:+1:

**Comment by dnahodil** [comment]
I believe this is by design.

**Comment by pmbohm** [comment]
This is by design but....  its less than ideal. Technically the 'problem' should be fixed by changing the component that everything is nested in. It used to make sense when the portal was map centric and maximum space was given to the map
