### ISSUE TITLE
Faceted search - Don't show + when the only options will be those you've already selected

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#1591]
**Steps to reproduce**
On step 1 select a facet from the Parameter
Click on the `+` icon to select from that facet again
Keep adding more new selections to the facet
Click on the `+` icon to select from that facet again

**What does happen**
You can keep adding to the facet even though the only option(s) is the one you've already selected

**What should happen**
You shouldn't be able to add more selections to the facet when you'll only be able to select options you have already selected

**Comment by danfruehauf** [comment]
I think that shouldn't be tagged as a bug, but rather implemented correctly at the first place, no?

**Comment by dnahodil** [comment]
An idea:
Should we also not include any selection(s) you've already made from the list when adding a new selection. e.g. if you select 'Temperature of the Water Body' and then add a new selection to the facet then you shouldn't see 'Temperature of the Water Body' in the second selection list.

**Comment by dnahodil** [comment]
@danfruehauf It's a bit unclear. The work meets the acceptance criteria, but we've found a problem which needs to be fixed.

**Comment by jonescc** [comment]
How about I remove all useless options (drilldowns which won't result in a narrowing of the search) and only display the add button when there are useful options?

**Comment by jonescc** [comment]
Refer https://github.com/aodn/aodn-portal/compare/remove-useless-options?expand=1 for how this would work.
