### ISSUE TITLE
If no applicable top level parameters are set should not show in results

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1597]
Instance name: IMOS
            App version: 3.41.2
            Build date: Thu Feb 19 09:38:07 AEDT 2015
            Build number: 357
            Git ref: e9cec741231a49f2774f7397860b0be6cbdbb353

Steps to reproduce:

Select biological platform. Look at list of results

What should happen:

If there is no applicable parameter set then the row should not be seen

What does happen:

Parameter symbol of that which is not set show but with no text

![symbol only](https://cloud.githubusercontent.com/assets/2906602/6281485/842b25d4-b916-11e4-90e7-e6585bac111d.jpg)

**Comment by pblain** [comment]
If there are no parameters it would be better to leave the row and say "No parameters".  Users will then know what to expect.
