### ISSUE TITLE
geoserver extension redundant log line

### ISSUE THREAD

**Issue by danfruehauf** [aodn/aodn-portal#1599]
Every time you hit the filter plugin, you get a redundant log line such as:
```
24 Feb 16:47:22 WARN [geoserver.ows] - Could not get a ServiceInfo for service layerFilters thus could not check if the service is enabled
```

This can potentially blow up the log.

To reproduce, look at the geoserver log and run:
```
$ curl -v 'http://geoserver-systest.aodn.org.au/geoserver/ows?request=uniqueValues&service=layerFilters&version=1.0.0&workspace=imos&layer=soop_xbt_nrt_profiles_map&propertyName=XBT_line'
```

**Comment by dnahodil** [comment]
As discussed in the planning meeting. The fix for this is to register proper metadata about the plugin. This will also let us query GetCapabilities to see if the plugin is installed.

**Comment by dnahodil** [comment]
The changes to our plugins is going onto the backlog to go to JPSR next iteration.
