### ISSUE TITLE
gogoduck emails classified as spam in gmail

### ISSUE THREAD

**Issue by danfruehauf** [aodn/aodn-portal#1602]
Steps to repeat:
 * Select a gogoduck-able layer
 * Select a subset
 * Download as NetCDF
 * Use a gmail account when prompted for an email address
 * You should instantly get an email saying the job was registered

What should happen:
 * You get an email when the jobs is done with a download link

What does happen:
 * You get an email with the download link, but it's classified as spam by gmail

**Comment by jkburges** [comment]
I cannot get any emails.  I am trying with collection "CARS 2009 - Australian weekly sea water temperature" - is that definitely gogoduck?

**Comment by danfruehauf** [comment]
Verify an email was sent on the server itself.

It's a bit of an environment problem, so better if you test it on the server itself. So it's not a bug per se...

**Comment by jkburges** [comment]
Looks like an email is being sent, in any case:

<pre>2015-03-04 17:15:19,194 [quartzScheduler_Worker-2] INFO  grails.app.services.au.org.emii.gogoduck.job.NotificationService - Sending success email to 'jkburges@gmail.com' with report from '/mnt/ebs/tomcat7/gogoduck/data/gogoduck/1fd76bb3/report.txt'</pre>

**Comment by jkburges** [comment]
Yep, you just beat me @danfruehauf.

**Comment by jkburges** [comment]
I'm unsure how to proceed with this one.  It seems to me that even if gmail classifies an email as spam, I should still get it (albeit, in the spam folder) - which is what this bug report suggests will happen.  However, I'm not even seeing an email appear in spam, despite the email apparently being sent (according to the logs in "/var/log/mail.log").

Is there anywhere else these outgoing emails could be getting "stuck"?

**Comment by danfruehauf** [comment]
No idea, I actually do get emails from the duck. I can continue investigating it.

**Comment by danfruehauf** [comment]
We're not on DNSBL:
http://www.dnsbl.info/dnsbl-database-check.php

A diagnosis of an email is here below:
http://isnotspam.com/newlatestreport.php?email=ins-yq3dojb0%40isnotspam.com

**Comment by danfruehauf** [comment]
Spamassassin on my machine says:
```
Content analysis details:   (1.4 points, 5.0 required)

 pts rule name              description
---- ---------------------- --------------------------------------------------
 0.1 TW_DB                  BODY: Odd Letter Triples with DB
 1.3 RDNS_NONE              Delivered to internal network by a host with no rDNS
```

Looks like we get penalized for sending emails from a domain which doesn't resolve to the correct place + doesn't have reverse DNS.

**Comment by danfruehauf** [comment]
We cannot register on dnswl.org - because we don't have RDNS (reverse DNS) for our hosts on NSP.

**Comment by danfruehauf** [comment]
I think what we can do is the following:
 * Send at least one gogoduck email to anyone with a gmail address (if they are OK with that, and it's perfectly fine if they're not)
 * If it's classified as spam - declassify it
 * That way we /may/ teach the google spam filter that it's actually not spam

In addition we can:
 * Add a little message (not so sure where) that this email may or may not be classified as spam
 * Provide a direct link to the gogoduck job queue, so they can follow the progress

**Comment by dnahodil** [comment]
What about utilising a managed email service like mandrill.com? I believe they have ways to ensure emails sent through their service are not classified as spam. We also have low enough volume to be eligible for their free plan.

**Comment by danfruehauf** [comment]
@dnahodil Yeah, that's a good idea. They allow up to 12K emails on free tier. We'll never get close to that even.

It might entail some extra work on our side though. There's also www.sendgrid.com, not free, but virtually costs nothing:
https://sendgrid.com/pricing/lite_plan
That would put us back probably $0.10 a month :)

It's also (I think) easier than mandrill to integrate:
https://sendgrid.com/docs/API_Reference/Web_API/mail.html

But either would be good. Generally I don't think we should care about mail delivery.

**Comment by danfruehauf** [comment]
We get a worse score going via mandrill for some reason (on isnotspam.com):
http://isnotspam.com/newlatestreport.php?email=ins-j6ilbhuc%40isnotspam.com

However, I think it's still a better option. Thoughts on that?

Notice also we do get penalized for wording :/

**Comment by dnahodil** [comment]
I'm not familiar with isnotspam.com but if the service doesn't reduce our chances of being marked as spam then it's probably not worth the effort. Can we check how it would go with www.sendgrid.com? It looks like thay also have a free plan with up to 12k emails per month.

**Comment by danfruehauf** [comment]
It's virtually no effort to change to that - only some chef config to modify the config file.

I'll experiment with sendgrid as well, see how it goes.

**Comment by danfruehauf** [comment]
Better on sendgrid:
http://isnotspam.com/newlatestreport.php?email=ins-v1llgfcg%40isnotspam.com

Lets go with that I think and then we can improve the process overall so we do not rely solely on emails for notifications.

**Comment by danfruehauf** [comment]
Once this is deployed - I want to verify it works for @jkburges with his gmail account.
