### ISSUE TITLE
interface unresponsive with ncwms layers

### ISSUE THREAD

**Issue by danfruehauf** [aodn/aodn-portal#1603]
Steps to repeat:
 * Select a NcWMS layer from CSIRO (srs for instance)
 * Change dates

What should happen:
 * Interface is responsive (user can interact with other controls) while dates are being fetched

What happens:
 * Interface is not responsive

NOTE: This is apparent because the latency between our portal and CSIRO is not amazing. Happens as well when choosing for instance ACORN layers, but it's not as apparent.

**Comment by dnahodil** [comment]
Could you please add a bit more details of what you mean by 'Interface is responsive while dates are being fetched'. It'll help whoever comes to fix this, and help Kate to test it.

**Comment by danfruehauf** [comment]
Just did, let me know if it makes sense.

**Comment by dnahodil** [comment]
That's better, thanks. And "other controls" means like the geographic filter, and the other tabs?

**Comment by danfruehauf** [comment]
It's anything else unfortunately, the browser just jams while the AJAX request is running for some reason.
