### ISSUE TITLE
Malformed included css file

### ISSUE THREAD

**Issue by pmbohm** [aodn/aodn-portal#1604]
### What happens

This incorrect url is being written into the portal pages
```
<link rel="stylesheet" type="text/css" href="/aodn-portal/home/css?v=1425423212840"/>
```

**Comment by danfruehauf** [comment]
@pmbohm How can I witness this?

**Comment by pmbohm** [comment]
`<link rel="stylesheet" type="text/css" href="/aodn-portal/home/css?v=1426565660596"/>` will be in the generated HTML source

**Comment by danfruehauf** [comment]
If i... hit what page? the main page?

**Comment by pmbohm** [comment]
I see it on splash, and step one. probably on all then..

**Comment by danfruehauf** [comment]
Perhaps it'd be good to add it to the bug description.

**Comment by pmbohm** [comment]
Sorry but it is all there in the bug description. There is no confusion

**Comment by danfruehauf** [comment]
To be honest, I still can't quite figure out what's wrong.

**Comment by pmbohm** [comment]
Don't worry, I'll do it

**Comment by dnahodil** [comment]
> There is no confusion

There clearly *is* confusion.

@pmbohm Your bug report does not say what you think is wrong with the URL. Why do you think it is invalid? @danfruehauf was trying to get more information out of you because your bug report is inadequate.

**Comment by danfruehauf** [comment]
OK, so it's not an incorrect URL, the URL was always correct, but the following error may appear in some browsers if there's no branding activated:
```
Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://dev.aodn.org.au:8080/aodn-portal/home/css?v=1427070599771".
```
