### ISSUE TITLE
Large CSV downloads

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#1620]
Steps to reproduce

1. On Step 1, select:  IMOS - Australian National Facility for Ocean Gliders (ANFOG) - delayed mode glider deployments (search by "Platform > Glider" facets)
2. On Step 2, filter by bounding box -30N, 150E, -70S, 100W and platform_type = seaglider
3. Go to step 3 and download as CSV

What should happen

1. It starts downloading
2. I get a really big file

What does happen

1. Download never starts

See it happen here (at the 18:50 mark) ...
https://youtu.be/xf1FnLnyhvc?t=18m50s

**Comment by dnahodil** [comment]
Possibly related to #1623

**Comment by jkburges** [comment]
The query is taking a while to return results.  The download does start...eventually.

Here's an example query:

```sql
SELECT "file_id","deployment_name","platform_type","platform_code","time_coverage_start","time_coverage_end","TIME","TIME_quality_control",
"LATITUDE","LATITUDE_quality_control","LONGITUDE","LONGITUDE_quality_control","DEPTH","DEPTH_quality_control","PRES","PRES_quality_control",
"TEMP","TEMP_quality_control","PSAL","PSAL_quality_control","DOXY","DOXY_units","DOXY_quality_control","CDOM","CDOM_quality_control",
"FLU2","FLU2_quality_control","UCUR","UCUR_quality_control","VCUR","VCUR_quality_control","CNDC","CNDC_quality_control","DOXY_raw","HEAD",
"HEAD_quality_control","UCUR_GPS","UCUR_GPS_quality_control","VCUR_GPS","VCUR_GPS_quality_control","VBSC","VBSC_quality_control","OCR443",
"OCR443_quality_control","OCR443_1","OCR443_1_quality_control","OCR443_42","OCR443_42_quality_control","OCR443_52","OCR443_52_quality_control",
"OCR443_8","OCR443_8_quality_control","OCR443_9","OCR443_9_quality_control","OCR455_9","OCR455_9_quality_control","OCR456_6",
"OCR456_6_quality_control","OCR470_3","OCR470_3_quality_control","OCR470_5","OCR470_5_quality_control","OCR489_1","OCR489_1_quality_control",
"OCR489_2","OCR489_2_quality_control","OCR489_4","OCR489_4_quality_control","OCR489_59","OCR489_59_quality_control","OCR489_64",
"OCR489_64_quality_control","OCR489_7","OCR489_7_quality_control","OCR520","OCR520_quality_control","OCR520_3","OCR520_3_quality_control","OCR554_2",
"OCR554_2_quality_control","OCR554_24","OCR554_24_quality_control","OCR554_4","OCR554_4_quality_control","OCR554_77","OCR554_77_quality_control",
"OCR554_9","OCR554_9_quality_control","OCR555_3","OCR555_3_quality_control","OCR555_4","OCR555_4_quality_control","OCR664_67",
"OCR664_67_quality_control","OCR664_89","OCR664_89_quality_control","OCR669_3","OCR669_3_quality_control","OCR670_2","OCR670_2_quality_control",
"OCR670_8","OCR670_8_quality_control","OCR670_9","OCR670_9_quality_control",encode(ST_AsEWKB("geom"),'base64') as "geom" 
FROM "anfog_dm"."anfog_dm_trajectory_data" 
WHERE  ("geom" && ST_GeomFromText('POLYGON ((100 -70, 150 -70, 150 -30, 100 -30, 100 -70))', 4326) 
AND ST_Intersects("geom", ST_GeomFromText('POLYGON ((100 -70, 150 -70, 150 -30, 100 -30, 100 -70))', 4326)) 
AND "platform_type" LIKE 'seaglider' ) LIMIT 100000
```

**Comment by jkburges** [comment]
I think this line is key:

```sql
ST_Intersects("geom", ST_GeomFromText('POLYGON ((100 -70, 150 -70, 150 -30, 100 -30, 100 -70))', 4326))
```

The startup cost in the query planner with the above is 2437594.

Changing it to a much smaller area, e.g.:

```sql
ST_Intersects("geom", ST_GeomFromText('POLYGON ((100 -70, 110 -70, 110 -60, 100 -60, 100 -70))', 4326))
```

gives startup cost of 0.57

**Comment by jkburges** [comment]
@jonescc I could do with some help interpreting the query plans :confused:

**Comment by jkburges** [comment]
So after some help from @jonescc, we have determined that the query planner is choosing to perform a `Bitmap Heap Scan` on the large `measurements` table.  Whilst this gives better total performance, it gives a much slower startup cost (seen as latency as far as the portal user is concerned).

e.g. with bitmap scans disabled, the startup cost is as low as 43.

**Comment by jkburges** [comment]
@pblain how would you like to proceed with this bug? We can fiddle easily with the postgres parameters when testing things in isolation like I did above, but it's a much bigger job to tweak things permanently so that *all* geoserver queries still run acceptably (both startup and total cost).

**Comment by dnahodil** [comment]
One solution might be similar to what you did in AATAMS I think, @jkburges. Where you have a spinner show in the window to try to indicate that something is happening. It disappears once the data starts streaming.

**Comment by dnahodil** [comment]
@jkburges also pointed out that there is an estimated size indicator with a yellow exclamation mark showing that it was going to be a big download. So either:
1) The user didn't see that estimated size indicator
2) They did see the indicator but didn't associate that with the fact the download took ages to start (or in their mind, never started)

Improving that indicator might help, and that could be done in conjunction with my suggestion from above.

**Comment by jkburges** [comment]
I've been thinking about this overnight (sadly).  Rather than trying to configure postgres to deal with every possible layer, optimising for both start up and overall cost - an impossible task - let's design the system to cope (i.e. be usable) for these kinds of situations.  i.e. downloads with some startup latency.

WPS sounds like it could be the go, perhaps that's where we should invest our efforts?

**Comment by jkburges** [comment]
Discussed this with @pblain and @dnahodil - we're going to go with something like that described in https://github.com/aodn/aodn-portal/issues/1620#issuecomment-85857865

**Comment by jkburges** [comment]
Ref: http://gruffcode.com/2010/10/28/detecting-the-file-download-dialog-in-the-browser/

**Comment by pblain** [comment]
Looks good @jkburges !
