### ISSUE TITLE
Start/End Date on step 3 are switched

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1626]
Instance name: IMOS
            App version: 3.39.1
            Build date: Tue Jan 20 17:08:04 EST 2015
            Build number: 321
            Git ref: 5a01b135de233f242c01e5a595a069639074a2e8

Steps to reproduce:

Select any collection to add to map.

Select a from date and a to date, ie From: 2015/02/17 To: 2015/02/18

Proceed to step 3

What should happen

Filters for collection read start date: 2015/Feb/17 end date: 2015/Feb/18

What does happen:

They read end date: 2015/Feb/17 start date: 2015/Feb/18

**Comment by dnahodil** [comment]
Yeah, this has bugged me for ages. It's *technically* correct but it is confusing and needlessly complicated.
