### ISSUE TITLE
Portal has errors in Latest Version 36.0.1 of Firefox with Firebug/tools

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1629]
There is a bug in the latest version of Firefox (36.0.1) where Portal 123 freezes the whole browser if developer tools or Firebug are being used. 

I don't think we can fix this ourselves, but we probably need to be aware of it if anyone contacts us.

So as with #1175 we will add a note into help

Steps to reproduce:

Open https://imos.aodn.org.au/imos123/ in firefox 36.0.1, wait until loaded and then click open the firebug tool. Click get ocean data button.

What should happen:

Taken to step 1 on portal

What does happen:

Whole browser freezes, then get the popup asking if we wish to stop script.
![36 1](https://cloud.githubusercontent.com/assets/2906602/6699309/d254191c-cd54-11e4-9f9c-c404764693cf.jpg)

![36 2](https://cloud.githubusercontent.com/assets/2906602/6699311/d69c62ea-cd54-11e4-979a-050d973cacf9.jpg)

![36 3](https://cloud.githubusercontent.com/assets/2906602/6699313/d90ff5fa-cd54-11e4-97b9-f8fd02911b3c.jpg)

**Comment by pblain** [comment]
Given current time constraints I am closing this bug.  It is likely that we will re-open it down the track.
