### ISSUE TITLE
Difficult to tell which geoserver layer to configure filters in

### ISSUE THREAD

**Issue by jkburges** [aodn/aodn-portal#1630]
This one is a usability issue for project officers etc who want to configure filters.

**Steps to reproduce**
1. In the portal, add any collection, e.g. "IMOS - Argo Australia Profiles"
2. In step 2, the collection is entitled "IMOS - Argo Australia Profiles"
3. Go to geoserver in order to configure filters for layer.

**What happens**
At this point, it's not obvious *which* layer I should be configuring filters for.  A search on "argo" results in no less than 5 layers.

**What should happen**
It should be obvious from the portal (somehow) exactly which layer I need to be configuring in geoserver.

**Comment by danfruehauf** [comment]
Is that regarding the idea that we have a WMS/WFS coupling here?

Following a convention here can definitely help.

**Comment by jkburges** [comment]
Not so much, it's more to do with the fact that the collection title shown in the portal comes from geonetwork, whereas to configure the filter I need the geoserver layer name.

Yes - this connection can be derived by looking at the portal, geonetwork and geoserver - but, I *bet* that people still pick the wrong layer to configure (because I certainly had trouble).  We could definitely make it easier.

**Comment by danfruehauf** [comment]
Yeah, that's a good point. However, this affects only project officers. I bet we can easily find which layer the filters are coming from etc.

**Comment by danfruehauf** [comment]
This needs a tag, either bug or enhancement.

**Comment by jkburges** [comment]
It's a usability issue - what is that - a bug or an enhancement?

**Comment by danfruehauf** [comment]
Yep, it's a usability issue for POs only though. We can also say that if a metadata layer is defined by the same person - he/she should know how the layers related to each other.

**Comment by pmbohm** [comment]
+1 Not fixable by code changes. Its a content issue.
The layer name can be found by looking at the GetMap request url's using Firebug or Chrome Console
