### ISSUE TITLE
Dragging layer below or above makes that layer disappear on Step 2 

### ISSUE THREAD

**Issue by xhoenner** [aodn/aodn-portal#1633]
On production portal
IMOS Portal v3.39.2, build date: Wed Mar 11 15:49:44 AEDT 2015

<h3> Steps to reproduce <h3>

Select a data collection on Step 1 (e.g. IMOS - AATAMS Facility Satellite Relay Tagging Program - Near real-time data). 
From Step 2, go back to Step 1.
Select another data collection on Step 1 (e.g. IMOS - SOOP-Sea Surface Temperature (SST) Sub-facility - Near real-time data).
On Step 2, drag the layer at the top below, or vice versa.

<h3> What happens? <h3>

The layer that has been moved is not getting displayed anymore, and the little icon near the name of the layer that has been moved keeps spinning.

<h3> What should happen? <h3>

The layer that has been moved should be displayed.

**Comment by danfruehauf** [comment]
This is the re-incarnation of this bug I think:
https://github.com/aodn/aodn-portal/issues/1134

**Comment by xhoenner** [comment]
@danfruehauf, yes in a sense, except that this time the layer doesn't show up anymore.

**Comment by kereid** [comment]
I cannot see this in firefox 36.0.1 but I do see it in chrome

**Comment by kereid** [comment]
Not sure if relevant but as this is a testcase in testrail (due to 1134) I have tried it again in chrome and now it I'm not seeing it....

**Comment by xhoenner** [comment]
> as this is a testcase in testrail (due to 1134)

@kereid :anguished: what does that mean?

**Comment by kereid** [comment]
I just meant I have a testcase to repeat the steps in 1134 every round of testing to make sure it does not happen again, so I had come to that case in testrail today during testing and did it and it didn't do what we both saw earlier today and yesterday.

**Comment by kereid** [comment]
But now I read what I wrote it isn't exactly clear lol!

**Comment by xhoenner** [comment]
> But now I read what I wrote it isn't exactly clear lol!

I didn't want to be tactless but now that you've admitted it, yes Kate, it didn't make much sense ^_^.

> it didn't do what we both saw earlier today and yesterday.

Weird, I'm still seeing that bug on Chrome on my machine.

**Comment by pmbohm** [comment]
@pblain The work on accordions will nullify this bug.
Should it still be a bug?

**Comment by pblain** [comment]
That's correct @pmbohm, the accordion makes this irrelevant.  Let's not waste time on it.
