### ISSUE TITLE
Layers showing on Prod and Systest that aren't in our ncWMS server

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1636]
Seeing in Systest and production

Instance name: IMOS
App version: 3.39.2
Build date: Wed Mar 11 15:49:44 AEDT 2015
Build number: 368
Git ref: 73fabe9824be13dc354a3d8b3bacc0b37af7d114

Steps to reproduce:

On step 1 select satellite as platform and then proceed to page 2 of the results, add the first 2 on the page -

IMOS - SRS SATELLITE - OC MODIS - 01 DAY - CHLOROPHYLL A CONCENTRATION (OC3 – NPP) Nanoplankton: BREWIN ET AL 2012

and

IMOS - SRS SATELLITE - OC MODIS - 01 DAY - CHLOROPHYLL A CONCENTRATION AlGORITHM (GSM – NPP): Eppley-VGPM

What should happen:

They load as expected with details and visible on map

What does happen:

They do not load and we see red error triangle and the second one doesn't even have a "human-readable" title.

Spoke to Angus about this one and he looked them up in ncwms server for me.

**Comment by pblain** [comment]
Is this a content issue?

**Comment by danfruehauf** [comment]
I believe so. Unless @kereid believes otherwise. Virtually anything can be in the metadata - the fact it doesn't load doesn't mean it's a portal bug...

**Comment by dnahodil** [comment]
Yeah, for next time this is a content issue. I've just checked and these layers are currently working in prod.
