### ISSUE TITLE
updating thredds version ?

### ISSUE THREAD

**Issue by lbesnard** [aodn/aodn-portal#1652]
See ref https://github.com/aodn/imos-user-code-library/issues/7

Updating the THREDDS fix a few issues, including missing display of global attributes

**Comment by danfruehauf** [comment]
This issue needs a tag.

**Comment by dnahodil** [comment]
This wont get looked at if it is in here, @lbesnard. You should put it in the backlog https://github.com/aodn/backlog

**Comment by lbesnard** [comment]
@dnahodil I don't think it's up to me to add this to the backlog. Always thought jpsr would do it. wrong, right ?

**Comment by dnahodil** [comment]
I think it's okay for us to put stuff on the backlog (provided we use the correct format for items). But if you prefer you could talk to @smancini and get him to add it to the backlog.

I'm pretty confident this issue (as it is) will never get picked up from this list.

**Comment by pblain** [comment]
As product owner I am responsible for maintaining the backlog.  So I moderate it and "groom" it ready for planning sessions.  But I'm happy for anyone in the organisation to add items for consideration.  If they are malformed or don't belong on the backlog, I will edit or delete them.
