### ISSUE TITLE
facets category for SRS

### ISSUE THREAD

**Issue by lbesnard** [aodn/aodn-portal#1657]
The current way of looking for collections in the 123 portal doesn't work very well for the SRS products. A product type facet is lacking. 

## Example
By selecting in the portal : 
 * Measured parameter > Physical-Water > Temperature > Skin temperature of the water body (10)
 * Platform > Satellite >  orbiting satellite (10) 

Already 10 products appear in one page, all ordered randomly. Another 15 products should appear, creating a big sense of confusion to look for a particular product. We can't add new and currently awaiting collections on the portal, otherwise the help desk will receive a lot of questions :"which product should I use ?" .

## Solution

A new facets could read from the metadata record a new xml entry, such as product_category. This new facets would have :

 * single satellite swath (L3U)
 * single satellite, multiple swaths (L3C products) > [1 day | 3 days | 6 days ...] > [AVHRR11 | AVHRR12 ...| AVHRR19] > [ day | night | day and night ]
 * multiple satellites, multiple days (L3S products) > [ 1 day | 3 days | 6 days ]> [day | night | day and night]

Every ">" contains a sub category. 

This new feature is really important as it makes the portal definitely more attractive and usable to the growing satellite community.

**Comment by pblain** [comment]
@lbesnard nice one.  I added it to the backlog https://github.com/aodn/backlog/issues/83

**Comment by pblain** [comment]
Moved to backlog https://github.com/aodn/backlog/issues/393
