### ISSUE TITLE
Download confirmation box should provide directions to metadata

### ISSUE THREAD

**Issue by atkinsn** [aodn/aodn-portal#1661]
After discussions with Marian and @dnahodil I realised that the download confirmation box firstly only comes up only once in a session (I believe it should prompt the user upon each download choice), and secondly that whilst the text says: "I can't remember what is says exactly, and can't go back and see!" but it says that the data might have some licence requirements etc, but it doesn't direct the user to where this information resides. I think at least in brackets the user should be directed to the "view metadata record" link in step 3 for each data collection.

Note @pblain I will leave it up to you to assign a label (re. @dnahodil )

**Comment by pblain** [comment]
![image](https://cloud.githubusercontent.com/assets/2802359/6795875/1bec5be8-d23c-11e4-9e47-9daec9086b68.png)

**Comment by pblain** [comment]
Added to the backlog: https://github.com/aodn/backlog/issues/85
