### ISSUE TITLE
Date filter changes go to Google Analytics twice

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#1671]
**Steps to reproduce**
Add the following to trackFilterUsage(...) in trackUsage.js:
``` javascript
console.log(
    OpenLayers.i18n('filtersTrackingCategory'),
    OpenLayers.i18n(actionKey),
    label,
    collection
);
```
Open the Portal and add the Argo layer
Use the date picker to choose a date
Look at the javascript console
Click off the date pick
Look again at your javascript console

**What should happen**
Changing date is logged to Google Analytics once

**What does happen**
Two events are logged to Google Analytics

**Comment by jonescc** [comment]
Fixed by #1670
