### ISSUE TITLE
Clear subset does not clear acorn date filter

### ISSUE THREAD

**Issue by jonescc** [aodn/aodn-portal#1673]
systest.aodn.org.au
Instance name: IMOS
App version: 4.0.0
Build date: Thu Mar 26 13:33:50 AEDT 2015
Build number: 1
Git ref: 22cd9f53c67f198551731bb0a8c0facff69a6906

To reproduce, 

* select an acorn layer and go to step 2
* select a from or to date from the  list and then,
* hit the clear subset button.

What I expect to see is the changes I've made cleared. 

Instead, the dates remain modified.

**Comment by danfruehauf** [comment]
@jonescc Which commit is that, that is missing?

**Comment by danfruehauf** [comment]
Or, hold on. I misread it, I'm trying to understand if `no_db` is missing something that should be there, or... Is it a new bug?

**Comment by jonescc** [comment]
I'd suggest a new bug, but wouldn't know without investigating.

**Comment by danfruehauf** [comment]
Does it happen in prod?

**Comment by jonescc** [comment]
Yeah happens in prod as well - so an old bug not a nodb one.
