### ISSUE TITLE
Filter "loading..." in step 3

### ISSUE THREAD

**Issue by danfruehauf** [aodn/aodn-portal#1674]
Discovered by @kereid after no_db was deployed to systest.

Instance name: IMOS
App version: 4.0.0
Build date: Thu Mar 26 13:33:50 AEDT 2015
Build number: 1
Git ref: 22cd9f53c67f198551731bb0a8c0facff69a6906

Steps to reproduce:
 * Select a data collection
 * Go to step 3

What should happen:
 * No filters showing

What happens:
 * All filters are showing with "loading..." label

**Comment by dnahodil** [comment]
Turns I I did fix this bug as part of my filters work. So this should not happen after next release to systest.
