### ISSUE TITLE
Two time filters require different titles

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1675]
Found in sys-test but is also in production:

Steps to reproduce:

Add AATAMS Facility - Tracking of Short-Tailed shearwaters collection to map (Platform >biological to narrow down) 

What should happen:

Taken to step 2 and see 2 time filters one labelled as the "time stamp" and the other as release date ( @danfruehauf confirmed this is what they are)

What does happen:

See Temporal extent with 2 date selection filters underneath and cannot tell why they are there

**Comment by danfruehauf** [comment]
Thanks @kereid ! Good spotting!
