### ISSUE TITLE
Temporal extent filter broken on portal-edge

### ISSUE THREAD

**Issue by anguss00** [aodn/aodn-portal#1691]
Instance name: IMOS, on portal-edge.aodn.org.au
App version: 4.0.0
Build date: Thu Mar 26 13:33:50 AEDT 2015
Build number: 1
Git ref: 22cd9f53c67f198551731bb0a8c0facff69a6906

Steps to reproduce:

Go to step1 on portal-edge, select SOOP-SST near real time layer.
Select a date in the temporal extent filter.

Observed behaviour:

Red triangle of doom, stack of 500ing geoserver requests, as follows:
http://geoserver-123.aodn.org.au/geoserver/wms?LAYERS=imos%3Asoop_sst_nrt_trajectory_map&TRANSPARENT=TRUE&FORMAT=image%2Fpng&EXCEPTIONS=application%2Fvnd.ogc.se_xml&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&QUERYABLE=true&SRS=EPSG%3A4326&CQL_FILTER=TIME%20%3E%3D%20%272014-10-13T00%3A00%3A00Z%27&BBOX=41.484375,41.484375,93.515625,93.515625&WIDTH=296&HEIGHT=296

Expected behaviour:

filter is applied as per systest. No red triangle

**Comment by dnahodil** [comment]
I'm happy to help anyone who looks into this as I've touched a lot of this code recently.

**Comment by dnahodil** [comment]
@anguss00  and I have confirmed that this problem is just because the prod GeoServers don't have the latest version of the filters plugin, yet. Systest works fine because that GeoServer *does* have the latest version of the plugin.

**Comment by dnahodil** [comment]
Until the prod GeoServers are updated (which will happen this iteration if testing does well) time range filters will be broken on edge and on a dev Portal if the dev Portal uses prod GeoNetwork and GeoServers (which they do by default).
