### ISSUE TITLE
Filters for non-IMOS collections not available

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1697]
App version: 4.1.0
            Build date: Thu Apr 02 10:31:40 AEDT 2015
            Build number: 2
            Git ref: 66644d52db0a7f852d6a4f48d6725318390f16ce

Steps to reproduce:

Add collections that are not IMOS such as CATAMI [institute is Commonwealth of Australia(Geoscience Australia)] or RLS (institute is IMAS), taken to step 2

What should happen:

Filters are available for user to alter

What does happen:

There are no filters to select from at all

**Comment by dnahodil** [comment]
I've just discussed this with @pblain. We only migrated filters for our GeoServer so until the GeoServers hosting these layers get the filter plugin then they won't have configured filters. @pblain is going to talk to IMAS now about the RLS layers.

The CATAMI project has been wound up so those layers should be removed anyway.
