### ISSUE TITLE
Filter titles are not consistent

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1698]
Not sure if this is a content issue..

App version: 4.1.0
            Build date: Thu Apr 02 10:31:40 AEDT 2015
            Build number: 2
            Git ref: 66644d52db0a7f852d6a4f48d6725318390f16ce

Steps to reproduce:
Add collections:
* IMOS - ANMN National Reference Stations - Darwin and Yongala - Near real-time meteorology and oceanographical data
* IMOS - Australian National Mooring Network (ANMN) Facility - Temperature and salinity time-series
* IMOS - Australian National Mooring Network (ANMN) Facility - Current velocity time-series
 
When taken to step 2 look at the filter names:

What does happen:

The first two are inconsistent in formatting (the second is even inconsistent within it's own filters.

What should happen:
They should all be consistent with no underscore and correct use of capital letters like the third collection added

**Comment by dnahodil** [comment]
Previously we tried to massage the filter names into a nice format ('platform_code' became 'Platform Code'). This change was not brought forward in the filters rework (*mea culpa*).

I want to chat to @pblain about this, though. Although it will help with naming consistency of filters in the Portal it might be confusing of problematic for some data providers, and it doesn't do anything you couldn't do yourself.

**Comment by dnahodil** [comment]
Just as an example, when I say 'problematic' this is the sort of thing I mean:
A filter called `Length (mm)` would become `Length (Mm)`

**Comment by dnahodil** [comment]
I've chatted to @pblain about this. The Portal should display labels as they are configured in GeoServer so we shouldn't title case them in the Portal. I've added an issue for this: https://github.com/aodn/geoserver-layer-filter-extension/issues/15

For the release we will need to update the current filter configurations so the filter names appear as they did in the previous Portal.

**Comment by dnahodil** [comment]
To be clear, the format that we'll need to update the current filter configurations to is:
All underscores replaced with spaces. 
and
First letter of each word is upper case.

e.g. `drifter_id` -> `Drifter Id`

**Comment by danfruehauf** [comment]
I'll do it.

Just verifying we're after `Id` rather than `ID`, yes?

**Comment by dnahodil** [comment]
Yeah, lowercase 'd' to maintain current behaviour.

**Comment by danfruehauf** [comment]
https://github.com/aodn/geoserver-config/pull/249

Is that what you're after?

**Comment by dnahodil** [comment]
That's it.
