### ISSUE TITLE
Step 3 filter ordering is not consistent

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#1706]
**Steps to reproduce**
Add the Argo data collection
Check the 'Oxygen' filter
Select a float from the drop-down
Add a time range
Go to step 3

**What should happen**
Filters should be displayed in same order as step 2

**What does happen**
The filters display in a different order

**Comment by pblain** [comment]
Given current time constraints I am closing this bug.  It is likely that we will re-open it down the track.
