### ISSUE TITLE
Step 2 date filter should load date range from filter

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#1707]
**Steps to reproduce**
Add Argo data collection
Open the 'from' and 'to' date pickers

**What does happen**
Minimum date selectable is 1/1/1970
Default of 'from' date picker is today

**What should happen**
GeoServer filter plugin is used to get the possible values
Date pickers should be disabled while possible value range is loading
The default of the 'from' date picker is the earliest of the dates in the possible range
The default of the 'to' date picker is the latest of the dates in the range

**Comment by dnahodil** [comment]
This was the behaviour a long time ago but it got lost along the way somewhere (over a year ago, I'd guess). This is how ncWMS temporal extent works and is how WMS filters should work, again.

**Comment by dnahodil** [comment]
There are a few considerations here.

1) We should see how many unique values are returned. Considering we only want the first and last it'd be nice not to transfer heaps of timestamps just to throw them away.
2) We have to see how this will work on the map layer (dates will need to be represented there in some form).
3) We will need to ensure this works for time-range layers.

**Comment by pmbohm** [comment]
Tested this with Argo. GetFilterValues query took 13.05s for a response which is too slow

**Comment by dnahodil** [comment]
Agreed. Sounds like we might need to look at a min/max solution if we want to have this behaviour.

**Comment by pmbohm** [comment]
This bug requires new geoserver filters extension work
aodn/geoserver-layer-filter-extension#23

**Comment by danfruehauf** [comment]
After having some adventures with setting available dates in NcWMS I think the better approach would indeed be min/max, as @dnahodil suggests. It'll require just the parsing of 2 dates and setting a simple range in the date picker.

**Comment by pmbohm** [comment]
After discussion with @dnahodil  and @pblain, this bug will soon no longer be an issue when the planned general date range picker for all collections is implemented.
