### ISSUE TITLE
Step 2 'Info' Tab - Broken Links for AATAMS Collections

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1717]
Steps to reproduce:

Add AATAMS collections such as IMOS - AATAMS Facility - Satellite Relay Tagging Program - Delayed mode data or IMOS - AATAMS Facility - Tracking of Short-tailed shearwaters

Click the info tab open and select the link titled "Link to all marine mammal CTD tag data held by IMOS. Data are in NetCDF format, grouped by year, tag batch and project name."

What should happen:

Taken to thredds server successfully

What does happen:

Get a 404 error.

Not sure if this is similar to  #1613

**Comment by danfruehauf** [comment]
I think it's more of a content problem. I'm pretty sure those links come from the metadata and we display them as is. Someone correct me if I'm wrong.

**Comment by smancini** [comment]
Dan is correct, it is a content problem. I will fix that now

**Comment by smancini** [comment]
Fixed

**Comment by danfruehauf** [comment]
:+1:
