### ISSUE TITLE
No indication of error for GoGoDuck job

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1728]
This is the exact same issue as a Gogoduck bug (#73) that I loaded on the 5th February.

Steps to reproduce:

Attempt a download for SRS data ie 
IMOS - SRS Satellite - SST L3S - 01 day composite - night time but do not set a bounding box and set the time for 1 year so that it is too big.

What should happen:

Get an email indicating that it is too big.

What does happen:

Get a failed notification but does not indicate why it failed.

**Comment by danfruehauf** [comment]
Fair enough. But you did get my email, yes?

**Comment by kereid** [comment]
Yes thanks for doing that, my bad! But the ones that were failing in a shorter amount of time just list the files being processed in the aggregation report and it just stops whereas for an ACORN collection it will indicate that "you have requested x number of files and only y number can be processed".

**Comment by danfruehauf** [comment]
We might have been hitting a disk limit there. This /should/ and probably will be addressed as a backlog item more than a bug. But leave it open - so we don't forget about it.

The backlog item will provide better scoring of the job. Aggregating 200 SRS files can be much bigger than aggregating 2000 ACORN files yet now we still treat them the same...

**Comment by pblain** [comment]
We need to allow large aggregations if we want this to be a useful service.  I'm less concerned about the error message and more concerned that legitimate (albeit large) aggregations cannot be processed.

**Comment by danfruehauf** [comment]
@pblain @kereid I'm not going to properly fix it, however what I am going to do in order to mitigate the problem is:
 * Use a different storage partition to run the aggregations on (so more than 10GB are available)
 * Enlarge that storage partition to 80GB, so there's actually space for the aggregations to run

**Comment by danfruehauf** [comment]
These 2 PRs will enable bigger jobs to run as they will not run on `/tmp` which is usually small (10-20GB):
https://github.com/aodn/chef/pull/104 - set the correct temp directory for tomcat
https://github.com/aodn/go-go-duck/pull/104 - allow gogoduck to use the temp directory used by tomcat (java.io.tmpdir)

**Comment by danfruehauf** [comment]
Deployed, can be closed.

**Comment by danfruehauf** [comment]
I'm reopening it as there is an apparent problem with long aggregations that get killed in the middle - there's simply no error and the user is left in the dark.

Here is an example:
https://gogoduck.aodn.org.au/gogoduck/job/b69dbf85
