### ISSUE TITLE
Bounding Box stops functioning if user goes off side of map

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1742]
App version: 4.3.4
            Build date: Wed Apr 29 15:10:45 AEST 2015
            Build number: 9
            Git ref: 456d2368e6b2c3cda0f9c64e2643809a0a5441cd
        -->
This is also in production

Steps to reproduce:

Add any collection to the map. When taken to step 2 start drawing a bounding box anywhere and then run the mouse off the side of the map. Bring the curser back over the map

What should happen:

The draw functionality is still active and the box will shrink or enlarge with mouse movement

What does happen:

The functionality is stopped as though the user has double clicked and will need to click again to start a new bounding box.

**Comment by danfruehauf** [comment]
Mmmm.... Happens also in production BTW.

**Comment by pmbohm** [comment]
This is standard OpenLayers behaviour. Only polygon drawing will let the mouse leave the map and return.
