### ISSUE TITLE
Step 2 number filter gives javascript error

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#1744]
> App version: 4.2.1
> Build date: Fri Apr 17 16:24:33 AEST 2015
> Build number: 4
> Git ref: fee6a717030ec18a707839d7a160d5a9798e1315

**Steps to reproduce**
- Add a collection with a number filter to the map (e.g. [Platform: float], NOAA Drifters)
- On step 2 enter a number into the text field without having first chosen an operator

**What does happen**
- Javascript error in console

> TypeError: record is undefined
> http://portal-systest.aodn.org.au/imos123/js/portal-all.js?v=4.3.4
> Line 6401

**What should happen**
- No error in console
- Filter should not be applied (as it is invalid without an operator)

**Comment by smancini** [comment]
Testing
