### ISSUE TITLE
Citation suggestion and licence details on step 3 are derived from metadata where possible

### ISSUE THREAD

**Issue by keaves** [aodn/aodn-portal#1752]
Enhancement request:

Would it be possible for the portal step 3, data download: Licence and use limitations: 
(this part)
![image](https://cloud.githubusercontent.com/assets/10750046/7558714/f4f0ab5c-f7ed-11e4-8f16-3f0483c7e38b.png)
attempt to discover creative commons and citation suggestions from the metadata record?
Specifically and for example:
•	Creative Commons licence type
•	Attribution Constraints
•	Other Constraints
•	Use limitation

Example of GeoNetwork disclaimer (gathers the information from the metadata record xml)
![capture1](https://cloud.githubusercontent.com/assets/10750046/7558696/9cae51ce-f7ed-11e4-962f-341818af5b14.JPG)
![capture2](https://cloud.githubusercontent.com/assets/10750046/7558678/4a1a4e5e-f7ed-11e4-8bc3-2e8165d68974.JPG)

Perhaps if no license information is found in the metadata, default back to the standard agreement as it is now?

**Comment by pblain** [comment]
This is covered by a recent enhancement
