### ISSUE TITLE
Removing data collections quickly that have been added via ctrl click results in double select button

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1757]
App version: 4.4.1
            Build date: Fri May 08 17:06:37 AEST 2015
            Build number: 12
            Git ref: eb55aa288ba068b736d1c7a59d2fe61fa71f8c0e

This is also in production

Steps to repeat:

Add 5-6 random collections to the map using ctrl click function (hold control key down while clicking to stay on step 1)

Proceed to step 2 here align mouse pointer over the "remove" cross on the collection at the top of the list.

Quickly and continuously click until all collections have been removed, 

Go back to step 1

What should happen:

All results only have 1 select button

What does happen:

Collections have 2 select buttons sometimes even 3

**Comment by danfruehauf** [comment]
Another way of recreating that:
 * Go to a link with a `uuid=` link (such as http://portal-edge.aodn.org.au/imos/home?uuid=4402cb50-e20a-44ee-93e6-4728259250d2)
 * Go to step 1
 * Witness multiple select buttons
