### ISSUE TITLE
Additional formatting on information sourced from the metadata record (step 2 and 3)

### ISSUE THREAD

**Issue by keaves** [aodn/aodn-portal#1771]
Aesthetic enhancement request:
To assist users in finding additional resources and to make the Info tab easier to read.
Perhaps these links could be separated by?
Supplementary downloads | Online resources | Additional resources

Supplementary downloads could be defined from the metadata by Online Resources with the following protocols;
`<gmd:protocol>`
`<gco:CharacterString>WWW:DOWNLOAD-1.0-http--downloadother</gco:CharacterString>`
or
`<gmd:protocol>`
`<gco:CharacterString>WWW:DOWNLOAD-1.0-http--downloaddata</gco:CharacterString>`

Online resources could be defined from the metadata by Online Resources with the following protocols;
`<gmd:protocol>`
`<gco:CharacterString>WWW:LINK-1.0-http--link</gco:CharacterString>`
or
`<gmd:protocol>`
`<gco:CharacterString>WWW:LINK-1.0-http--related</gco:CharacterString>`

Additional resources could be defined from the metadata by Online Resources with any other protocols than the previously sorted ones. e.g.
`<gmd:protocol>`
`<gco:CharacterString>WWW:DOWNLOAD-1.0-ftp--download</gco:CharacterString>`
or
`<gmd:protocol>`
`<gco:CharacterString>WWW:LINK-1.0-http--rss</gco:CharacterString>`

The metadata point of truth could be separated or remain at the top of the list:
`<gmd:protocol>`
`<gco:CharacterString>WWW:LINK-1.0-http--metadata-URL</gco:CharacterString>`

**Essentially what I am trying to describe is to make this:**

![image](https://cloud.githubusercontent.com/assets/10750046/7851373/131106b2-0532-11e5-8ae1-b64b97910abf.png)

**Look something more like this:**

![image](https://cloud.githubusercontent.com/assets/10750046/7851388/48e7177c-0532-11e5-8685-50a0b43a9673.png)
All the links in the Info tab on step 2 could also be shown on step 3 with the updated format?

**Comment by danfruehauf** [comment]
I think that's generally an easy thing to implement. Up to @pblain to decide what to do with that though...

**Comment by pblain** [comment]
Looks good.  If Mark wants to make the enhancement we would be happy to accept it.  Otherwise I'll add it to our backlog as a future enhancement.

**Comment by keaves** [comment]
My guess is @markhepburn won't have enough time left for this one. 
Happy for it to be added to the backlog.

**Comment by pblain** [comment]
Added to the backlog
