### ISSUE TITLE
GoGoDuck sending success emails and empty netCDF for aggregations with no data 

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1772]
App version: 4.5.0
            Build date: Fri May 22 14:04:54 AEST 2015
            Build number: 13
            Git ref: 72b9e6b8cbedd3738bc5e2bc21d4df04c529e2e0

Steps to reproduce:
Select any SRS Satellite collection or ACORN collection and add to the map, 

Draw a bounding box outside the extreme ranges of the box ie over land in asia.

Proceed to step 3 and select a netCDF download.

What should happen:

Get a failed job with an email indicating no data found or at least an "internal error"

What does happen:

Get a success email and an empty netCDF file.

**Comment by dnahodil** [comment]
I (by myself or with @kereid) could not reproduce the issue where a success email was sent for a job returning no data.

However, by looking into this issue, I realise that the user feedback for a job failed with no error are not great. I have opened a new issue in the GoGoDuck repository (https://github.com/aodn/go-go-duck/issues/109).
