### ISSUE TITLE
No error symbol for broken layer

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1792]
App version: 4.6.1
            Build date: Wed Jun 10 11:57:32 AEST 2015
            Build number: 15
            Git ref: 1d2478cc16914fdfc8b7ade8abc245331f0e96fe

Steps to reproduce:

Add a collection that does not load

What does happen:

User doesn't really see anything happen.

What should happen:

See red error triangle

**Comment by dnahodil** [comment]
Red error triangle will go in title part of the accordion, on the right next to the close button. (Discussed with @pmbohm @pblain)

**Comment by kereid** [comment]
Re-opening - I still don't see an error triangle

**Comment by kereid** [comment]
Closed because it did come up will open a new ticket because it only showed when i move the map
