### ISSUE TITLE
No loading symbol for collections

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1793]
App version: 4.6.1
            Build date: Wed Jun 10 11:57:32 AEST 2015
            Build number: 15
            Git ref: 1d2478cc16914fdfc8b7ade8abc245331f0e96fe

Steps to reproduce:

Add a collection to the map

What should happen:

User sees a loading symbol so they know it is loading

What does happen:

No loading symbol is seen anywhere

**Comment by dnahodil** [comment]
Loading indicator will go in title part of the accordion, on the right next to the close button. (Discussed with @pmbohm @pblain)
