### ISSUE TITLE
Can no longer easily zoom to geoserver boundaries of collection 

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1798]
App version: 4.6.1
            Build date: Fri Jun 12 18:42:47 AEST 2015
            Build number: 1
            Git ref: 1d2478cc16914fdfc8b7ade8abc245331f0e96fe

Steps to reproduce:
Add any collection to be taken to step 2

What should happen:

On step 2 there should be an option to click a button to zoom to the geographical restrictions of the collection on the map

What does happen:

No option to click a zoom button anywhere

**Comment by dnahodil** [comment]
Zoom to layer button will go in the 'layer' tab within the accordion. (Discussed with @pmbohm @pblain)
