### ISSUE TITLE
Can no longer autozoom

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1799]
App version: 4.6.1
            Build date: Fri Jun 12 18:42:47 AEST 2015
            Build number: 1
            Git ref: 1d2478cc16914fdfc8b7ade8abc245331f0e96fe
        -->

Steps to reproduce:

Add any collection, to be taken to step 2

What should happen:

Past version have either had an autozoom on the map tab or it was on the active layer/collection switcher panel

What does happen:

No autozoom option

**Comment by dnahodil** [comment]
As discussed in the planning meeting this morning, we will not resurrect this feature for now.

**Comment by dnahodil** [comment]
@kereid can you please update testrail so we no longer test this behaviour.
