### ISSUE TITLE
Data collection order mismatch

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#1800]
**Steps to reproduce**
Add a couple of data collections in the Portal
Go to step 2 and observe the data collection ordering in the accordion, the order on the map and the order in the 'overlays' list in the right-hand-side pop-out menu
Go to step 3 and observe order of data collections on this screen

**What does happen**
Order is not consistent.
eg. Order in accordion is reverse of that in the 'overlays' menu

**What should happen**
Order should be consistent throughout

**Comment by pblain** [comment]
Not sure why we need the overlays menu.  It shows the same thing as the accordion and it is sounding like a pain to keep in sync.  Perhaps best to get rid of it.

**Comment by dnahodil** [comment]
Just had a chat with @pblain and we will remove the 'overlays' list from the right-hand side pop-out.

**Comment by dnahodil** [comment]
However, there is still the problem that the accordion order is the opposite of the layer order.
