### ISSUE TITLE
Removing a collection before it has finished loading results in errors

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#1809]
**Steps to reproduce**
Add a collection and then remove it again before it has finished loading

**What should happen**
Collection should be removed

**What does happen**
Many JavaScript errors

**Comment by dnahodil** [comment]
I think this is essentially the same as #563

**Comment by kereid** [comment]
Re-opening as I am seeing today, 

TypeError: J is undefined
	

...,H,K;if(J==document){return null}L=w(L);H=(G=J.style[L])?G:(I=t.getComputedStyle...

**Comment by dnahodil** [comment]
I'm sure everyone believe this is a thing, but just for reference I am getting this symptom on the data_collection_layers branch at the moment:
> TypeError: el is undefined
out = (v = el.style[prop]) ? v :
(ext-all-debug.js (line 2278, col 20))
