### ISSUE TITLE
Pagination controls not frozen in place

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1832]
App version: 4.8.4
            Build date: Tue Jul 07 16:43:25 AEST 2015
            Build number: 4
            Git ref: e1f5e0fbe9254c9fe772e7a216c50048e400d36

Steps to reproduce:

Proceed to step 1 and scroll down

What should happen:

When taken to step one the pagination controls are seen at the bottom of the page and when user scrolls they stay in the same place locked above the bottom bar of the screen

What does happen:

When taken to step one there is no indication of how many results there are or what page the user is on, they have to scroll all the way to the bottom of the results to find out.

**Comment by dnahodil** [comment]
This changes in commit 82df600679c1fb1347258bb94b2d18153436e05b. I don't know whether it was deliberate or not (there was no information in the commit message).

**Comment by dnahodil** [comment]
Closing this as we're not going to call it a bug. Just another instance where changes weren't communicated.
