### ISSUE TITLE
Resetting the users position in the results in Step 1

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1834]
App version: 4.8.4
            Build date: Tue Jul 07 16:43:25 AEST 2015
            Build number: 4
            Git ref: e1f5e0fbe9254c9fe772e7a216c50048e400d363

Steps to reproduce:

Scroll to bottom of results on step one.

Select a facet that will significantly alter the results but still have more than one page of results.

What does happen:

Results are narrowed but user still remains at bottom of page

What should happen:

Results narrowed and user position reset to the top of page 1

As per #464

**Comment by danfruehauf** [comment]
Could witness that only on firefox, seems like it works alright on Chrome.
