### ISSUE TITLE
Broken collection shows loading until map is moved

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1835]
App version: 4.8.4
            Build date: Tue Jul 07 16:43:25 AEST 2015
            Build number: 4
            Git ref: e1f5e0fbe9254c9fe772e7a216c50048e400d363
        -->

Steps to reproduce:

Add IMOS - SRS SATELLITE - OC MODIS - 01 day - Chlorophyll  a concentration algorithm  (OC3) to the map when the satellite collections are down, 

What should happen:

The collection when it does not load should show red error triangle

What does happen

Collection does not show error triangle until the map is moved and then it shows immediately

**Comment by jkburges** [comment]
@kereid: is this only happening when loading the portal with a collection ID in the address (e.g. https://imos.aodn.org.au/imos123/home?uuid=d7a14921-8f3f-4522-9a54-e7d1df969c8a)?

**Comment by kereid** [comment]
@jkburges - no it was happening when I was adding it from the step1 select button,

**Comment by jkburges** [comment]
@pblain this bug is a great example of the kind of behaviour which cannot be tested (easily, and reliably, at least) with production data.

**Comment by kereid** [comment]
@jkburges this collection:
SRS Satellite Contributed Ocean Colour - MODIS -  Aqua Chlorophyll Concentration in the Southern Ocean: Weekly, Johnson et al 2013  is currently broken in production so you can reproduce this issue if you hadn't already.

**Comment by jkburges** [comment]
Yes, I see it, thanks!  I've added some details of various requests/responses here: https://gist.github.com/jkburges/e0144260c289e81d4174

Note that the `getFilters` and `getStyles` requests fail.  I don't think I was simulating this when I originally tried to recreate this bug.

**Comment by pblain** [comment]
@jkburges - Can this be closed?
