### ISSUE TITLE
Free text search layout

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#1836]
## Steps to reproduce
Enable free text search

## What should happen
Buttons align

## What does happen
Buttons are out of alignment (i.e. the "Go" button is hard up against the text field - "Clear button" is off to the right. 

![image](https://cloud.githubusercontent.com/assets/2802359/8640838/9f493ae2-2949-11e5-8476-6b6fda858b20.png)

**Comment by danfruehauf** [comment]
@pblain Can you please post a mock up of how it should actually look?

**Comment by pblain** [comment]
It should lake exactly the same as it does now, but with buttons spaced correctly.  There should be a gap between the text field and the Go button - and the Clear button should not poke out to the right.

**Comment by danfruehauf** [comment]
Timeboxed that as well, my original PR fixes that issue but introduced perhaps another. If anyone wants to look at the Ext layouts - go for it.
