### ISSUE TITLE
Ext 4 JS upgrade notes

### ISSUE THREAD

**Issue by jkburges** [aodn/aodn-portal#1838]
Two approaches:

## Sandbox
https://github.com/aodn/aodn-portal/tree/ext_js_4_sandbox

- run ext 3 and 4 side by side
- incrementally replace v3 components with v4
- issues due to the wrapping of v4 in v3
- all unit tests working

## Compatibility Layer
https://github.com/aodn/aodn-portal/tree/ext_4_upgrade

- run 4 only but with a compatibility layer to 3
- bulk change over of all classes
- various issues due to classes which have disappeared or changed a lot in v4
- unit tests not working at all (this could be just due to something as simple as missing includes but haven't investigated)

**Comment by danfruehauf** [comment]
:+1: for sandbox.
