### ISSUE TITLE
Flash player warnings show when loading Portal

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#1839]
Firefox have recently disabled Flash player by default and since then I have been seeing messages in the Portal showing that Flash player has been blocked. @lbesnard noticed this a little while ago, but we all decided he was probably just crazy.

It would be good to know why these flash messages are appearing (I can't think of where we would be using Flash) and if there's an alternative we can consider now that one of the major browsers is disabling Flash by default [citation needed].

**Steps to reproduce**
Load the Portal in FireFox with Flash player disabled

**What does happen**
Warnings about flash player being disabled

**What should happen**
No warnings
Warm fuzzy feelings inside as you easily find data relevant to your interests and download it in a format convenient to your needs.

**Comment by danfruehauf** [comment]
https://addons.mozilla.org/en-US/firefox/blocked/p946

**Comment by dnahodil** [comment]
See https://github.com/aodn/aodn-portal/blob/182b0ac883c8e8b926cee97a6be95f88ac0c1338/web-app/js/ext-3.3.1/ext-all-debug.js line 36573

**Comment by lbesnard** [comment]
thanks @dnahodil , you're proving I'm not totally insane
