### ISSUE TITLE
Zoomed in screen shows random gridlines on the map

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1846]
App version: 4.8.5
            Build date: Tue Jul 14 12:44:51 AEST 2015
            Build number: 5
            Git ref: a17cfedb990cbae4d4dc6634754c881a4aa6674d
        -->

Not sure how long this has been there as I don't think I've ever zoomed in my screen whilst testing.

Steps to reproduce:

Scroll in on screen by holding ctrl and clicking plus button 3 times
Proceed to portal and add any collection to the map to be taken to step 2.
Change to pan control and move around the map

What should happen:

Map is clear and free of any random gridlines

What does happen:

User sees random gridlines 

![grid1](https://cloud.githubusercontent.com/assets/2906602/8740477/680f35bc-2c8d-11e5-9a0b-c5d9d62ea1db.jpg)

![grid2](https://cloud.githubusercontent.com/assets/2906602/8740481/6ec96f08-2c8d-11e5-801e-0a54b275e735.jpg)

**Comment by pblain** [comment]
@danfruehauf , if this is an openlayers issue (that requires changes to the openlayers code itself) I'm happy for the bug to be closed as "won't fix".

**Comment by danfruehauf** [comment]
@pblain I'm not entirely sure, but it's probably not something that's going to be easy to debug/fix the way I see it.

**Comment by danfruehauf** [comment]
Introduced by OpenLayers 2.13.1 upgrade. I'm still investigating.

**Comment by danfruehauf** [comment]
If we set a gutter for base layers, those artifacts disappear. We need to discuss whether we actually want to do that.

That means we need to re-seed all tiles for the base layers then.

**Comment by danfruehauf** [comment]
Might be related:
http://gis.stackexchange.com/questions/27942/openlayers-vector-layer-and-google-maps-vector-layer-and-google-layers-dont

Either, this was timeboxed, if anyone wants to try and solve it - good luck. I'm very hesitant with having a gutter on the base layer BTW.

**Comment by danfruehauf** [comment]
Fixed by #1872
