### ISSUE TITLE
Feature Request: customise header link(s)

### ISSUE THREAD

**Issue by markhepburn** [aodn/aodn-portal#1847]
The portal has basic branding support, including footer content, header text, and css overrides.

It would be nice if we could also customise the links in the top right corner via the same mechanism.  Our motivation is just to have our own help page, explaining the provenance etc before pointing off to the official manual on aodn.org.au.

(I'm happy to put together a PR some time if you'd look at that)

**Comment by dnahodil** [comment]
Hey @markhepburn,

The links in the top right can be customised, currently. The config just lets you add links, nothing fancier than that, but it sounds like that'll be enough for your needs. Check out https://github.com/aodn/aodn-portal/blob/182b0ac883c8e8b926cee97a6be95f88ac0c1338/grails-app/conf/Config.groovy#L230 (sing out if you need help getting it to work).

Cheers,

**Comment by dnahodil** [comment]
I've just seen that we have removed that customisation (but didn't remove the config entry :angry:)

Maybe try reverting this commit 44895d2eb5c31e53ace27180feb829bf90680ec1 and if that seems to work (and is configurable as you need) you can put up a PR for that.

**Comment by markhepburn** [comment]
Thanks @dnahodil , incoming shortly.

**Comment by dnahodil** [comment]
:+1:

**Comment by dnahodil** [comment]
Works on master, closing
