### ISSUE TITLE
Subset options for active collection not displayed after control click

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1848]
App version: 4.9.0
            Build date: Fri Jul 17 13:45:28 AEST 2015
            Build number: 7
            Git ref: 182b0ac883c8e8b926cee97a6be95f88ac0c1338

Steps to reproduce:

Add 6-9 collections using the control click function from step 1. Proceed to step 2

What should happen:

The scroll bar of the subset tab should be at the bottom so that all filters of the active collection are visible.

What does happen:

The scroll bar stays at the top and then the user has to manually scroll it down to see filters of the active collection

**Comment by dnahodil** [comment]
This also happens if you're just adding collections with normal clicks (it's just a lot slower that way).

**Comment by dnahodil** [comment]
@jonescc This seems (to me) to have been auto-closed incorrectly. Perhaps a typo in the git commit message?

**Comment by danfruehauf** [comment]
Oh, I think he meant #1846

**Comment by pblain** [comment]
Users not likely to notice. Closing.
