### ISSUE TITLE
Geographic boundary usability not ideal

### ISSUE THREAD

**Issue by danfruehauf** [aodn/aodn-portal#1861]
There are a couple of issues with the geographic boundary in my opinion. One of them is that by default it opens in such a way that the `Go` and `Clear` buttons are not visible:
![geographicboundary1](https://cloud.githubusercontent.com/assets/830676/8949267/4734fc58-35f4-11e5-8fd0-74a5a93f64d7.png)

The second can be reproduced by:
 * Adding a collection to the map
 * Going back to step 1
 * Opening the geographic boundary facet
 * After drawing a polygon, users will be tempted to click on the `Next` button:
![geographicboundary2](https://cloud.githubusercontent.com/assets/830676/8949282/925dc1b0-35f4-11e5-9805-72ac6246a349.png)

I think those are usability issues which should be addressed. Mind you, most of our backend effort is to provide a proper spatial index of the data. By having a suboptimal geographic boundary facet we are defeating that purpose a bit.

**Comment by kereid** [comment]
@danfruehauf I agree hence why I had previously opened #1833 but then I closed it as I couldn't work out how to reproduce it every time. Think it only occurs when the Geo facet is opened for the first time in a session/after a hard refresh - ie if user has been active on portal and then selects "start new search" and re-opens geo facet it will default to the bottom of the scroll.

**Comment by danfruehauf** [comment]
@kereid I think either way it's bad, since the `Next` button is orange and bright, while the `Go` button is pretty pale. Users will be encouraged to click on the `Next` button most of the times I think. This at least happened with one of my friends who I introduced the portal to.

**Comment by jkburges** [comment]
> This at least happened with one of my friends who I introduced the portal to.

Is he/she still your friend?

**Comment by danfruehauf** [comment]
@jkburges Insta-unfriended them on every social network ;)

**Comment by danfruehauf** [comment]
@pblain How do you suggest to fix this?

Scrolling it all the way to the bottom can prove tricky (i.e., when do we scroll? What if the geographic boundary is not the last one there?

Second, the buttons are still going to be grey and  unappealing compared to the bright orange/yellow `next` and `prev` buttons.

**Comment by pblain** [comment]
The important thing is that the Go and Clear buttons are visible when the facet is opened.  Somehow it knows to scroll down far enough to show the full map.  I don't know how it does it, but the current response is correct - it just needs to scroll that little bit further to show the buttons.  

The grey button colour is fine.  Orange must be reserved for calls to action.

**Comment by danfruehauf** [comment]
My point is that this is still not ideal:
![portal-spatial-search](https://cloud.githubusercontent.com/assets/830676/9214250/854c5fbe-40de-11e5-94d4-0241664bfb8c.png)

In terms of usability, people might be tempted to click on the `next` button there as well.
