### ISSUE TITLE
Links to eMII and IMOS on header have re-appeared 

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1867]
App version: 4.10.1
            Build date: Tue Aug 04 16:48:25 AEST 2015
            Build number: 9
            Git ref: 2c1784dd1aca6af80585a72c668af0ceb9670ae7
        -->

Steps to reproduce

Load systest, Look at top right of screen

What should happen:

Only see one link - to the help page

What does happen:

See links to eMII page, IMOS page and help page

**Comment by danfruehauf** [comment]
That's configurable now. So not quite a portal bug, if that's the desired result, we can remove those links from there. I guess it is the desired result.

**Comment by danfruehauf** [comment]
BTW, in portal 2 those links are there:
http://portal.aodn.org.au/aodn/

**Comment by kereid** [comment]
So if these being configurable is a new feature should this have been shown at the review on Monday? 

There is an IMOS link in the footer and I'm pretty sure there was a reason behind removing eMII link I can't recall why or why the links were moved to the bottom of the pages ( @pblain might - maybe for tidiness?) 

Portal2 is AODN though, maybe they should be removed from there too @pblain could confirm but doubt it would be on any kind of priority list anyway as it's portal 2..... isn't it different infrastructure anyway?

**Comment by danfruehauf** [comment]
I think we'll just remove them for the time being. @pblain will probably want to remove them too.

There was just work done so we can reconfigure the links (IMAS wanted that), I thought it was desirable to have those IMOS and eMII links there, apparently not, so they'll be removed shortly.

**Comment by pblain** [comment]
@danfruehauf and @kereid. That is correct.  The links should not be at the top.  It is a web convention to put those kinds of links (contact, terms and conditions, etc) at the bottom.
