### ISSUE TITLE
Multi-WMS limitations/assumptions

### ISSUE THREAD

**Issue by jkburges** [aodn/aodn-portal#1869]
Dumping ground for @jkburges' and @dnahodil's notes about limitations and assumptions of the multi-wms implementation.  These may need to be addressed in the future.
- a group of related ncwms layers must all have the same time samples

**Comment by dnahodil** [comment]
It is currently assumed that all the layers are of the same type (ie. GeoServer vs ncWMS)

**Comment by dnahodil** [comment]
It is assumed that GeoServer layer filters are configured such that they will work for any map or data layer which is part of the same DataCollection

**Comment by dnahodil** [comment]
I think at the moment it is assumed that the area covered by the layers is roughly the same. This isn't the case for the example data collection (CARS) as it has both Australia and World-wide layers.

**Comment by jkburges** [comment]
Selecting an accordion folder should bring the associated layer to the top of the map, but it doesn't.

**Comment by dnahodil** [comment]
We should try this with multiple GeoServer layers. I've only been testing with the one example which is multiple ncWMS.

**Comment by dnahodil** [comment]
Decision: the style panel range controls (changes the max/min for the colour scale) and style picker will be **per layer**. As the cited example case of many ncWMS layers effectively means switching layers is switching variables of that dataset, then having a number range stay between those different attributes does not make sense. E.g. the range for a temperature is going to be very different from a range for salinity. Similarly, the palette you'd use to visualise a temperature would be very different to the one you'd use to visualise temperature anomaly data.

**Comment by dnahodil** [comment]
We've gone back to using layer names (in the layer picker) which is something we've managed to avoid in the Portal for a while now. Layer names are cryptic and unhelpful for people who are not ocean scientists. It would be nice if we could have something human-readable.

**Comment by dnahodil** [comment]
It is assumed that layers cover roughly the same geographical area. This is because the geographic bounds are stored in the metadata record which is shared for all layers. If this isn't the case then the 'zoom to layer' button will give odd/incorrect results.

(This was previously in the list but I think I removed it incorrectly)

**Comment by pblain** [comment]
In backlog
