### ISSUE TITLE
Temporal extent on download step not updated after 'clear subset'

### ISSUE THREAD

**Issue by jkburges** [aodn/aodn-portal#1870]
**Steps to reproduce:**
1. Add an ncwms collection, e.g. ACORN
2. Edit the "from date" in the subset panel (to a more recent year than the default, for example)
3. Click 'clear subset'
4. Go to step 3.

**What should happen:**
The temporal extent shown on step 3 should reflect the full extent of the collection.

**What does happen:**
The temporal extent shows what was set in point 2 in the steps to reproduce above.

Note: seems as though this bug was introduced in https://github.com/aodn/aodn-portal/commit/6d13c170cc6e746e (according to `git bisect`).

**Comment by dnahodil** [comment]
My work on this is stalled until I can answer this question: https://www.sencha.com/forum/showthread.php?304418-Is-it-possible-to-make-an-Ext.data.Record-class-which-extends-Observable&p=1112488

**Comment by dnahodil** [comment]
Actually, I found a fix that doesn't require DataCollection to be Observable (re: that link).
