### ISSUE TITLE
Data collection refactoring

### ISSUE THREAD

**Issue by jkburges** [aodn/aodn-portal#1871]
General notes of things that are currently a bit messy and need to be refactored (in order of most to least importance):

1. ~~visibility and life cycle of `DataCollectionLayers`~~
  * ~~`DataCollection.getLayerState()`~~
  * ~~`DataCollection.getSelectedLayer()`~~
  * ~~`DataCollectionLayers` behaving as an OpenLayer~~
1. ~~ref FilterService:20 - hide the fact that filters are retrieved from a single layer in geoserver.  As far as the portal is concerned, it should be modelled as filter per data collection~~
1. ~~Remove usages of bodaacFilterParams (unblocks more refactoring opportunities)~~
1. ~~Search and replace for GeoNetwork -> Metadata (unless it *really* is geonetwork specific code)~~
1. ~~search for `this.layer` - check for using layer instead of DataCollection~~
1. ~~unit tests for DataCollection, DataCollectionStore, DataCollectionLayers~~
1. ~~layer link vs layer record vs open layer vs converted layer link~~
~~e.g. https://github.com/aodn/aodn-portal/pull/1868/files#diff-c77abb48bd68b441f485ece546efd3dcR201~~
  * ~~lifecycle~~
  * ~~representation~~
1. ~~naming SubsetPanel, SubsettingPanel, generally the component which are children of the filtering step~~
1. Portal.cart namespace
1. ~~Move ncWMS params to use filters get/set on DataCollection~~
1. ~~Rename Ncwms, NcWMS -> NcWms~~
1. ~~Change usages of SELECTED_LAYER_CHANGED to DataCollection-held event~~
1. Move DataCollection updateFilters() out of DataCollection - no setFilters(), either
1. ~~DataCollectionStore~~
  * ~~getLoadedRecords(?)~~
  * ~~isRecordActive()~~
  * ~~getRecordForUuid()~~
1. ~~Active record stuff from FacetedSearchResultsDataView~~
1. ~~Rename DATA_COLLECTION_MODIFIED -> DATA_COLLECTION_STATE_CHANGED~~
1. Combine or abolish LayerDescriptor, LayerOptions, and LayerParams

**Comment by dnahodil** [comment]
I'm looking at number 2

**Comment by dnahodil** [comment]
PR #1882 addresses (2)

**Comment by dnahodil** [comment]
All the important refactorings here have been done!

**Comment by jkburges** [comment]
:+1: :+1:
