### ISSUE TITLE
Actions in the Portal not currently tracked by Google Analytics

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#1878]
This is a (possibly incomplete) list of actions in the Portal which are not currently tracked with Google Analytics.

* Change opacity
* Change scale range
* Change style for layer
* Data collection visible/hidden on map
* ncWMS date filtering
* ncWMS data pick which time to see on map
* Remove button (step 3)
* Clear and reset (step 3)

@pblain FYI

**Comment by danfruehauf** [comment]
> This is a (possibly incomplete) list of actions in the Portal which are not currently tracked with Google Analytics.
> 
>     Change opacity
>     Change scale range
>     Change style for layer - #1893
>     Data collection visible/hidden on map - #1893
>     ncWMS date filtering
>     ncWMS data pick which time to see on map
>     Remove button (step 3) - #1893
>     Clear and reset (step 3) - #1893

**Comment by danfruehauf** [comment]
Still left after #1893:
* Change opacity
* Change scale range
* ncWMS date filtering
* ncWMS data pick which time to see on map

**Comment by jkburges** [comment]
How about pan and zoom operations the map, or more interestingly, what areas are people looking at?
