### ISSUE TITLE
Zoom to collection does not work for Australian multi ncWMS

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1889]
Steps to reproduce:

Add a multi ncWMS collection, proceed to layer tab ensure an Australian layer is selected, click zoom to collection.

What should happen:

Map is zoomed closer on Australia

What does happen:

Map zooms to Africa

Note: could possibly be a content issue

**Comment by dnahodil** [comment]
Not sure if it's related but I just spotted some craziness at https://github.com/aodn/aodn-portal/blob/f674a627c63640b190be1529ba8d8ad56f7482df/web-app/js/portal/ui/MapPanel.js#L155.

Specifically:
```javascript
... Math.abs(bounds.top == bounds.bottom) ...
```

**Comment by jkburges** [comment]
This bug no longer appears to be apparent, and I don't *think* it has anything to do with #1939 (or [the fix](https://github.com/aodn/aodn-portal/pull/1941)).

So, just checking in to see if @atkinsn perhaps changed (added) the extent for the multi-ncwms test collection?

**Comment by atkinsn** [comment]
@jkburges yesterday I edited the CARS record for Australian weekly, and created a new record for World monthly. I did edit the geo extent in the Australian record.

**Comment by jkburges** [comment]
Ok, imma close this then, as I think it was a content issue (which has now been fixed). 

Although there's a possibly a usability issue there in that the 'zoom to collection' control should not be enabled/visible *if* the collection does not have a geo extent defined. /cc @pblain

**Comment by pblain** [comment]
Agree.  Not good to have a button that doesn't work

**Comment by jkburges** [comment]
The usability issue is address in https://github.com/aodn/aodn-portal/pull/1945
