### ISSUE TITLE
New Search - Does not clear free text search

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1890]
App version: 4.11.1
            Build date: Wed Aug 19 09:30:45 AEST 2015
            Build number: 11
            Git ref: b1b9fa11ffd1a7919d92149ac76a2743ba8ac74f

Steps to reproduce:
Note the number of default pages - at this stage there are 12
Enter a word in the free text search look at number of pages (this example 3) click New Search
Look at the number of pages of results

What should happen:

Text is cleared from box and results are back to 12 pages

What does happen:

Text types is still there but facet is contracted but there are still only 3 pages of results.

**Comment by danfruehauf** [comment]
Ouch. That was definitely overlooked.
