### ISSUE TITLE
Cannot view all ACORN collections

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1900]
App version: 4.11.1
            Build date: Wed Aug 19 09:30:45 AEST 2015
            Build number: 11
            Git ref: b1b9fa11ffd1a7919d92149ac76a2743ba8ac74f
        -->

This is occurring on Systest but not production which leads me to believe it is a code issue rather  than a content issue maybe ncWMS stuff @dnahodil @jkburges ??

Steps to reproduce:
Narrow results down to ACORN collections byselecting radar from platform.

Add IMOS - ACORN - Rottnest Shelf HF ocean radar site (Western Australia, Australia) - Real-time sea water velocity to the map, go back to step 1 and try to add 
IMOS - ACORN - Turquoise Coast HF ocean radar site (Western Australia, Australia) - Real-time sea water velocity 

Same for adding Bonney coast and SA, or any others that have the same names

What should happen:

They can be added

What does happen:

See select button turns grey see a message that says this collection is already added but there will only be one collection in the active panel yet (assuming it's ncwms) there are no radio buttons on the layer tab to change the layers.

**Comment by dnahodil** [comment]
Could be related to this change: 0deb534b6ef53cd7177938a772be687a72ef5b1d

**Comment by jkburges** [comment]
I am unable to re-create this behaviour on the current master, FWIW. Let me just try on the systest version...

**Comment by dnahodil** [comment]
Try harder

**Comment by jkburges** [comment]
Actually, I can :-)
