### ISSUE TITLE
Portal doesn't fit on a standard sized screen

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#1905]
## Steps to reproduce
1. Open portal using a non-widescreen monitor
2. Go to Step 1

## What should happen
No horizontal scroll bar. Can see everything without it

## What does happen
There is a horizontal scroll bar

![image](https://cloud.githubusercontent.com/assets/2802359/9400792/1dc79584-4809-11e5-8297-c064314631b0.png)

**Comment by dnahodil** [comment]
What resolution are we talking, here?

**Comment by pmbohm** [comment]
@kereid We need to know. Your screen will be the benchmark of what a working professional can endure.
### There are other options:
1. I can go to the tip shop and get you a better screen? (I'll need $10 of petty cash)
2. Sticky tape your two screens together?

See how helpful and resourceful we can be!

**Comment by kereid** [comment]
@pmbohm wasn't me that reported it - looks fine on both of mine lol

**Comment by pmbohm** [comment]
@kereid Sorry I remember you had this issue before, but there are even more disadvantage people here at eMII. !!! the horror !!!
