### ISSUE TITLE
Time filter not applied on step 3 if user does not click out of box

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1922]
App version: 4.11.2
            Build date: Wed Aug 26 10:32:42 AEST 2015
            Build number: 12
            Git ref: 936ebee4b3ed78a0a01ca83121aa7a165427fa56
        -->

Seeing #1581 again

Steps to reproduce
Select Parameter satellite, then select any srs collection to add.

Once on step 2 wait until time filter loads and then click in the from date box

Manually type to change the from date. Click next or download button to proceed to step 3

What should happen:

New from date is applied, to the possible download.

What does happen:

Date is still set at default,

NB if you then go back to step 2 and then forward to step 3 the correct date is then applied.

**Comment by dnahodil** [comment]
Might be related to #1870

**Comment by pmbohm** [comment]
@kereid Today i cant seem to reproduce the bug (on master). Can you?
If you can please let me know which collection you use.

**Comment by kereid** [comment]
@pmbohm just tried it on systest for 
IMOS - SRS SATELLITE - OC MODIS - 01 day - Ocean Colour - SST and could see it

**Comment by pmbohm** [comment]
@kereid Thanks that's it. straight away
