### ISSUE TITLE
Download button still visible when no data available

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1927]
App version: 4.11.2
            Build date: Wed Aug 26 10:32:42 AEST 2015
            Build number: 12
            Git ref: 936ebee4b3ed78a0a01ca83121aa7a165427fa56

Steps to reproduce:

Add any collection and draw a bounding box away from any visible data. ie Argo and then in the middle of the Australian land mass.

Proceed to step 3.

What should happen:

GO to step 3 and only see the grey remove button and the message No data available. (Try changing filters)

What does happen:

Still see Download as button.

Decision was originally made to remove it see #1227

**Comment by danfruehauf** [comment]
So, there's a few ways of fixing that. Simple way:
 * Once the page loads, show the download button
 * If the download estimator returns with 0B of download - hide the button
This will still allow the user to download a collection of 0B if he/she is quick enough

Second option:
 * Hide/disable the download button on page load
 * Once the estimator have finished running, and if there's something to download - unhide/enable the button
This introduces the problem that a user will not be able to download before the estimation is done

@pblain @kereid, suggestions?

**Comment by pblain** [comment]
These options are worse than the bug itself.  Buttons enabling/disabling in front of the user's eyes is not what we want.

I am going to close this.  If a user filters data down to zero (e.g. bounding box outside the spatial extent) and the download estimator displays a zero file size - the user can download the empty file if he/she chooses.  The zero file size warning should be enough. We COULD add a warning if the user chooses to download it - but this is a new feature and we have bigger fish try fry at the moment.
