### ISSUE TITLE
Zoom to collection not working

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1939]
-
            App version: 4.12.1
            Build date: Tue Sep 01 15:30:10 AEST 2015
            Build number: 14
            Git ref: d6c409ad34d5a579c4508c81a0767f7f285fef3e

Steps to reproduce:

Add any collection ACORN, Argo, AATAMS proceed to layer tab and click zoom to collection

What should happen:

Map zooms for closer area of layer (or at least moves around to mid-world for Argo)

What does happen:

Nothing

**Comment by kereid** [comment]
Possibly not unneccesary code @jkburges 
https://github.com/aodn/aodn-portal/pull/1924#issuecomment-134835550

**Comment by dnahodil** [comment]
> @dnahodil said he's willing to take full responsibility for any bugs that may arise from this PR.

Ha ha. Win.

**Comment by jkburges** [comment]
Possible duplicate of #1889.  I'll look at both of these.

**Comment by jkburges** [comment]
It's not due to https://github.com/aodn/aodn-portal/pull/1924#issuecomment-134835550! But rather https://github.com/aodn/aodn-portal/commit/132465f91ea94a2354#diff-7eb247b543df1512b29d7e56f26db01aL61

**Comment by danfruehauf** [comment]
Closed by #1941. Improved by #1945
