### ISSUE TITLE
Spatial Subset not applied on step 3 for ncWMS collections

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1944]
App version: 4.12.1
            Build date: Tue Sep 01 15:30:10 AEST 2015
            Build number: 14
            Git ref: d6c409ad34d5a579c4508c81a0767f7f285fef3e

Steps to reproduce:

Add any ncwms collection such as ACORN or SRS.

Draw a bounding box on step 2 at some part over the collection

Proceed to step 3

What should happen:

See indicaqtion of spatial subset applied to collection and the co-ordinates

What does happen:

Only see default temporal extent that is applied

**Comment by pmbohm** [comment]
After this fix, the spatial constraint is getting lost
#### To Reproduce
1) Add an ncWMS collection
2) Add spatial constraint by drawing bbox
2) Add temporal constraint
3) Go to Step 3
#### What happens 
the spatial constraint is gone

**Comment by danfruehauf** [comment]
I'll try to resolve that again. Must be resolved if we want to release...
