### ISSUE TITLE
Load Data Collection from URL has JavaScript errors

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#1956]
Spotted on master (i.e. not currently on systest) @ 597bfa8f690571ba0fd5aa450eea488ebbebdea6

**Steps to reproduce**
* Try to load a data collection by having the UUID in the URL

**What does happen**
* Errors appear in JavaScript console
* Data collection is not loaded

**What should happen**
* Data collection should load as normal

**Comment by dnahodil** [comment]
Git bisect suggests this commit is the culprit: eb95fc2fdc529c34a8ef1da58afc18ff8b738a52

**Comment by danfruehauf** [comment]
Just tried with:
http://edge.aodn.org.au/imos/home?uuid=4402cb50-e20a-44ee-93e6-4728259250d2

Looks OK. Am I missing something?

**Comment by dnahodil** [comment]
The record I was trying with has been removed from the GeoNetwork instance (I didn't realise). This bug actually only affects invalid UUIDs.

**Comment by pmbohm** [comment]
@dnahodil something i was doing earlier gave me a URL with a hash appended, leading to confusing errors.
EG: http://edge.aodn.org.au/imos/home?uuid=4402cb50-e20a-44ee-93e6-4728259250d2#

Maybe we should be showing a nice msg to users instead of JS errors

**Comment by dnahodil** [comment]
@pmbohm any idea how it got on there? I agree that it's a bug.

**Comment by dnahodil** [comment]
@pmbohm don't answer here. Chuck the details up in #1958
