### ISSUE TITLE
Load Data Collection from URL fails with fragment identifier

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#1958]
Spotted by @pmbohm, see https://github.com/aodn/aodn-portal/issues/1956#issuecomment-138183839

**Steps to reproduce**
* Get a direct-link to a data collection in the Portal. 
* Append the hash symbol to the URL
* Try to load the URL in a browser

**What does happen**
* The data collection isn't loaded
* JS error occur in terminal

**What should happen**
* The data collection should be loaded or the user should get feedback that the uuid is unavailable

Note: It is valid for a URL to have a fragment identifier after a query string, so we should handle it.

**Comment by pmbohm** [comment]
@dnahodil As for what it takes to get yourself a free hash char turning up at the end of the url, dunno yet what i do

**Comment by dnahodil** [comment]
*Hash chars, hash chars, get 'em while they're hot. FREE to the first 100 callers!*

It seems you can get one by middle-clicking on the 1-2-3 tabs. There will be other ways, too.
