### ISSUE TITLE
Satellite collections show layer names in get feature info popup

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1976]
App version: 4.14.0
            Build date: Tue Sep 15 12:12:50 AEST 2015
            Build number: 16
            Git ref: 46c86164f7408e5001457edf483241bad348f0a9

This is also in production

Steps to reproduce

Narrow down results by selecting Satellite from the Platform facets.

Select any collection from the list

On step 2 click any point on the collection display on the map

WEhat should happen:

Tabs show collection name - "human readable"

What does happen:

They show layer name - I think

ie IMOS - OceanCurrent - Gridded sea level anomaly - Near real time shows as surface_geostrophic_sea_water_velocity(NRT)

**Comment by kereid** [comment]
Also the names don't even show up sometimes

![no layer names](https://cloud.githubusercontent.com/assets/2906602/9895094/d1cf297e-5c6e-11e5-9456-eb8bfd570d42.jpg)

**Comment by pmbohm** [comment]
marvl collection has this problem
![screen shot 2015-09-16 at 1 34 18 pm](https://cloud.githubusercontent.com/assets/1066981/9895869/de7cdf5a-5c77-11e5-82c2-ec2eaa0ce721.png)

**Comment by pmbohm** [comment]
As we now have multiple map layers for collections, the 'title' is correctly being pulled from the MEST WMS link information. @atkinsn has informed me that this field (called description in Geonetwork) is often left empty and she will now undertake to populate the description field.
If the title field (in portal code) is left empty then the collection name will now be used as a fall back.
