### ISSUE TITLE
Large gaps in the accordion

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#1985]
## Steps to reproduce
1. Select Aus CPR Zooplankton on Step 1
2. Go back to Step 1 and choose a second data colelction
3. On Step 2 open the Aus CPR Zooplankton

## What happens
There is a large area of white space underneath the "Clear Subset" button and the header of the next accordion panel.
This causes the next data collection to run off the bottom of the screen (unless you scroll down)

## What I expect to happen
The header of the next accordion panel should be close under the "Clear Subset" button.

![image](https://cloud.githubusercontent.com/assets/2802359/9986258/d28bef06-607d-11e5-8827-01bbcb85cba9.png)

**Comment by pmbohm** [comment]
This is a Chrome only bug
