### ISSUE TITLE
New Search doesn't work

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#1986]
## Steps to reproduce
1. Go to Step 1
2. Select a platform
3. Use the text search
4. Click "New Search" at the top

## What I expect to happen
1. Search reset to the initial state

##What does happen:
This:
![image](https://cloud.githubusercontent.com/assets/2802359/9986785/0d9112d8-6084-11e5-9621-9a66dd76115d.png)

**Comment by kereid** [comment]
Duplicate of #1890 which has been resolved but not released into production yet
