### ISSUE TITLE
Zombie accordion panel

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#1987]
Don't know how to reproduce, but I got into a state where AusCPR was selected twice - with one panel working and the other not:
![image](https://cloud.githubusercontent.com/assets/2802359/9986947/a176122c-6085-11e5-8373-e7f0d79ecd24.png)

**Comment by pmbohm** [comment]
no more clues?

**Comment by pmbohm** [comment]
Cant reproduce.
A Note from Kath. Error occurred after collections were deleted

**Comment by dnahodil** [comment]
I haven't been able to reproduce this, either. I'll be happy to look at it again if we get any more information (from @pblain or @ktattersall).
