### ISSUE TITLE
Download Estimator - not completing

### ISSUE THREAD

**Issue by pmbohm** [aodn/aodn-portal#1998]
### Whats Happening (current Master)
On http://portal-edge.aodn.org.au/imos/home?uuid=4402cb50-e20a-44ee-93e6-4728259250d2&health=all the Download Estimator on Step 3 never seems to populate. 
### To reproduce
1. select a small area on Step 2
2. Note the request to ....aodn-portal/download/estimateSizeForLayer is made and returned with a numeric value not an error message or status
3. On Step 3 the estimator status is never shown

**Comment by danfruehauf** [comment]
This is pretty critical. I don't think we'll be able to release without that fixed.

**Comment by danfruehauf** [comment]
And just to clarify - this is a client side bug, the result returns from the server, but never embedded in the right place.

**Comment by kereid** [comment]
Possibly related to #1964?
