### ISSUE TITLE
Select button does not take user to step 2 after ncwms collection added

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1999]
pp version: 4.15.3
            Build date: Tue Sep 29 12:17:44 AEST 2015
            Build number: 20
            Git ref: f5e30b566e43440ba6dc8c5632ae7ee7392ad2b6
        -->

**Steps to reproduce:**

1. Refresh portal
2. proceed to bottom of first page of results and type 12 in the page number box
3. Add the first record "IMOS - SRS SATELLITE - SST L3S - 01 day composite - day and night time composite" (goes to step 2)
4. (Attempt to) add the second record "IMOS - SRS SATELLITE - SST L3S - 03 day composite - day time".

**What should happen:**

Taken to step 2

**What does happen:**

Select button greys - collection is added but user is kept on step 1 like ctrl is being held down.

**Comment by jkburges** [comment]
This is some sort of race condition.  If, after step 3 above, one waits for the layer to be fully loaded (i.e. the text "Loading ..." changes to "Displaying: 2015-09-26 09:20:00:000 UTC", then the problem doesn't occur.

**Comment by jkburges** [comment]
Well done @kereid for finding this, pretty obscure!

**Comment by jkburges** [comment]
I think this bug in fact occurs whenever two ncwms collections are selected within quick succession.  A non-ncwms then ncwms doesn't trigger it.
