### ISSUE TITLE
WPS client/server integration

### ISSUE THREAD

**Issue by jkburges** [aodn/aodn-portal#2003]
Here is a brief list of the remaining work that needs to be done in order to have WPS available as a "Download later" option in the portal.  Noting here since no work has been scheduled for this iteration, and this'll hopefully make it easier to pick up.

Notes:

1. make sure that notification callback is called, even if the initial WPS process fails
1. follow up on https://github.com/aodn/geoserver-build/issues/45
1. follow up on https://github.com/aodn/geoserver-build/issues/46
1. revert 9a4bb98d916a0c51a (to re-enable the option to "Download later" in the client).

**Comment by jkburges** [comment]
@julian1 can you please provide comment on whether or not it's possible (or within the WPS spec in fact) to send a typeName as "namespace:typeName", e.g. "imos:argo_profile_data", instead of separately, in the WPS request?  This would simplify the portal code.

**Comment by jonescc** [comment]
There's nothing in the WPS, WMS or WFS specs about namespace and typename - this is a Geoserver implementation detail.

In the WMS spec there is just a layer name it is not broken down into namespace/layer  - same with feature type.  So its more correct not to separate them.

**Comment by jonescc** [comment]
Or should I say more compatible with other WMS/WFS implementations

**Comment by jonescc** [comment]
WPS you can do whatever you want.

**Comment by jkburges** [comment]
Thanks for the info @jonescc.  I'm pretty sure I tested a request as such, and it failed - but this needs to be confirmed by whoever picks this up again.

**Comment by julian1** [comment]
@jkburges can definitely change - not sure why i didn't do it that way - since i'm aware of the convention.

**Comment by pmbohm** [comment]
@jkburges constructed these for testing:

*  Config.groovy will need editing to allow `geoserver-systest` or change the URL's to match
*  sendMail in WpsService.groovy may need commenting out and replacing with a call  like `println groovyPageRenderer.render(template: .........`

### Create a job:
```
curl "http://localhost:8080/aodn-portal/asyncDownload?aggregatorService=wps&jobParameters.namespace=imos&jobParameters.typeName=anmn_ts_timeseries_data&jobParameters.cqlFilter=INTERSECTS(geom%2CPOLYGON((113.33%20-34.09%2C113.33%20-30.98%2C131.11%20-30.98%2C131.11%20-34.09%2C113.33%20-34.09)))%20AND%20TIME%20%26gt%3B%3D%20%272009-01-13T23%3A00%3A00Z%27%20AND%20TIME%20%26lt%3B%3D%20%272009-02-01T00%3A00%3A00Z%27&server=http://geoserver-systest.aodn.org.au/geoserver/wps&email.to=[ YOUR EMAIL ADDRESS ]"​
```


### Job complete:
```
curl "http://localhost:8080/aodn-portal/wps/jobComplete?server=http%3A%2F%2Fgeoserver-systest.aodn.org.au%2Fgeoserver%2Fows&uuid=f3f5068f-0c7d-46d9-8bcb-d153deef929e&email.to=[ YOUR EMAIL ADDRESS ]"
```

**Comment by jkburges** [comment]
Closing, in favour of post-it notes.

[![post-it notes](http://img.youtube.com/vi/Y1rZqw5bXb4/3.jpg)](http://www.youtube.com/watch?v=Y1rZqw5bXb4)
