### ISSUE TITLE
Python/Unsubsetted nedtcdf only downloads a small amount of requested data 

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2013]
App version: 4.14.0
            Build date: Tue Sep 15 12:12:50 AEST 2015
            Build number: 16
            Git ref: 46c86164f7408e5001457edf483241bad348f0a9
        -->
Reported by Jason Everett

**Steps to reproduce:**

1. Add IMOS - SOOP-Temperate Merchant Vessel (TMV) sub-facility - Data collected on the Spirit of Tasmania I during transect between Melbourne and Devonport (Delayed mode) to the map
2. On Step 2, select from date as 01/01/2008 and end day as 1/10/2015.  
3. On Step 3, download as unsubsetted netcdf or python

**What should happen:**

Get downloads with all years for all forms of data

**What does happen:**

Get downloads with random years within selected time-frame but not all of the years data requested

**Comment by jkburges** [comment]
For the python download, what's happening is that the `maxFeatures` row limit (of 1,000,000 rows) is being hit in geoserver.  The "randomness" is because there is no sorting on the results, so the rows are returned in whatever order the DB returns them in.

Not sure about unsubsetted NetCDF (BODAAC) - there are only ~1400 files so would've thought that all data would be returned for this.

**Comment by dnahodil** [comment]
IIRC we uniqueify the results in the Portal, so only the first 1,000,000 would be returned and the unique values from them will be far fewer.

**Comment by jkburges** [comment]
It looks as if all the netcdf files are there anyway:

```
unzip -l IMOS_-_SOOP-Temperate_Merchant_Vessel_\(TMV\)_sub-facility_-_Data_collected_on_the_Spirit_of_Tasmania_I_during_transect_between_Melbourne_and_Devonport_\(Delayed_mode\)._source_files.zip | tail -n +4 | head -n -3 | cut -d' ' -f10 | sort
```

gives [this result](https://gist.github.com/jkburges/783232f3a414f86be0a7).

**Comment by jkburges** [comment]
Ok, just to clarify a couple of things here after some further investigation:

* the data in the database ranges from "2008-08-28 10:18:48+00" to "2013-01-07 19:40:20+00", and includes ~5 million rows
* python (and CSV) downloads - the results *are* sorted but only the first 1,000,000 rows are returned
* List of URLs (BODAAC) *is* returning all of the results (about 1400 netcdf files), but they are *not* sorted, so it may appear to be random

So, I think we can possibly do a couple of things here to improve the user experience:

1. (Somehow) let users know when the row limit has been reached, or increase the limit.
2. Sort BODAAC results.

Thoughts @pblain?

**Comment by dnahodil** [comment]
Ref https://github.com/aodn/aodn-portal/issues/1140

**Comment by dnahodil** [comment]
I think we could pretty easily update the download estimator widget to also let people know that their downloads will be limited at 1million rows

**Comment by dnahodil** [comment]
As per planning meeting, we're not fixing this yet.
