### ISSUE TITLE
Updating the portal help look and feel

### ISSUE THREAD

**Issue by ggalibert** [aodn/aodn-portal#2020]
Would that be possible to revamp the look (at least background color and font color/style for links) of the help page? The orange font for links over the fair yellow background is hard to read. Colors/style could be consistent with the ones used in the portal itself for example.
![portal](https://cloud.githubusercontent.com/assets/3498686/10298741/e1bfd698-6c2d-11e5-9f5d-530d2ece069c.png)
![portal_help](https://cloud.githubusercontent.com/assets/3498686/10298742/e1c23c58-6c2d-11e5-92db-2427d343cb6b.png)

**Comment by pmbohm** [comment]
+1 :{)

**Comment by jachope** [comment]
So in building the site we have used one of the contributed themes - without going to trouble (requiring a developer to assist in getting other theme modules), we can very easily change both the base colour and the link colour (not change fonts, built into the theme).  However, the colour was originally selected in line with the orange of the 'Get Ocean Data' button!! 
We can change the links to a standard blue?

**Comment by pmbohm** [comment]
There has not been an edit or new page on the http://intranet.emii.org.au site for 1 Year and 24 weeks. 
Its time to kill it as it contains many out of date pages. Github is the new intranet
