### ISSUE TITLE
Online resource title is just a line on the info panel

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2028]
App version: 4.16.1
            Build date: Tue Oct 13 14:49:06 AEDT 2015
            Build number: 23
            Git ref: 152a05741ae9815e67080afa3b47dbc875c9d8aa

Steps to reproduce:

Add any collection, when taken to step 2 click on the info tab and scroll to see the additional links.

What should happen:

There is a title of "Online resources" for the link to the metadata record and then a secone title under for Supplementary Records

What does happen:

There is a weird half line that fades out where it should say "Online Resources"

**Comment by pmbohm** [comment]
This is what I see. Was this a particular collection?
![screen shot 2015-10-27 at 12 21 52 pm](https://cloud.githubusercontent.com/assets/1066981/10747075/5c827250-7ca5-11e5-9f84-c0ae774b571c.png)

**Comment by dnahodil** [comment]
I wonder if this is another case of us not communicating changes with Kate. In this case we've removed a title from above the metadata record link which she (and maybe her test scripts) expected to be there.

**Comment by pmbohm** [comment]
Yes this was discussed. The pull request that changed things, #1974 dosen't mention some keywords that @kereid may use to search history. The physical outcome of the changes aren't mentioned in comments, only the name of the branch gives any information. My bad.
