### ISSUE TITLE
Moorings indicate symbol "Phytoplankton Location"

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2033]
App version: 4.16.1
            Build date: Tue Oct 13 14:49:06 AEDT 2015
            Build number: 23
            Git ref: 152a05741ae9815e67080afa3b47dbc875c9d8aa

Steps to repoduce:

Add any of the following collections

IMOS - Australian National Mooring Network (ANMN) Facility - Current velocity time-series
IMOS - Australian National Mooring Network (ANMN) Facility - WQM and CTD burst averaged data products
IMOS - SRS Satellite Altimetry Calibration and Validation Sub-Facility
IMOS - ANMN National Reference Stations - Maria and North Stradbroke Islands - Near real-time meteorology and sea surface temperature
IMOS - ANMN National Reference Stations - Maria and North Stradbroke Islands - Near real-time water quality
IMOS - ABOS Southern Ocean Flux Station (SOFS) - Surface properties (delayed mode)
IMOS - ANMN National Reference Stations - Maria and North Stradbroke Islands - Near real-time wave height
 
On step 2 look at the layer tab

What should happen:

Symbol has a label indicating location of mooring or that it is a mooring?

What does happen:

They all say Phytoplankton location

@mhidas perhaps you can comment on this one too?

**Comment by dnahodil** [comment]
I've moved this to a content issue so the POs can check it out.
See: https://github.com/aodn/content/issues/143

**Comment by pmbohm** [comment]
Demonstrated to be a content issue. Duplicate internal id's in two SLD files
