### ISSUE TITLE
Bounding box not applied to summary statistics collection

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2034]
App version: 4.16.1
            Build date: Tue Oct 13 14:49:06 AEDT 2015
            Build number: 23
            Git ref: 152a05741ae9815e67080afa3b47dbc875c9d8aa
Steps to reproduce:

Add IMOS - AATAMS Facility - Satellite Relay Tagging Program - Summary statistics.
Draw a bounding box over some data on step 2
Proceed to step 3

What should happen:
Bounding box applied 

What does happen:
Step 3 indicates "full collection will be downloaded consider filtering the collection"

**Comment by dnahodil** [comment]
This data collection does not have a geometry filter configured so we cannot apply a bounding box for it. However, I think the collection is probably configured correctly (because it's summary data), which would mean it's not a content issue.

We can look at this and see if there's a nice way to improve this situation in the Portal.

**Comment by pmbohm** [comment]
`IMOS - AATAMS Facility - Satellite Relay Tagging Program - Summary statistics` has now been deleted and `IMOS - AATAMS Facility - Satellite Relay Tagging Program - Delayed mode data` now encompasses `Summary statistics`
This new layer has content issues described at https://github.com/aodn/content/issues/145

This issue should remain open until it is detirmined that the configuration described above by @dnahodil should never occur

**Comment by pblain** [comment]
We can't accept data collections without a geometry filter because the spatial subset is above the accordion. The new monitor should be extended to identify configuration errors.

**Comment by dnahodil** [comment]
In discussion with @pblain the decision is to leave the Portal behaviour as it currently is. Things won't break if you don't have a geometry filter configured for a data collection but the Portal will not do anything different to try to explain why a data collection won't use the global geometry filter you set.
