### ISSUE TITLE
Bounding box not applied to latest ncwms collection added.

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2035]
App version: 4.16.1
            Build date: Tue Oct 13 14:49:06 AEDT 2015
            Build number: 23
            Git ref: 152a05741ae9815e67080afa3b47dbc875c9d8aa

Steps to reproduce:
Add any collection
Draw a bounding box on step 2
Go back to step 1 and select an ncwms collection to add (SRS or ACORN)
Proceed to step 3

What should happen:

See spatial extent applied

What does happen:

Spatail extent is not applied

**Comment by pmbohm** [comment]
#1944 does not quite go far enough as the geometryFilter information is not available to new collections added.
