### ISSUE TITLE
Incorrect geographical bounding box display in metadata record display of Step1

### ISSUE THREAD

**Issue by rogerproctor** [aodn/aodn-portal#2048]
Data bounding boxes do not display correctly. e.g. none of the satellite bboxes are complete; sst satellite data, from the metadata record spans 70°E to 170°W, 20°N to 70°S but this is not shown in the image with the metadata record, e.g. L3S 1-day composites, which cuts off eastern Australia and the Tasman Sea to NZ; Johnson southern ocean chl covers 0-360 degrees but not in the image. Others too, e.g. SOOP XBT which spans the Pacific and down to Antarctica is likewise limited.

**Comment by pblain** [comment]
The fix for this seems to cause some minimaps to zoom in too far:

![image](https://cloud.githubusercontent.com/assets/2802359/11578293/1b7c4f9c-9a78-11e5-97e3-d7461b9f8b2e.png)

![image](https://cloud.githubusercontent.com/assets/2802359/11578303/41bd947c-9a78-11e5-85de-517e6a3ede53.png)

**Comment by pmbohm** [comment]
Additional fix to limit zoom level

https://github.com/aodn/aodn-portal/commit/c5e2841640bbd8cefdc103584a59f5afed3ede44
