### ISSUE TITLE
switching layers on and off in step 2

### ISSUE THREAD

**Issue by rogerproctor** [aodn/aodn-portal#2051]
Now we have the accordion the location of the button to switch layers on and off in step 2 is on the 'layer' tab as 'shown on map'. This makes hard work for the user to switch layers on and off. As a user I want this option to be more visible, and preferably on the title bar next to, or under, the 'X'. Also the wording 'shown on map' is not intuitive, the wording should be 'enable/disable layer'.

**Comment by pmbohm** [comment]
@rogerproctor @pblain Is this something that is wanted? There is a fix that was done and its getting stale.
https://github.com/aodn/aodn-portal/pull/2090

**Comment by pblain** [comment]
@pmbohm - this will be among the features that we consider for next FY.  Keep the branch but don't worry about rebasing.  I'll let you know what we decide following the JPSR planning meetings in the coming months.

**Comment by pblain** [comment]
Closing for now
