### ISSUE TITLE
GoGoDuck download fails with incorrect time values

### ISSUE THREAD

**Issue by rogerproctor** [aodn/aodn-portal#2052]
Selecting a single time for start finish returns an error ... see log below

```
The list of URLs obtained was empty, were your subseting parameters OK?
The collection name was 'srs_sst_l3s_1d_day_gridded_url'
The subset parameters were 'TIME,2015-11-01T03:20:00.000Z,2015-11-01T03:20:00.000999Z;LATITUDE,-90.0,90.0;LONGITUDE,-180.0,180.0'
```

**Comment by danfruehauf** [comment]
The SRS files are "packed" (`ncpdq`), the result file is not packed, hence the size difference.

**Comment by dnahodil** [comment]
The first you raised certainly is an issue. You can see the problem in the subset parameters:
```
... TIME,2015-11-01T03:20:00.000Z,2015-11-01T03:20:00.000999Z; ...
                                                      ^^^^^^
```
We'll need to track down where it is coming from, though.

**Comment by danfruehauf** [comment]
Either way, best if this bug is split into 2:
1. GGD (or general WFS?) downloads cannot give data for a specific date time
2. GGD doesn't pack files

**Comment by dnahodil** [comment]
See https://github.com/aodn/go-go-duck/issues/113 regarding the size discrepancy.

**Comment by dnahodil** [comment]
Turns out that the crazy date munging isn't actually causing the issue. Although we will need to fix that anyway as it is incorrect and might be causing bugs we don't know about.

**Comment by dnahodil** [comment]
Given that we need to support a few flavours of ncWMS we probably need to keep this munging code in, but ensure that it works for both formats we expect (with and without the milliseconds component).

**Comment by dnahodil** [comment]
Ok, the problem is actually a content problem (see https://github.com/aodn/content/issues/149). Loz is going to look into that. Also, it seems that the munging code (as it is currently) is actually still fine so I won't make any changes there.
