### ISSUE TITLE
Newly added link does not show in info panel

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2054]
Steps to reproduce:

Add a new link in distribution of a metadata record with the following protocol WWW:DOWNLOAD-1.0-ftp--download @atkinsn can explain further if required.

What should happen:

Link shows up in info panel of record on portal

What does happen:

Nothing.

For further information see @atkinsn comment at the end of #1974 re external AODN contributors.

**Comment by pmbohm** [comment]
Re @atkinsn comment: 
I'm in favour of adding 'WWW:DOWNLOAD-1.0-ftp--download' protocols to step 2. We should encourage external AODN contributors to use a defined set of protocols that make sense to show as a link in step 2. Its just another step of their configuration providoers need to conform too.

In other words if a link dosen't show, its a contributors problem and if we show links that don't make sense, its our problem.

**Comment by pmbohm** [comment]
Fixed by https://github.com/aodn/aodn-portal/commit/be68b4f8e2e6a9ebdecd8d2cb6662c0d909e8622
