### ISSUE TITLE
Depth service sometimes can return no value

### ISSUE THREAD

**Issue by pmbohm** [aodn/aodn-portal#2057]
## To reproduce
http://localhost:8080/aodn-portal/depth?lat=-9.09765625&lon=48.251953125 or
https://imos.aodn.org.au/imos123/depth?lat=-9.09765625&lon=48.251953125

## What happens
No depth value is returned
```
<root>
    <latitude>-9.09765625</latitude>
    <longitude>48.251953125</longitude>
    <depth></depth>
</root>
```
## What should happen
Always the geographically closest value is returned

**Comment by dnahodil** [comment]
I think the Portal should also handle this situation gracefully.

**Comment by pmbohm** [comment]
Fixed by https://github.com/aodn/chef/pull/207
