### ISSUE TITLE
Section of map highlighted when drawing a polygon on Step 1 in Chrome

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2077]
App version: 4.18.0
            Build date: Wed Nov 25 09:51:20 AEDT 2015
            Build number: 28
            Git ref: 442355c1318504dba3e272fcdd4c9064e0a6d383

Steps to reproduce:
Open geographic facet on step 1, draw a polygon anywhere of 3-4 points, double click to end drawing

What should happen:

Polygon is drawn on map 

What does happen:

Polygon is drawn and when user double clicks a blue highlighted square appears over the west of Australia

**Comment by kereid** [comment]
Also seeing this on step 2.

Add a collection, draw a polygon go back to step 1 add another collection and draw another polygon.

**Comment by kereid** [comment]
Or if you have 2 collections on the map, draw a polygon, then select the non-active collection to become active

**Comment by pmbohm** [comment]
#2091 Is related. A control is created for drawing which is sitting over the up pan arrow. Question is what/why?
