### ISSUE TITLE
Link in WPS Error Email points to localhost not the geoserver instance running the wps request

### ISSUE THREAD

**Issue by jonescc** [aodn/aodn-portal#2087]
Problem identified on portal-systest:

# To reproduce

Go to acorn rottnest delayed mode collection
Proceed to download without specifying any subset parameters
Select Netcdf, enter an email address and confirm.

# What happens

I get an email with a valid link to the job status page of the geoserver instance

# What does happen

I get an email with a job status page link at localhost:8080

**Comment by danfruehauf** [comment]
@jonescc Reformatted your ticket, so it has proper headers.
