### ISSUE TITLE
No indication of what the error was on WPS job status page when error occurs

### ISSUE THREAD

**Issue by jonescc** [aodn/aodn-portal#2088]
Tested on portal-systest

# To reproduce

Run an unconstrained acorn subset
Go to job status page and refresh until job has finished

# What happens

Get a decsriptive message saying that an error occurred but nothing about why - e.g. max files exceeded

# What I expect to happen 

Get some information as to what happened

**Comment by pmbohm** [comment]
I think its a need to know basis. That is, the user should never see some obtuse message intended for devops. If we can be sure its *too many files exceeded* then by all means that probably has value to show it

**Comment by kereid** [comment]
Changing this issue to Bug rather than enhancement, as Gogoduck used to provide the above mentioned information by Craig such as too many files, time limit exceeded etc and therefore this new WPS should do the same.
