### ISSUE TITLE
Drawing a Bounding box too small opens GFI

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2093]
<!--
            App version: 4.19.1
            Build date: Mon Dec 07 11:58:17 AEDT 2015
            Build number: 30
            Git ref: 5786b4ec3fa6c72810ffa3fa5577032adaf4eb43

Steps to reproduce:

Draw a bounding box that is too small (will be red)

What does happen:
The bounding box draws red then disappears and the GFI opens

What should happen:
The bounding box draws red then disappears 

Related to #2064 ?

**Comment by pblain** [comment]
This is the correct behaviour.  A single click opens the GFI box.  A single click IS a small bounding box.

**Comment by pblain** [comment]
... we can dispense with the red effect though
