### ISSUE TITLE
No queue numbers for gogoduck wps

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2097]
```
 App version: 4.19.2
        Build date: Fri Dec 18 15:56:45 AEDT 2015
        Build number: 31
        Git ref: 93adc9b7627059e2fc0dba037e319ff29797f1e8
```

Steps to reproduce:

Add MOS - ACORN - Rottnest Shelf HF ocean radar site (Western Australia, Australia) - Real-time sea water velocity to the map.

Proceed to step 3 and select download NetCDF when popup opens close it and again click on download netCDF and then when popup opens click link to status page. (may need to subset to a smaller size if download fails immediately because to big - to get the downlaod to take enough time to get the second one to be waiting in the queue)

What should happen:

Second collection download status page indicates in queue and the position

What does happen:

Both just say preparing download

**Comment by danfruehauf** [comment]
I had a feeling this was going to come ;)

**Comment by pblain** [comment]
This is now referenced in the backlog and will come in planning at some stage.  Please leave it until then.

**Comment by pblain** [comment]
Closing because it's now replicated in the backlog
