### ISSUE TITLE
Bounding box button disappears when hovered over

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2098]
App version: 4.19.2
            Build date: Fri Dec 18 15:56:45 AEDT 2015
            Build number: 31
            Git ref: 93adc9b7627059e2fc0dba037e319ff29797f1e8

This is showing in production - but not systest....

Steps to reproduce:

Add any collection to the map to be taken to step 2

Hover over the bounding box button on the left of the map

What should happen:

Just see the button and it doesn't change.

What does happen:

It disappears but is still clickable - ie if you first change to pan control then hover over the button and click it will change back to bounding box function.

**Comment by pmbohm** [comment]
@kereid I cant reproduce this. Could you try again and maybe get a screen shot as well please?

**Comment by kereid** [comment]
Hmmm very strange I cannot reproduce it either - Seb saw it too so I didn't make it up but I will close this issue and if I see it again I'll re-open
