### ISSUE TITLE
All links to metadata should point to whole MCP record 

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2099]
Not sure if this is something we can change or if it is a Geonetwork issue
Based on 2 users contacting @atkinsn on missing components today

Steps to reproduce:
1. On step one click "more" link for any collection 

2. Add any collection to the map.
On step 2 go to the info tab.
Scroll to Point of truth URL of this metadata record and click

3. Add any collection to the map.
Proceed to step 3 and click "view metadata record"

What should happen:

User taken to Geonetwork and see whole record (MCP All to test MCP is highlighted)

What does happen:

User taken to Geonetwork and only see default view in which record is abbreviated

**Comment by jonescc** [comment]
The default record view is a GeoNetwork system configuration setting so @atkinsn can currently change this.  @anguss00 this is something we also probably need to be able to manage
