### ISSUE TITLE
Logo is not being resized

### ISSUE THREAD

**Issue by danfruehauf** [aodn/aodn-portal#2107]
```
            App version: 4.20.0
            Build date: Fri Jan 15 13:56:56 AEDT 2016
            Build number: 34
            Git ref: 70deb34dac1b27b7185854ec8051e379acdd6311
```

Happened on systest:
![logosizing](https://cloud.githubusercontent.com/assets/830676/12344537/565cf45a-bb92-11e5-9624-c5ad15395bdd.png)

**Comment by danfruehauf** [comment]
I am going to perform a restore of geonetwork on systest, which will probably pull in a good size logo, but this problem should still be addressed - the logos should be resized before they are embedded in our search results HTML.

**Comment by pmbohm** [comment]
there is a `max-height` attribute of 80px in the code! 
todo: make this backwards compatible

**Comment by danfruehauf** [comment]
I'm on Firefox 42.0. Probably not the latest, but also happened to @jonescc. So I guess this can be considered as a bug.

**Comment by pmbohm** [comment]
This will be absorbed into the new pull request for the AODN landing page

**Comment by pmbohm** [comment]
no it wont!
