### ISSUE TITLE
Logos should not be included in this repository

### ISSUE THREAD

**Issue by danfruehauf** [aodn/aodn-portal#2108]
Some logos included in this repository can be found at https://github.com/aodn/aodn-portal/tree/master/web-app/images

Ideally anything that's branded related should be sourced as an external resource. For us we have static.emii.org.au, so for instance I don't see why we should have things like the AODN logo for example in this repository.

Somewhat related to the work at #2100

**Comment by pmbohm** [comment]
Logos are now on static.emii.org.au. They will be utilised on the new AODN home page when it is released
