### ISSUE TITLE
No logo for AODN DSTO collection

### ISSUE THREAD

**Issue by anguss00** [aodn/aodn-portal#2118]
`App version: 4.21.2
Build date: Tue Feb 02 13:48:17 AEDT 2016
Build number: 38
Git ref: 9062f9a7b7ab66d5f95995ccdb3de2d104534885`

portal-systest.aodn.org.au

Steps to reproduce:
Go to page 9 on systest, consider the layer Defence Science and Technology Organisation (DSTO) - delayed mode glider deployments
Observed behaviour:
Empty logo is displayed, with the geonetwork default "logo" image
Expected behaviour:
A logo is displayed, either IMOS default or DSTO logo.

**Comment by kereid** [comment]
@anguss00 you just pipped me there, I have also mentioned this collection in #2119  it definitely shouldn't have the IMOS default logo as it is not an IMOS collection so should have either the DSTO logo or the logo of wherever it is harvested from - however in saying that it is a static collection at the moment so would need manual configuration as mentioned in #2119

**Comment by pblain** [comment]
This will be redesigned
