### ISSUE TITLE
Non- harvested non-IMOS collections should not have IMOS logo - should be manually configurable

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2119]
App version: 4.21.2
            Build date: Tue Feb 02 13:48:17 AEDT 2016
            Build number: 38
            Git ref: 9062f9a7b7ab66d5f95995ccdb3de2d104534885

Steps to reproduce:
Find non-IMOS collections such as:

Southern Ocean Continuous Zooplankton Record
Satellite tracking of Emperor penguin fledglings

Defence Science and Technology Organisation (DSTO) - delayed mode glider deployents

Royal Australian Navy (RAN) - CTD Profiles

IMAS Shearwater

IMAS Johnson Sattellite collections x4

CARS 2009 - CSIRO

Sat Tag of female Hawksbill Turtle - Charles Darwin University

What should happen:

These all have the appropriate organisation logo.

What does happen:

They all have IMOS logo (except for DSTO ahich @anguss00 mentioned in #2118 )

Confirmed with @atkinsn that this is due to these records being static at the moment and so defaulting to the IMOS logo however this needs to be changed to manual configuration as some organisations may not be ready to produce MCP 2.0 compliant metadata for AODN portal use.  

Also confirmed with @xhoenner the organisation for the Hawksbill record should display the Charles Darwin University logo which @atkinsn will try to source.

**Comment by xhoenner** [comment]
> Satellite tracking of Emperor penguin fledglings

My understanding was that the tags for this data collection had been funded by IMOS, isn't it the case @jachope ?

**Comment by atkinsn** [comment]
This record will eventually come in via an AAD harvest, so will have a AAD logo. This is irrespective of whether IMOS has had a contribution or something.

**Comment by pblain** [comment]
@pmbohm , can you please (temporarily) hide the logos?  @kereid , please stop testing until this is done and released to systest.  This is a VIT.

**Comment by kereid** [comment]
Charles Darwin University Logo has been obtained and is located in Sheryl > Project Office > Artwork > AODN Logos > Charles Darwin Logo when required. 

Email with approval request is also saved in the above mentioned folder, please consult in regards to requirements on correct logo usage.

Charles Darwin University must approve material before release to ensure compliance (see email for further information).

**Comment by jachope** [comment]
Yes Xavier - but I think now it is back to the drawing board to look at how best this can be achieved given it may not be as straight forward as a logo per GeoNetwork.

**Comment by pblain** [comment]
This will be redesigned
