### ISSUE TITLE
Go and Reset buttons on Geo Search break when search is reset on step 3

### ISSUE THREAD

**Issue by anguss00** [aodn/aodn-portal#2121]
App version: 4.21.3
Build date: Thu Feb 04 10:50:42 AEDT 2016
Build number: 39
Git ref: b26063cfbe935f3b68381f0002bb5a2762089497

Portal-systest

Steps to reproduce:
Select a geographic filter on step 1, click go, select a data collection, move to step 3. Click clear and reset and move to step 1. Click on the geo filter.

Observed behaviour:
The Go and Clear buttons are missing.

Expected behaviour:
The buttons should be in the filter.

**Comment by pmbohm** [comment]
@anguss00 Sorry i didnt see that you had your head on this as well
