### ISSUE TITLE
Gogoduck is not sending notification emails

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2122]
Note: This worked the last time I tested in December but that release was not made until early January.

It is occurring on both production and sys-test

Steps to reproduce:

Add any ncWMS collection ie Satellite or ACORN subset if desired proceed to step 3 and select download as netCDF

What should happen:

Get notification email that job has commenced and then one for if it succeeded or failed.

What  does happen:

No emails come through

**Comment by danfruehauf** [comment]
https://github.com/aodn/go-go-duck/commit/d84ca94110c19ea25bbcae0c48ff204db390b54d

**Comment by kereid** [comment]
@danfruehauf or @pmbohm do you recall why it was turned off?

**Comment by pmbohm** [comment]
@danfruehauf It seems that chef is now configuring mail, but the `grails.mail.disabled = true` line in go-go-duck config.groovy should be set for the development environment only?

**Comment by danfruehauf** [comment]
@pmbohm Yeah, do it via chef. It's here:
https://github.com/aodn/chef/pull/254
