### ISSUE TITLE
Collection modified for wps and ncwms-abonimation do not show in the facet counts or results

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2124]
App version: 4.21.3
            Build date: Thu Feb 04 10:50:42 AEDT 2016
            Build number: 39
            Git ref: b26063cfbe935f3b68381f0002bb5a2762089497

Steps to reproduce:

Once collections have been set up (as this has to occur each time) 
a) Look at results for Rottnest Delayed and Real time collections, look at facet count of Radar and then click that facet.
b) refresh and repeat for ANMN Current Velocity Time Series

What should happen:

a) collections are in results list, radar facet count is 10 and when click see Rottnest collections in narrowed results.

b) collections are in results list, Mooring and buoy facet count is 22 and when click see ANMN Current Velocity Time Series in narrowed results.

What does happen:

a) see Rottnest in first results list but facet count is 8 and Rottnest does not appear in narrowed results

b) see ANMN Current Velocity Time Series in first results list but mooring and buoy facet count only shows 21 and when clicked ANMN Current Velocity Time Series is not in narrowed results.

**Comment by jonescc** [comment]
My bad.

This was caused by me bringing back an MCP 2.0 draft record from production and modifying it to include WPS links.

It needs to have the mcp 2.0 draft to mcp2.0 final xsl run against it. 

I'll redo the changes

**Comment by jonescc** [comment]
XSL run against imported records in systest.  The above records are now showing as expected.  Note that the count for moorings nd buoys for me in systest is 21 now not 22.  

"IMOS - ANMN National Reference Stations - Darwin and Yongala - Near real-time meteorology and oceanographical data" is not showing in systest - due to a link checker failure.
