### ISSUE TITLE
OceanCurrent collections always on bad list

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2126]
App version: 4.21.5
            Build date: Tue Feb 16 11:46:01 AEDT 2016
            Build number: 41
            Git ref: cf0e67855d506c0cd8b721f6323f9a0fca973071
        -->

Steps to reproduce:

Go to http://portal-systest.aodn.org.au/imos123/home

Look for OceanCurrent in keyword search,

Go to http://portal-systest.aodn.org.au/imos123/home?health=bad

Go to http://portal-systest.aodn.org.au/imos123/home?health=all

Find OceanCurrent collection and add to map

What should happen:

Should be fixed if on bad list (work in prod)

What does happen:

Always on bad list and don't load when found on all list 

This was seen the last iteration but I just thought it might have been they were bad at harvest time into catalogue systest and they would be rectified as they are fine in production but thought as they haven't improved with the release today I should log as an issue just in case it's something else

**Comment by danfruehauf** [comment]
You need a new copy of geonetwork DB as those records were modified to use the abomination ncwms protocol. ncwms.aodn.org.au does not serve anything now except for CARS.

Running restore now on systest so it should be fixed.
