### ISSUE TITLE
Facets not showing

### ISSUE THREAD

**Issue by danfruehauf** [aodn/aodn-portal#2127]
Facets not showing in portal systest. Geonetwork response looks legit. See:
http://portal-systest.aodn.org.au/imos123/proxy?url=http%3A%2F%2Fcatalogue-systest.aodn.org.au%2Fgeonetwork%2Fsrv%2Feng%2Fxml.search.imos%3Fprotocol%3DOGC%253AWMS-1.1.1-http-get-map%2520or%2520OGC%253AWMS-1.3.0-http-get-map%2520or%2520IMOS%253ANCWMS--proto%26sortBy%3Dpopularity%26from%3D1%26to%3D10%26fast%3Dindex%26filters%3Dcollectionavailability&_dc=1455668534197

Happened after geonetwork restore on 16/02/2016.

**Comment by jonescc** [comment]
<dimension value="Measured parameter" count="0"/>means no parameter facets.

Systest has mcp 2.0 mods in it.  I'm assuming prod still using mcp2.0 draft so backup/restore will break systest - needs @julian1 s mcp2.0 draft to mcp2.0 final transformation to be run.

**Comment by danfruehauf** [comment]
@julian1 Can you please run it? It's sort of blocking @kereid from testing.

**Comment by anguss00** [comment]
Should we be releasing mcp 2.0 final to prod? It's gone through one round of testing

**Comment by jonescc** [comment]
That's what Kate tested with last iteration

**Comment by danfruehauf** [comment]
I wasn't aware of that when I did the restore. Probably should have left it untouched.

**Comment by jonescc** [comment]
A restore also wipes out WPS test data - until we actually configure that in production that is.

**Comment by julian1** [comment]
Is this resolved? I suggest raising a vit.

**Comment by julian1** [comment]
Ok, portal-systest is fixed.

**Comment by kereid** [comment]
As discussed in planning this should have been closed it was resolved.
