### ISSUE TITLE
Online resource monitor failed to pick up geoserver outage

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#2128]
There was an outage that affected all geoserver backed data collections: https://github.com/aodn/internal-discussions/issues/193
The affected data collections still appeared in the portal during the outage.
The online resource monitor in GN should have detected the unresponsive services and hidden them from view in the portal

**Comment by jonescc** [comment]
@pblain, in prod the link checker is configured as follows:

max_failure_rate = 0.4
max_checks = 10
fixed_delay_seconds = 600

So for a previously available service it will take 5 failing checks or more than 50 minutes before the failing service triggers disabling of the layer.  Most of the layers didn't get checked 5 times before geoserver was restored for that outage.

**Comment by jonescc** [comment]
Working as designed and configured.

**Comment by danfruehauf** [comment]
:+1: Really happy it's not some corner use case with the link monitor.

**Comment by pblain** [comment]
Yeah that's good.  We can look at tuning the config if we get more problems.  It's been OK so far.
