### ISSUE TITLE
ANMN netcdfoutput wps collection does not have all filters

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2129]
App version: 4.21.5
            Build date: Tue Feb 16 11:46:01 AEDT 2016
            Build number: 41
            Git ref: cf0e67855d506c0cd8b721f6323f9a0fca973071

Steps to reproduce:

Add IMOS - ANMN National Reference Stations - Darwin and Yongala - Near real-time meteorology and oceanographical data to the map, look at filters.

What should happen:

Long name, platform name and variable name all have values in the drop down.

What does happen:

Only Long name and Variable name have options in drop down list
Platform states - "No Options available"

Related to #2080 ?

**Comment by pmbohm** [comment]
Choppy response from Geoserver for the `anmn_nrs_dar_yon_timeseries_data` layer and then this:
![screen shot 2016-03-01 at 4 58 51 pm](https://cloud.githubusercontent.com/assets/1066981/13419008/0e8e9ae6-dfcf-11e5-8f3b-4ea86ca77c96.png)
