### ISSUE TITLE
How to config email

### ISSUE THREAD

**Issue by fxmzb123** [aodn/aodn-portal#2131]
In step3, the GoGoDuck service will email the user when the wps request has been finished.
How to config the portal to send emails?

Thanks,
Ming

**Comment by pmbohm** [comment]
Do you have `grails.mail.disabled = true` set somewhere?
Do you have a mail program installed on the server ? `/usr/bin/mail` ?

**Comment by danfruehauf** [comment]
@fxmzb123 Since you're not using our chef code, you have this problem. See:
https://github.com/aodn/chef/blob/master/cookbooks/imos_webapps/templates/default/portal/Portal.groovy.erb#L136
