### ISSUE TITLE
ncDownloadService does not perform subsetting correctly

### ISSUE THREAD

**Issue by smancini** [aodn/aodn-portal#2134]
Issue found in portal-systest

App version: 4.21.5
Build date: Tue Feb 16 11:46:01 AEDT 2016
Build number: 41
Git ref: cf0e67855d506c0cd8b721f6323f9a0fca973071

### Steps to reproduce:

Select the following dataset collection:
IMOS - Australian National Mooring Network (ANMN) Facility - Temperature and salinity time-series
http://portal-systest.aodn.org.au/imos123/home?uuid=7e13b5f3-4a70-4e31-9e95-335efa491c5c
Apply the following subset:
Spatial Subset: 151.344W -33.972S 151.411E -33.917N
Temporal Extent: 2013/Mar/09-00:00-UTC to 2013/Apr/20-23:59-UTC 

On step 3, select the "NetCDF" download option.

### What should happen:

By selecting the "NetCDF" download option, I should get 1 netCDF file per instrument and deployment with data only for the selected period.

### What does happen:

I get 1 netCDF file per instrument and deployment but with data for the entire deployment.
The NcDownloadService did not perform subset on the time dimension.

In my example, there are two deployments for the mooring and the period I am interested in.
The first deployment start from 05/01/2013 and finish on the 27/03/2013.
The second deployment start from the 22/03/2013 and finish on the 05/07/2013.
The output files will contain either data from January to March or April to July depending on the deployment while I was expecting data for the period March-April.

**Comment by jonescc** [comment]
Currently filtering on time_coverage_start and time_coverage_end rather than on "TIME" resulting in all data in the files with the right time coverage being returned.
