### ISSUE TITLE
Links in download pop-up open in same tab

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2147]
App version: 4.22.0
            Build date: Fri Mar 11 17:46:50 AEDT 2016
            Build number: 44
            Git ref: 0ce4df52e9f247afc34ebf97a4486f12353720e6

Steps to reproduce:

Add a collection such as AATAMS or ACORN and proceed to step 3
Click download (any format as always get the popup)

Click the links in the pop-up.

What should happen:

Links open in a new tab

What does happen:

Links open in the same tab and any subsetting and collection selecting is lost and user must re-do all before they can download.

**Comment by anguss00** [comment]
I'll work on this
