### ISSUE TITLE
thredds S3 cache cannot be configured for size

### ISSUE THREAD

**Issue by danfruehauf** [aodn/aodn-portal#2151]
When dealing with thredds to cache S3 files, currently the only "configurable" values are:
 * EHCACHE_MAX_OBJECTS
 * EHCACHE_TTL
 * EHCACHE_TTI

See:
https://github.com/aodn/thredds/blob/s3_datasets_stable/cdm/src/main/java/thredds/crawlabledataset/CrawlableDatasetAmazonS3.java#L24

It is probably desired to have control of the total size of the objects in the cache as they can vary in size. For instance - a maximum of 4GB of cache allocated for S3 cache, with cache eviction happening when it is being exceeded (or before).

**Comment by pblain** [comment]
Moved to backlog
