### ISSUE TITLE
Cannot change the Colour scheme of a Satellite collection

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2155]
App version: 4.22.1
            Build date: Thu Mar 17 11:32:41 AEDT 2016
            Build number: 45
            Git ref: e4226d3eb99a6ea6ed28cb92c95bca91afaa37a5

Steps to reproduce:

On Step 1 select a data collection that will have options to change eg - SRS SST GHRSST or OceanCurrent gridded collection.

From "create a subset" select the Layer tab

Click the arrow next to "select a style" to open the drop down list

Select a style from the list

What should happen:

There is a drop down list

What does happen:

There is no drop down list

**Comment by danfruehauf** [comment]
Color schemes defined in:
https://github.com/aodn/chef-private/blob/master/external_templates/templates/default/thredds/wmsConfig.xml.erb#L91

I'm not sure what was possible before, but that's a result of using thredds to display the files.

**Comment by bhasin85** [comment]
Confirmed with Kate that it is not happening anymore in the test environment.  It was possibly linked to the re-indexing issue.
