### ISSUE TITLE
GFI reads unkown units for temperature

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2156]
App version: 4.22.1
            Build date: Thu Mar 17 11:32:41 AEDT 2016
            Build number: 45
            Git ref: e4226d3eb99a6ea6ed28cb92c95bca91afaa37a5
        -->

Steps to reproduce:

Add any temperature collection ie IMOS - SRS SATELLITE - SST L3S - 03 day composite - day time
Once collection is laoded on step 2 click any point on the collection

What does happen:
GFI opens and see Value at Thu, 31 Dec 2015 03:20:00 GMT 297.92636 (unknown units) 

What should happen:

GFI opens and see Value at Thu, 31 Dec 2015 03:20:00 GMT 297.92636kelvin (19.85 celcius)

Could have been the other way around where it had kelvin in parenthesis can't remember now that I can't see it

**Comment by bhasin85** [comment]
Issue Fixed. Pull request created.

**Comment by kereid** [comment]
Reopening as pull request was not merged and is now stale

**Comment by pmbohm** [comment]
fixed by https://github.com/aodn/aodn-portal/pull/2166

**Comment by pmbohm** [comment]
#2166 Incorrectly used the layer.units (http://dev.openlayers.org/docs/files/OpenLayers/Layer-js.html#OpenLayers.Layer.units) as a fall back when metadata units are missing.

**Comment by jonescc** [comment]
Fixed by https://github.com/aodn/geoserver-build/pull/138 and https://github.com/aodn/aodn-portal/pull/2225
