### ISSUE TITLE
Full Argo collection too big for Download Size Estimator

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2158]
App version: 4.22.1
            Build date: Thu Mar 17 11:32:41 AEDT 2016
            Build number: 45
            Git ref: e4226d3eb99a6ea6ed28cb92c95bca91afaa37a5

Steps to reproduce:

Add argo to the map

Proceed to step 3

What does happen:

Estimator for full collection never seems to complete.

What should happen:

Estimator completes in a reasonable time

If you go back to step 2 and draw a bounding box and go back to step 3 it will complete an estimate almost immediately.

**Comment by pblain** [comment]
Logged here: https://github.com/aodn/backlog/issues/26
