### ISSUE TITLE
GFI download times out

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2161]
Not sure where this should be:

This issue https://github.com/aodn/content/issues/191 was opened in content last week and @atkinsn fixed what she could and Dan had a geoserver pull request which I believe got activated but no the link which is to https://data.aodn.org.au.s3-website-ap-southeast-2.amazonaws.com/IMOS/SRS/OC/BODBAW/2003_cruise-MV062003/pigment/IMOS_SRS-OC-BODBAW_X_20030618T054500Z_MV062003-pigment_END-20030624T025100Z.nc just times out.

Steps to reproduce:

Add Srs bio-optical database and open GFI, click Download deployment as CSV

What should happen:

Deployment downloaded as cvs

What does happen:

 Page times out.

**Comment by pmbohm** [comment]
This is content. The download link for CSV is broken: 
`
https://data.aodn.org.au.s3-website-ap-southeast-2.amazonaws.com/IMOS/SRS/OC/BODBAW/2000_cruise-NB062000/pigment/IMOS_SRS-OC-BODBAW_X_20000601T030200Z_NB062000-pigment_END-20000609T010200Z.nc`

Either the link should point to `data.aodn.org.au` or `amazonaws.com`
