### ISSUE TITLE
Download popup missing links

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2162]
App version: 4.22.1
            Build date: Thu Mar 17 11:32:41 AEDT 2016
            Build number: 45
            Git ref: e4226d3eb99a6ea6ed28cb92c95bca91afaa37a5

Steps to reproduce:

ADd any collection and proceed to step 3 click on download of any format and pop should open

What should/used to happen:

Download popup had this phrase with links

Any questions?

Please visit the **Download a Dataset** (link) page of the **Portal Help** (link) forum where you can find more information. 

What does happen:

With rework of popup these have gone

**Comment by pblain** [comment]
The text is correct as per the specification provided to Mark.
