### ISSUE TITLE
GoGoduck not working in Systest

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2163]
App version: 4.22.1
            Build date: Thu Mar 17 11:32:41 AEDT 2016
            Build number: 45
            Git ref: e4226d3eb99a6ea6ed28cb92c95bca91afaa37a5
        -->

Steps to reproduce:

Add any ACORN collection on step 1, on step 2 subset to only one day proceed to step 3 and select download as netCDF

What should happen:

netCDF downloads successfully (it does for same collection in production)

What does happen 

Download fails with error:
Failed downloading: 'http://imos-data.aodn.org.au/IMOS/ACORN/gridded_1h-avg-current-map_non-QC/TURQ/2016/03/30/IMOS_ACORN_V_20160330T050000Z_TURQ_FV00_1-hour-avg.nc'
Failed downloading URLs

**Comment by anguss00** [comment]
Issue closed as is working in systest as of 4/04/2016
