### ISSUE TITLE
GogoDuck error not descriptive enough

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2168]
App version: 4.21.5
            Build date: Tue Feb 16 11:46:01 AEDT 2016
            Build number: 41
            Git ref: cf0e67855d506c0cd8b721f6323f9a0fca973071

Background: User reported he could not get download to work - had subsetted out of data bounds but didn't realise.

Steps to reproduce:

Add any SRS satellite collection

Draw bounding box away from data ie over land up north

Proceed to step 3 and select downlaod as netCDF - click link in popup to go to status page refresh until job attempt complete.

What should happen:

Message indicates - no data to download

What does happen:

Message states "Internal error running GoGoDuck, please refer to report for more information"

Report reads:

Aggregation will use only the following variables for srs: 'time,lat,lon,dt_analysis,l2p_flags,quality_level,satellite_zenith_angle,sea_surface_temperature,sses_bias,sses_count,sses_standard_deviation,sst_dtime,wind_speed,wind_speed_dtime_from_sst', any other variable will be omitted!!
Applying subset 'TIME,2001-06-26T15:20:00.000Z,2001-06-26T15:20:00.000999Z;LATITUDE,28.0,33.0;LONGITUDE,113.0,116.0'
Processing file '20010626152000-ABOM-L3S_GHRSST-SSTskin-AVHRR_D-1d_night.nc'

**Comment by kereid** [comment]
Along lines of #2088

**Comment by pblain** [comment]
@kereid  - Sounds like a (pretty valid) feature request.  Added to the backlog here: https://github.com/aodn/backlog/issues/310
