### ISSUE TITLE
Collections that are bad are not being moved onto the bad list

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2169]
App version: 4.21.5
            Build date: Tue Feb 16 11:46:01 AEDT 2016
            Build number: 41
            Git ref: cf0e67855d506c0cd8b721f6323f9a0fca973071
        -->

Steps to reproduce:

Add any satellite collection, taken to step 2

What does happen:

See the red error triangle next to the collection name and collection does not load.

What should happen:

Collection was not listed on step one as it should already be moved to the "bad list"

**Comment by bhasin85** [comment]
It looks like the issue was related to the "No disk space left on 1-aws #207". Unable to reproduce it.

**Comment by jonescc** [comment]
@kereid - see https://github.com/aodn/aodn-portal/issues/2128

It can take over 50 minutes for a failing layer to be removed with the current settings.
