### ISSUE TITLE
Satellite collections are not working

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2170]
App version: 4.21.5
            Build date: Tue Feb 16 11:46:01 AEDT 2016
            Build number: 41
            Git ref: cf0e67855d506c0cd8b721f6323f9a0fca973071
        -->

Steps to reproduce:

Add any satellite collection 

What should happen:

It loads on step 2

What does happen:

Visualisation does not load up and see red error triangle an error in firebug of "NetworkError: 500 Internal Server Error - https://imos.aodn.org.au/imos123/layer/getFilters?serverType=ncwms&server=http%3A%2F%2Fgeoserver-123.aodn.org.au%2Fgeoserver%2Fncwms&layer=srs_oc_chl_oc3_1d_aqua_url%2Fchl_oc3&_dc=1460075289139"

**Comment by bhasin85** [comment]
It looks like the issue was related to the "No disk space left on 1-aws #207". Unable to reproduce it.
