### ISSUE TITLE
GoGODuck failing for one day of data 

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2173]
App version: 4.22.2
            Build date: Thu Apr 07 11:04:40 AEST 2016
            Build number: 46
            Git ref: ec41ac9ef05b51213b900b7371ea4ddc26aab146

Reported by a user - checked with @smancini and can't tell why it is failing because data is in database and on thredds.

Steps to reproduce:

Add IMOS - SRS Satellite - SST L3S - 01 day composite - night time to the map subset on time for 9 April 2016 (start and end date) and co-ordinates LATITUDE,-11.0,-9.0;LONGITUDE,146.5,151.5 

Proceed to step 3 and download as netCDF

What should happen:

Download proceeds successfully

What does happen

Download fails but can't tell why

**Comment by kereid** [comment]
User had another failure yesterday https://gogoduck.aodn.org.au/gogoduck/job/6ac75582 but i tried this morning and it worked, also tried the one above and it worked so can't help if whoever works on this comes to ask me to reproduce it.

**Comment by kereid** [comment]
User seeing failing downloads again today Hi Kate

I just tried these three downloads, but without success
(9d7bbaf2 is one)

Spatial Subset: 112W -26.7S 115E -20.7N
Temporal Extent: 2016/Apr/18-15:20-UTC to 2016/Apr/18-15:20-UTC

Spatial Subset: 112W -26.7S 115E -20.7N
Temporal Extent: 2016/Apr/19-15:20-UTC to 2016/Apr/19-15:20-UTC

Spatial Subset: 112W -26.7S 115E -20.7N
Temporal Extent: 2016/Apr/20-15:20-UTC to 2016/Apr/20-15:20-UTC

Am I doing something wrong?

**Comment by pmbohm** [comment]
@lbesnard  Help!!

The files for download are not complete?
http://imos-data.aodn.org.au/IMOS/SRS/SST/ghrsst/L3S-1d/ngt/2016/20160418152000-ABOM-L3S_GHRSST-SSTskin-AVHRR_D-1d_night.nc
"variable name or regular expression wind_speed is not in and/or does not match contents of input file"

**Comment by mhidas** [comment]
OPENDAP link for that file: 
http://thredds.aodn.org.au/thredds/dodsC/IMOS/SRS/SST/ghrsst/L3S-1d/ngt/2016/20160418152000-ABOM-L3S_GHRSST-SSTskin-AVHRR_D-1d_night.nc.html

**Comment by lbesnard** [comment]
@pmbohm unfortunately, as you spoted, the variable wind_speed doesn't exist. It's been a problem we've had with SST data and gogoduck aggregation which requires all the variable to exist. The best fix for now is to remove the wind_speed variable from the list of gogoduck variables. 

@pblain, unfortunately I don't have privileges to push a branch on the gogoduck repo to fix this

**Comment by lbesnard** [comment]
anyway, this line needs to be moidified
https://github.com/aodn/go-go-duck/blob/master/web-app/resources/worker/profiles/srs#L16

**Comment by pblain** [comment]
@lbesnard - You now have access

**Comment by lbesnard** [comment]
cheers, PR https://github.com/aodn/go-go-duck/pull/120

**Comment by kereid** [comment]
@lbesnard does this mean the files coming in are different to what they were previously? Just trying to work out why we hadn't encountered the problem before now?

**Comment by lbesnard** [comment]
some 2016 files don't have all the variables. It's not really that they are different from before. As maybe it will come back later this year. I'll have to ask Edward why though.

**Comment by kereid** [comment]
Ok right thanks

**Comment by anguss00** [comment]
Fixed by https://github.com/aodn/go-go-duck/pull/120
