### ISSUE TITLE
Amazon S3 data server - CSV file response is incorrect

### ISSUE THREAD

**Issue by pmbohm** [aodn/aodn-portal#2174]
## What happens
When links to CSV files are requested from data.aodn.org.au the browser is treating them as plain text and opening them in the browser. The link below is an example from the [SRS Bio-Optical Database collection](https://imos.aodn.org.au/imos123/home?uuid=97b9fe73-ee44-437f-b2ae-5b8613f81042) in portal
http://data.aodn.org.au/IMOS/SRS/OC/BODBAW/2003_cruise-MV062003/absorption/IMOS_SRS-OC-BODBAW_X_20030618T054500Z_MV062003-absorption-non-algal-detritus_END-20030624T025100Z.csv

## What should happen 
CSV files from http://imos-data.s3-website-ap-southeast-2.amazonaws.com (data.aodn.org.au) should download

**Comment by pmbohm** [comment]
Same thing for the matlab reader file from acoustic.aodn.org.au
http://imos-data.s3-website-ap-southeast-2.amazonaws.com/IMOS/ANMN/Acoustic/code/NL_load_logger_data_new.m

**Comment by julian1** [comment]
The mime type is a metadata property of the s3 bucket object and is (initially) set on s3 upload. I can't find any option within the aws console to configure mime defaults at upload based on the key suffix.

I believe data-services scripts use s3cmd. 

The s3cmd configuration here https://github.com/aodn/chef/blob/master/cookbooks/imos_core/templates/default/s3cfg.erb and sets the following options, 
```
default_mime_type = binary/octet-stream
guess_mime_type = True
```
There appear to be a few issues around these combinations, see https://github.com/s3tools/s3cmd/issues/198. 

Possible fixes?

  - See if it is possible to get s3cmd to read /etc/mime.types and apply a default mime setting based on the file-extension

  - change data-services s3cmd call points and set the mime type explicitly by using `--mime-type` in accordance with the file extension.

  - override mime type using the rev-proxy or portal? disadvantage doesn't fix at source.

**Comment by julian1** [comment]
s3 upload looks like it works through the s3_put() and then s3_put_no_index_keep_file() 

```
# moves file to s3 bucket, keep original file
# $1 - file to move
# $2 - path on s3 (relative)
s3_put_no_index_keep_file() {
    local src=$1; shift
    local object_name=$1; shift
    local dst=$S3_BUCKET/$object_name
    test -f $src || file_error "Not a regular file"
    log_info "Moving '$src' -> '$dst'"
    $S3CMD --no-preserve sync $src $dst || file_error "Could not push to S3 '$src' -> '$dst'"
}
export -f s3_put_no_index_keep_file
```

which is copy-pasted without modification across all of data-services,

 

lol
```
meteo@debian:~/imos/data-services$ md5sum $( grep -Rl    'export \-f s3_put_no_index_keep'   )
grep: SOOP/SOOP_TRV/env: No such file or directory
grep: FAIMMS/REALTIME/env: No such file or directory
grep: AATAMS/AATAMS_sattag_dm/env: No such file or directory
grep: ANMN/NRS_AIMS/REALTIME/env: No such file or directory
grep: AUV/auv_viewer_campaign_processing/env: No such file or directory
8129b50f81a4c291e44194348d7d5394  ACORN/ACORN_data_aggregation/lib/common/s3.sh
8129b50f81a4c291e44194348d7d5394  lib/common/s3.sh
8129b50f81a4c291e44194348d7d5394  SOOP/SOOP_TRV/lib/common/s3.sh
8129b50f81a4c291e44194348d7d5394  SOOP/SOOP_aggregation_dataset/lib/common/s3.sh
8129b50f81a4c291e44194348d7d5394  FAIMMS/REALTIME/lib/common/s3.sh
8129b50f81a4c291e44194348d7d5394  AATAMS/AATAMS_sattag_dm/lib/common/s3.sh
8129b50f81a4c291e44194348d7d5394  SRS/SRS_OC_BODBAW/lib/common/s3.sh
8129b50f81a4c291e44194348d7d5394  ANMN/NRS_AIMS/REALTIME/lib/common/s3.sh
8129b50f81a4c291e44194348d7d5394  AUV/auv_viewer_campaign_processing/lib/common/s3.sh

```

**Comment by julian1** [comment]
Upload replicate 
```
root@10-aws-syd:~$ cp IMOS_SRS-OC-BODBAW_X_20030618T054500Z_MV062003-absorption-non-algal-detritus_END-20030624T025100Z.csv /mnt/ebs/incoming/SRS/OC/BODBAW/
root@10-aws-syd:~$ ls /mnt/ebs/incoming/SRS/OC/BODBAW/
root@10-aws-syd:~$ 
```

**Comment by julian1** [comment]
https://github.com/aodn/data-services/pull/431

**Comment by pmbohm** [comment]
@pblain What about this?
http://imos-data.s3-website-ap-southeast-2.amazonaws.com/IMOS/ANMN/Acoustic/code/NL_load_logger_data_new.m

@mhidas Can you re-upload this file so that the mime type is correct

**Comment by mhidas** [comment]
@pmbohm I have re-uploaded it, but I don't see any change in behaviour when you click on the link.

**Comment by julian1** [comment]
Err, there will be no change in behavior so long as the code is not merged and deployed. 

In addition, someone needs to specify what mime type to use for matlab files.

**Comment by pblain** [comment]
Just catching up on things. I'm going to close this issue. We can live with it for now.  But feel free to merge the work done so far  (assuming it's in a mergable state).
