### ISSUE TITLE
Geoserver layer extent information is not up to date

### ISSUE THREAD

**Issue by pmbohm** [aodn/aodn-portal#2176]
## What happens
GetCapabilities requests  show incorrect extent information.
The spatial extent information is not reflecting the current state of the data This is by design as calculating could take "a lot of IO and take a lot of time" and the desired extent information may not be the current data at this precise moment.
https://groups.google.com/a/opengeo.org/forum/#!topic/js/PiGPWH0wg5k

## What should happen
GetCapabilities requests should show accurate information

## Possible Solution
Explore using the Geoserver REST API ?

**Comment by pblain** [comment]
Please add backlog
