### ISSUE TITLE
RLS Collections cannot be found with parameter or platform facet

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2178]
App version: 4.22.2
            Build date: Thu Apr 07 11:04:40 AEST 2016
            Build number: 46
            Git ref: ec41ac9ef05b51213b900b7371ea4ddc26aab146

Steps to reproduce:
1. On Step 1 search for RLS by using parameter > Biological > Ocean Biota > Abundance of Biota
Or: 
2. Search in Platform > Biological Platform > Diver

What should happen:

1. RLS records appear in results list 

2. Diver platform available to select 

What does happen:

1. No RLS records in results list

2. Diver is not in platform list

Metadata checked and both parameter and platform are present.

**Comment by jonescc** [comment]
Resolved in preprod.aodn.org.au by upgrading IMAS mcp 2.0 draft records to mcp 2.0 almost final
