### ISSUE TITLE
Inconsistent display of RLS records in results lists

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2179]
App version: 4.22.2
            Build date: Thu Apr 07 11:04:40 AEST 2016
            Build number: 46
            Git ref: ec41ac9ef05b51213b900b7371ea4ddc26aab146

Steps to reproduce:

Proceed to end of results list (page 11) 
Look at parameter of record
Open keyword facet and type rls
Look at parameter of record

What should happen:
Results found for RLS show Ocean Biota as parameter

What does happen:

No facet selection result has Ocean Biota parameter

Keyword search has "No Parameters"

**Comment by pmbohm** [comment]
@anguss00 @bhasin85 This is being fixed by IMAS schema transforms right?

**Comment by anguss00** [comment]
Yep that's right @pmbohm. I think this issue can be closed when the transforms have been finished

**Comment by jonescc** [comment]
IMAS schema transforms have been applied.  4 RLS records now have Ocean Biota as a parameter now.  However, one doesn't.  This record doesn't appear to have valid parameter information recorded in the metadata record.   @anguss00 and @julian1 - can you confirm the IMAS schema transform worked correctly for this record and that parameter information was not present before the transformation.

**Comment by jonescc** [comment]
UUID of record is 4972fa20-195b-41e4-bee8-8175d6ac792b

**Comment by julian1** [comment]
not sure about that uuid, but we did notice some records with missing parameter fields/urls.

before.txt and after.txt are still on the VMs so it should be possible to confirm

**Comment by atkinsn** [comment]
So when @smancini and I did the audit of IMAS collections for suitability for harvest, we identified that we didn't want to bring one of the RLS records across into the AODN Portal - the record in question above as it only describes survey sites and isn't an access point to data (and therefore isn't marked up with parameters - so they haven't gone missing!). So please amend the RLS harvest all the records with WMS except this one.
