### ISSUE TITLE
CAPTCHA box caches previously entered text in field

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2180]
@pmbohm noted this should not occur (but it's always been this way so I'm not sure if it's worth worrying about)

Steps to reproduce:

Add an acorn collection and subset to one day and draw bounding box over half map diplay otherwise gogoduck will clog up.

Proceed to step 3 and select download as netCDF. Repeat 3 times on the third try CAPTCHA box will open enter CAPTCHA figures, attempt to download for a 4th time.

What should happen:

CAPTCHA box opens but no text is retained from last entry

What does happen:

CAPTCHA box opens and last text entered is retained so user must delete

**Comment by pmbohm** [comment]
It will be an easy fix in `Portal.cart.DownloadChallengePanel`
