### ISSUE TITLE
Download estimator never completes

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2182]
App version: 4.22.4
            Build date: Thu Apr 21 13:42:48 AEST 2016
            Build number: 48
            Git ref: ec011c0d7bd9dd87df9589e1691e28eb6c777b6f

I know there is a backlog item regarding the download estimator, and that my last bug #2158  logged regarding it was closed due to backlog item but i am opening this as a record that I reported it, as i don't think that while something is in the works to be improved that is should actually be left to not work at all...

Steps to reproduce:

Add argo collection on step 2 draw a small bounding box and select oxygen as true. Proceed to step 3 and watch download estimator.

What should happen:
Gives an estimate (still true in production)

What does happen:
Just keeps spinning

**Comment by kereid** [comment]
Also if it is trying to complete and the user has selected an area where there is no data the estimator still shows as spinning but the download button disappears (which it should if no data) but could be confusing to users as though there might still be some data and they need to wait

**Comment by pmbohm** [comment]
@anguss00 What fix closed this?

**Comment by anguss00** [comment]
it was https://github.com/aodn/aodn-portal/pull/2184 @pmbohm
