### ISSUE TITLE
Rationalize portal configuration

### ISSUE THREAD

**Issue by pmbohm** [aodn/aodn-portal#2196]
### What happens now
The portal currently gets its theme configuration from the internal `Config.groovy` and is overridden by the Chef created `Portal.groovy`. The location of the created `Portal.groovy` is set by a tomcat environment variable https://github.com/aodn/aodn-portal/blob/f6e8e2f99067170dd1dc7e5add7a5c23f9f92a42/README.md

Portal JS code references config variables using the built grailsApplication object eg: `grailsApplication.config.portal.logo` 
Hovever there is another mechanism to access config via `portalBranding.logo` which offers defaults if variables are not set. There is no guarantee the defaults are valid

### The problem
1. There is a mix and match approach to accessing values:
  * `grailsApplication.config.portal.logo` or 
  * `portalBranding.logo`
2. Programmers are unaware of the different methods
3. Two methods are unnecessary and confusing
4. PortalBranding.groovy contains default values that are not reliable
5. Portal code also references `portalBranding.brandingBase` which is (sometimes?) set  by Chef and the requirement is not understood by Portal programmers.

### What should happen
1. Remove PortalBranding.groovy to simplify code for programmers and for administrators of Portal instances
2. Config.groovy should contain the minimum to create a generic unbranded portal
3. Portal.groovy should contain AODN config and be private for AODN usage for both development and deployment. 
4. Facility could be made to pull in local resources (images and CSS)

**Comment by pblain** [comment]
Moved to backlog
