### ISSUE TITLE
Browser Compatability message does not show on home page

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2200]
Steps to reproduce:

Open preproduction on internet explorer - which we do not support

What should happen:

See message:

"Your browser or device etc etc" (can see this when click "get ocean data")

What does happen:

![landing warning](https://cloud.githubusercontent.com/assets/2906602/15411201/995960cc-1e61-11e6-905b-0b19f2ea20f5.gif)

**Comment by jonescc** [comment]
Fixed by https://github.com/aodn/aodn-portal/pull/2201
