### ISSUE TITLE
GFI - Lat long depth/elevation missing

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2202]
App version: 4.23.2
            Build date: Fri May 20 14:21:32 AEST 2016
            Build number: 54
            Git ref: f3b156f7343f0f766f5f86aa77dcb99d4fba32b8

Steps to reproduce:

Add any collection to be taken to step 2. 

Click anywhere on the map either ocean or land

What should happen:

At top of GFI box the latitude/longitude and the depth or elevation of the click point are shown

What does happen:

Line where usually shows is just blank

**Comment by pmbohm** [comment]
Fixed by @lwgordonimos 
https://github.com/aodn/chef-private/pull/1899
