### ISSUE TITLE
Results list not pretty

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2204]
App version: 4.23.2
            Build date: Fri May 20 14:21:32 AEST 2016
            Build number: 54
            Git ref: f3b156f7343f0f766f5f86aa77dcb99d4fba32b8

Steps to reproduce:

Refresh preprod.

Look at results list

What should happen:

Collections are in popularity order

What does happen:

Well not sure what the default is before popularity filters through as there are collections on the first page I've never heard of and the very first collection at the top of the list is broken ("see next bug logged"), has no logo and was the latest one that Nat added! So hasn't been clicked nearly as much as Argo (which I'm trying to select for most tests)

**Comment by pblain** [comment]
@kereid - I think they are in popularity order but popularity is determined by geonetwork - and it has nothing to do with what users are selecting in the portal (or the resulting GN requests made by the portal).  I recall @jonescc doing an experiment to verify this.

**Comment by anguss00** [comment]
Yes @kereid I can confirm this, clicking on argo repeatedly in the backing catalogue pushes it to the top of the list.

**Comment by pblain** [comment]
Not a bug
