### ISSUE TITLE
Icon for meatadata place holder

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2206]
Steps to reproduce:

I'm not sure what happened but am reporting so it's on record, I went into preprod, and selected a facet (I don't know which one - possibly satellite) and then when I looked at the results instead of the IMOS logo there was text that read something like "Icon for metadata placeholder"

**Comment by anguss00** [comment]
I've double checked for this message @kereid, because I remembe seeing it myself... But I can't replicate on preprod (nee portal.aodn).
