### ISSUE TITLE
GOGOduck fails for Cars 2009

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2208]
Found on Preproduction but also occurring on production

Steps to reproduce:

Add Cars 2009 australian weekly collection to the map subset to dates being only a week apart and a small bounding box.
 
What should happen:

Download succeeds

What does happen:

Download fails immediately see error 
Applying subset 'TIME,2009-01-22T02:46:09.231Z,2009-12-25T23:04:36.923999Z;LATITUDE,-39.3759765625,-37.9697265625;LONGITUDE,116.5869140625,118.9599609375'
Processing file 'CARS2009_Australia_weekly.nc'

**Comment by pmbohm** [comment]
@jonescc @pblain 
Whats the time frame for removing go-go-duck V1?
There are references to info@emii and logos to change as well as fixing these few bugs?

**Comment by pblain** [comment]
@pmbohm - it will come up tomorrow in planning

**Comment by bhasin85** [comment]
Verified that the metadata works fine when pointed to gogoduck v2

![gogoduck systest aodn org au gogoduck job 19600ff3](https://cloud.githubusercontent.com/assets/2552378/16218860/eaae59ce-37c4-11e6-9ffe-16999933dbd9.png)
