### ISSUE TITLE
GogoDuck can't access URL lists for satellite composite collections

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2212]
Seeing on portal.aodn and imos.aodn

Steps to reproduce:

Add any of the following:
IMOS - SRS SATELLITE - SST L3S - 03 day composite - night time
IMOS - SRS Satellite - SST L3S - 03 day composite - day and night time composite
IMOS - SRS SATELLITE - SST L3S - 03 day composite - day time
IMOS - SRS SATELLITE - SST L3S - 01 day composite - day and night time composite

What should happen:

See a size estimate.

What does happen:

No size estimate which indicates it cannot access the URL lists

**Comment by pblain** [comment]
Content
