### ISSUE TITLE
Logo is IMOS

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2219]
App version: 4.23.6
            Build date: Tue Jun 07 17:17:28 AEST 2016
            Build number: 58
            Git ref: 193317e65f652cdad4391905c3358107e0f0aef0

Steps to reproduce:

Open http://portal-systest.aodn.org.au/imos123/

What should happen:

Logo to left is AODN

What does happen:

Logo to left is IMOS

**Comment by anguss00** [comment]
Fixed by https://github.com/aodn/chef-private/pull/1920
