### ISSUE TITLE
List of URLS is incorrect when original files are hosted by a third party organisation

### ISSUE THREAD

**Issue by smancini** [aodn/aodn-portal#2228]
# Steps to reproduce

Add the RAN CTD profiles dataset collection ((https://portal.aodn.org.au/search?uuid=bc6e10a6-4dda-41c0-8639-5c96411efc5a) or the IMAS fluorometry (https://portal.aodn.org.au/search?uuid=fc64fc7b-29b0-4607-9527-899dfa991d68 )

Proceed to Step 3 and select the "List of URLs" download option.

# What should happen

The URLs available in the text file are all valid URLs

# What does happen

The URLs are invalid and I cannot download the corresponding file

# Example:

For these two collections, the original data is hosted at the original AODN organisation but we have created a Talend harvester on their behalf and store the data in our PostGres database.

## RAN CTD profiles 

The user currently download the following URL
http://data.aodn.org.au/http://www.metoc.gov.au/thredds/fileServer/RAN_CTD_DATA/HI392LEE_H/20040702T150417Z_H_HI392LEE_H.nc

where it should be 

http://www.metoc.gov.au/thredds/fileServer/RAN_CTD_DATA/HI392LEE_H/20040702T150417Z_H_HI392LEE_H.nc

## IMAS Fluorometry layer 

http://data.aodn.org.au/http://thredds.imas.utas.edu.au/thredds/fileServer/IMAS/AMcMinn_FRRF_l_Astrolabe/2005/FRRF_TSB_20051018T130208Z_FHZI_FV01_fluorometry-R02005s_END-20051023T031828Z.nc

Where it should be

http://thredds.imas.utas.edu.au/thredds/fileServer/IMAS/AMcMinn_FRRF_l_Astrolabe/2005/FRRF_TSB_20051018T130208Z_FHZI_FV01_fluorometry-R02005s_END-20051023T031828Z.nc

## Config file to be updated

The XSLT file needs to be modified
https://github.com/aodn/geoserver-config/tree/master/wfs/transform

**Comment by pmbohm** [comment]
This is caused by the assumption that everything comes from data.aodn.org.au
https://github.com/aodn/chef-private/commit/8677e8347158373d5b6717cdabcbc5f08d85263a
