### ISSUE TITLE
Download option not updated correctly for an external WFS

### ISSUE THREAD

**Issue by smancini** [aodn/aodn-portal#2229]
# Step to Reproduce

Select an IMAS dataset collection like for example the "Nearshore temperature monitoring in Tasmanian coastal waters" (https://portal.aodn.org.au/search?uuid=71fd0720-44a6-11dc-8cd0-00188b4c0af8).

Draw a bounding box that does not include Tasmania.

# What should happen

The Download option are not available and the text "No data available (Try changing filters) should appear.

# What does happen

the download option are available and the user can download a CSV file which is emtpy.
![imas_step3](https://cloud.githubusercontent.com/assets/4506396/16509102/01781806-3f7d-11e6-91de-ba4bc481712f.png)

**Comment by pblain** [comment]
@smancini - please remember to add the bug label - otherwise the issue won't appear in the list of bugs.

**Comment by anguss00** [comment]
Summary of investigation into this issue. 
* Portal download estimator relies on list of urls online resource component configured in the metadata. 
* The list of urls produced is used to generate the download estimator AND is also used to determine if data is in the selected spatial subset range (which I would say there is room for improvement in terms of design).
* fixing this is a backlog item https://github.com/aodn/backlog/issues/26, so I'm going to close this issue as per discussion with @smancini and @pblain.
FYI @bhasin85
