### ISSUE TITLE
CAPTCHA required on first job

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2232]
Seen in production a couple of times but I can't assist in reproducing it - opening for record

Steps to reproduce:

Add an ncwms collection such as Satellite or Radar proceed to step 3 and select download as netCDF

Download popup opens

What does happen:

on first download user is required to enter CAPTCHA code

What should happen:

Only if user tried to do more than 3 downloads in 10 minutes are they required to enter CAPTCHA code

**Comment by pmbohm** [comment]
I cant reproduce this. Using Firefox with production and on master (with this commented out)
```
downloadAuth {
    // Never show a captcha to those IP addresses
    whitelistClients = [
        /*'127.0.0.1', '0:0:0:0:0:0:0:1'*/
    ]
```
