### ISSUE TITLE
Dates selected must be in logical order

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2233]
User discovered this problem in production. I have a test case but only for Argo which works as it should

Steps to reproduce:

Add ncwms collection such as radar or satellite, on step 2 select any from date, the select to date as before the from date

What does happen:

User sees no indication this is invalid yet gets a failed download

What should happen:

Box is highlighted red around date or if using calendar the dates that are not valid are greyed out

**Comment by pmbohm** [comment]
https://github.com/aodn/aodn-portal/pull/2240 fixes this for ncWMS
