### ISSUE TITLE
Point CSV does not work for external gridded data sets

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2234]
App version: 4.23.8
            Build date: Mon Jul 04 10:58:28 AEST 2016
            Build number: 60
            Git ref: 6daffbcb2eb03fb82930ed54c770325371297c72

Steps to reproduce:

ADd an external gridded collectino such as SRS Satellite Contributed Ocean Colour - SeaWIFS Chlorophyll Concentration in the Southern Ocean: Monthly, Johnson et al 2013

Subset to aproximately a month and turn on csv at point - selecting a point that will actually be where data is located

Proceed to step 3 and select download csv

What should happen:

Data is downloaded successfully as a csv

What does happen:

See error Process failed during execution /mnt/ebs/geoserver_wps_systest/temp/wps/a5d09829-9634-4790-9b86-ed6dec823c4e/out/srs_oc_so_johnson_chl_mo_seawifs_url.nc must be netcdf-3 or netcdf-4 file

**Comment by kereid** [comment]
Actually might be GoGODuck 2 causing the issue as can't get netcdf to work either but can get same dimensions in prod to work @pblain this might be a critical bug?

**Comment by jonescc** [comment]
Yes looks like an issue with srs_oc prefixed layers - GoGoDuck WPS includes remapped LONGITUDE/LATITUDE with required latitude/longitude parameters when mapping them .  Accidentally fixed in https://github.com/aodn/geoserver-build/pull/143

**Comment by jonescc** [comment]
Better fix is not to require mapping built into the code like this and either configure it, harvest it or just probe the file for the correct subset parameters

**Comment by pblain** [comment]
In answer to @kereid , we can't release it like this. We need to fix if possible. If it can't be fixed and re-tested by tomorrow, can we leave this data collection (and ones like it) on GGD v1?  Then we can release GGD v2 as planned and provide CSV at a point for most of the data collections.

**Comment by jonescc** [comment]
Well, just in case, I've put up a fix for systest (does not include any other changes made this iteration) at https://github.com/aodn/geoserver-build/tree/systest-srs-oc-hot-fix.   It only impacts SRS_OC (see https://github.com/aodn/geoserver-build/commit/732dceb5c65212267fbaa129730aedcd746ccd3d).

If @kereid had time to test this we could build this branch and promote it to systest first thing this morning (after you get in I guess).

Or we can just use gogoduck v1 for this collection - although we should probably test an updated transform to make sure it still works (it should).

**Comment by kereid** [comment]
@pblain @jonescc yes I am happy to test it I'm about halfway through testing step 3 which I would definitely finish well before pre-review at 2pm so can't imagine it will add too much more time on there.

**Comment by jonescc** [comment]
Fixed by https://github.com/aodn/geoserver-build/pull/144
