### ISSUE TITLE
Time filter issue for some SRS data collections (OC MODIS).

### ISSUE THREAD

**Issue by xhoenner** [aodn/aodn-portal#2236]
Seen on production portal. @anguss00 doesn't think it can be data related so posted this issue here.

<h3> Steps to reproduce: <h3>

Select a SRS data collection, [this one] (https://portal.aodn.org.au/search?uuid=468f550b-bbd8-42b1-91b5-313d5898d9e6) for instance but I noticed the same behaviour for other SRS layers, *e.g.* [Chl a] (https://portal.aodn.org.au/search?uuid=3177b188-9d42-4ba2-ab23-3d38b217eb3a). Note that this issue doesn't impact all SRS layers (this [SRS layer] (https://portal.aodn.org.au/search?uuid=35bf740e-792c-4e8f-b505-db40a166f27b) is fully functional) nor any ACORN layer. In Step 2, in the `From` time filter box, put in '2016/01/01'.

<h3> What does happen: <h3>

The `From` time filter box turns red, and moving the mouse over it gives a 'Disabled' error message. Looking at the calendar just to the right, all dates from 2016/01/01 to 2016/01/07 are greyed out. Only these dates are unavailable, there's no issue for the same days/months for previous years. 

<h3> What should happen: <h3>

Users should be able to select these dates.

**Comment by pmbohm** [comment]
Metadata says the data is at http://thredds.aodn.org.au/thredds/catalog/IMOS/SRS/OC/gridded/aqua/1d/catalog.html ??
It seems empty!

**Comment by pmbohm** [comment]
Watching the geoserver_wps logs for 2016/01/01 -> 2016/01/16
I can see that is misses from the 1st to the 7th
Is there any chance that Geoserver does not know of the missing files? A harvest has failed to run and populate the database that Geoserver uses?
```
03 Aug 06:33:18 INFO [worker.GoGoDuck] - Setting thread count to 1
03 Aug 06:33:18 INFO [worker.GoGoDuckModule] - Using class 'au.org.emii.gogoduck.worker.GoGoDuckModule_srs_oc'
03 Aug 06:33:18 INFO [worker.FeatureSourceIndexReader] - Processing url 'IMOS/SRS/OC/gridded/aqua/P1D/2015/12/A.P1D.20151231T000000Z.aust.sst.nc'
03 Aug 06:33:18 INFO [worker.FeatureSourceIndexReader] - Processing url 'IMOS/SRS/OC/gridded/aqua/P1D/2016/01/A.P1D.20160108T000000Z.aust.sst.nc'
03 Aug 06:33:18 INFO [worker.FeatureSourceIndexReader] - Processing url 'IMOS/SRS/OC/gridded/aqua/P1D/2016/01/A.P1D.20160109T000000Z.aust.sst.nc'
03 Aug 06:33:18 INFO [worker.FeatureSourceIndexReader] - Processing url 'IMOS/SRS/OC/gridded/aqua/P1D/2016/01/A.P1D.20160110T000000Z.aust.sst.nc'
03 Aug 06:33:18 INFO [worker.FeatureSourceIndexReader] - Processing url 'IMOS/SRS/OC/gridded/aqua/P1D/2016/01/A.P1D.20160111T000000Z.aust.sst.nc'
03 Aug 06:33:18 INFO [worker.FeatureSourceIndexReader] - Processing url 'IMOS/SRS/OC/gridded/aqua/P1D/2016/01/A.P1D.20160112T000000Z.aust.sst.nc'
03 Aug 06:33:18 INFO [worker.FeatureSourceIndexReader] - Processing url 'IMOS/SRS/OC/gridded/aqua/P1D/2016/01/A.P1D.20160113T000000Z.aust.sst.nc'
03 Aug 06:33:18 INFO [worker.FeatureSourceIndexReader] - Processing url 'IMOS/SRS/OC/gridded/aqua/P1D/2016/01/A.P1D.20160114T000000Z.aust.sst.nc'
03 Aug 06:33:18 INFO [worker.FeatureSourceIndexReader] - Processing url 'IMOS/SRS/OC/gridded/aqua/P1D/2016/01/A.P1D.20160115T000000Z.aust.sst.nc'
03 Aug 06:33:18 INFO [worker.FeatureSourceIndexReader] - Processing url 'IMOS/SRS/OC/gridded/aqua/P1D/2016/01/A.P1D.20160116T000000Z.aust.sst.nc'
03 Aug 06:33:18 INFO [worker.GoGoDuck] - Enforcing file limit...
03 Aug 06:33:18 INFO [worker.GoGoDuck] - Downloading 10 file(s)
```

**Comment by pmbohm** [comment]
I ran this on harvest database on dbprod.emii.org.au
```
SELECT t.id AS timeseries_id,
    f.url AS file_url,
    f.size,
    timezone('UTC'::text, t."time") AS "time"
   FROM srs_oc.timeseries t
     JOIN srs_oc.indexed_file f ON t.file_id = f.id
  WHERE f.url::text ~~ '%/P1D/2016/01/A.P1D.2016010%.aust.sst.nc%'::text
  ORDER BY timezone('UTC'::text, t."time");
```
Gets two results - the 8th and 9th

**Comment by pblain** [comment]
content issue now
