### ISSUE TITLE
Breaking non secure (HTTPS) image

### ISSUE THREAD

**Issue by pmbohm** [aodn/aodn-portal#2239]
### What happens

![screen shot 2016-07-14 at 9 55 14 am](https://cloud.githubusercontent.com/assets/1066981/16823694/45411b56-49a9-11e6-86a7-aa4543e8309a.png)

### What should happen
There should never be cross domain issues occur, although in reality in the AODN space this may be hard to achieve?

**Comment by lwgordonimos** [comment]
Can this be handled with a protocol relative link, e.g. "//i.creativecommons.org/l/by/4.0/88x33.png", just in case someone runs the portal on HTTP? Is that the concern?

**Comment by pmbohm** [comment]
I was thinking about GFI responses from AODN contributors.
I like the `// ` syntax though. I wonder if Grails gsp tags can write this as well?

**Comment by bhasin85** [comment]
Is this still an issue?  Look like fixed to me.

![https issue](https://cloud.githubusercontent.com/assets/2552378/17236493/b3f5a79e-558c-11e6-990a-d739ad4ad9bd.png)

**Comment by bhasin85** [comment]
Look like a geonetwork metadata content issue to me.

**Comment by bhasin85** [comment]
@pmbohm  We will need to override the following file to make the links https.

https://github.com/aodn/core-geonetwork/blob/2.10.x-imos/web/src/main/webapp/loc/eng/xml/creativecommons/jurisdictionLicenses.xml

Is there any other drawback other than mixed content console warning?

**Comment by pmbohm** [comment]
@atkinsn has fixed all IMOS metadata records. The AODN space will bring up issues like this in the future but until then, its fixed
