### ISSUE TITLE
Error trying to connect to Systest GoGODuck status page

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2241]
Steps to reproduce:

Add any radar collection, on step 2 subset to one day proceed to step 3 and select download as netcdf. when popup opens indicating job commenced click link to go to gogoduck status page.

What should happen:

See gogoduck status page

What does happen:

See this error Host for address 'http://geoserver-wps.aodn.org.au/geoserver/wps?service=WPS&version=1.0.0&request=GetExecutionStatus&executionId=f81a0f82-16c6-43f1-9260-53eb09922190' not allowed

@anguss00 is looking into this

**Comment by anguss00** [comment]
Fixed by https://github.com/aodn/metadata-utils/pull/15. Transform has been run after harvest for testing this iteration.
