### ISSUE TITLE
CSV at point - select outside boundary should not give data

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2242]
App version: 4.24.0
            Build date: Tue Jul 12 12:06:57 AEST 2016
            Build number: 62
            Git ref: 15ba961bddaeade4b6a1e517b2b0a425cf23df77

Steps to reproduce:

Add any gridded data collection, activate the point csv. Select a point that is outside the bounding constraints of the collection, note the red highlight of the box around the value, 

Proceed to step 3 and download

What should happen:
On step 2 the error indicator popup should tell the user automatically not have to hover over the co-ordinate box or on step 3 there should be an indication that no data is selected or if a file is to be downloaded be empty

What does happen:
Co-ordinate box is red, then proceeding to step 3 user sees the co-ordinates in the subsets listed outside the range, and download file has data for co-ordinates but not sure where they come from`.

**Comment by bhasin85** [comment]
Created a [backlog item](https://github.com/aodn/backlog/issues/412) after discussing it with @pblain
