### ISSUE TITLE
Some uuids do not work anymore

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2247]
App version: 4.24.0
            Build date: Tue Jul 12 12:06:57 AEST 2016
            Build number: 62
            Git ref: 15ba961bddaeade4b6a1e517b2b0a425cf23df77

Steps to reproduce:
Click these uuids:

https://portal.aodn.org.au/search?uuid=3162c844-d45c-491c-b326-6ae37e4079f9

https://portal.aodn.org.au/search?uuid=d7a14921-8f3f-4522-9a54-e7d1df969c8a

https://portal.aodn.org.au/search?uuid=52f09a23-63a2-4c14-8b3b-1fc7c8167281

What should happen:

Taken to step 2

What does happen:

Taken to step 1

**Comment by kereid** [comment]
Think this is all satellite/gridded collections

**Comment by pmbohm** [comment]
These are all caused by #2231
