### ISSUE TITLE
2nd email notification from Gogoduck job goes to junk mail

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2248]
Steps to reproduce:

Add any collection that can be aggregated ie satellite or radar and subset to a small amount, proceed to step 3 and select download as netcdf. 
Wait for emails to come (should be 2)

What should happen:

Both emails go to inbox.

What does happen:

First email goes to inbox but second goes to junk more often than not.

**Comment by pmbohm** [comment]
Both emails work for me and go to my inbox. I'm using UTAS webmail.
The headers of both emails are similar with the second email getting a better "SBRS" (SenderBase Reputation) score. Interesting the the SBRS score should change, and it might fluctuate for the worse? 
@kereid 
 1. What is your email client?
 2. Is there a rule in place that might send it to junk?
 3. Any spam filters used?
 4. Can you see the emails in the correct folder using only webmail?

**Comment by kereid** [comment]
1. Email client is Outlook 2016.
2. No I have no rules in place   
3. No Spam filters that I know of
4. No they are in junk but Jac said when she checks her email on her phone through webmail stuff that is junk is in the inbox

Thought Sendgrid can be set to ensure emails do not go to junk as we have done so in the past with others?

**Comment by pblain** [comment]
Whether or not an email message ends up in junk is at the whim of the spam filter.  Other than using SendGrid and following the recommendations (which we do) there's not much else that can be done and the sender's end. 

@kereid - perhaps try getting ITS involved.

I am going to close this because it appears to be an issue for Outlook/UTas.
