### ISSUE TITLE
portal-systest-eb

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#2274]
## Steps to reproduce
1. Go to portal-systest
1. Select IMOS - SRS Satellite - SST L3S - 01 day composite - night time
1. Go to step 3
1. Click the share link

## What happens
Share link is:
https://portal-systest-eb.aodn.org.au/search?uuid=aaad092c-c3af-42e6-87e0-bdaef945f522

## What I expected
Share link is:
https://portal-systest.aodn.org.au/search?uuid=aaad092c-c3af-42e6-87e0-bdaef945f522

**Comment by pblain** [comment]
Looks like the -eb turns up in other places too - such as the link to GoGoDuck jobs

**Comment by lwgordonimos** [comment]
This suggest that the artifact has not been rebuilt and deployed since changing the URL.

@bhasin85 we were discussing this yesterday arvo?

**Comment by bhasin85** [comment]
Thanks @lwgordonimos  

Redeployed systest with updated Portal.groovy

**Comment by bhasin85** [comment]
Fixed after Redeployment.
