### ISSUE TITLE
Selecting a point timeseries outside valid range

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#2276]
## Steps to reproduce
1. Go to portal-systest
1. Select IMOS - SRS Satellite - SST L3S - 01 day composite - night time
1. Check point time series box
1. Enter a point outside the spatial extend of the colelction

## What happens
Nothing

# What I expected
A validation error

**Comment by pmbohm** [comment]
@pblain 

@bhasin85 has expanded on the download estimator to exclude downloading when users have created a spatial subset outside the extent of the collection. Which works!

For 'timeSeriesAtaPoint' we dont have access to a download Estimator. It is specifically disabled in BodaacDownloadHandler.js
```
    canEstimateDownloadSize: function(filters) {
        return !Portal.filter.FilterUtils.hasFilter(filters, 'timeSeriesAtPoint');
    },
```
Could we estimate size download size?
Allowing  downloadEstimator would then be able to include the check if the point is within the collections bounds. Similar behaviour. win win

**Comment by pblain** [comment]
@pmbohm - we are going to redo the download size estimator very soon (it missed out on last iteration by one user story).  We can look at this as part of the work.  I'll add it to the user story in the backlog.

**Comment by pblain** [comment]
@pmbohm to update testrail to reflect expected behaviour

**Comment by pmbohm** [comment]
https://aodn.testrail.com/index.php?/cases/view/18850 modified
