### ISSUE TITLE
Creating a moorings subset

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#2277]
## Steps to reproduce
1. Go to portal-systest
1. Select IMOS - Australian National Mooring Network (ANMN) Facility - Temperature and salinity time-series
1. Draw a bounding box that covers no mooring
1. Go to step 3
1. Go to step 1
1. Draw a bounding box around a mooring
1. Draw a bounding box around a second mooring

## What happens
The final two bounding boxes are not shaded orange.
There are two boxes on the map:

![image](https://cloud.githubusercontent.com/assets/2802359/17991298/ac78a61a-6b80-11e6-979d-8249646bc24c.png)

**Comment by bhasin85** [comment]
Unable to reproduce on systest. This usually happens when you get a javascript error.
