### ISSUE TITLE
No email for ncDownloadService (jodaac)

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#2278]
## Steps to reproduce
1. Select IMOS - Australian National Mooring Network (ANMN) Facility - Temperature and salinity time-series
1. Go to step 2 and Create a subset
1. Go to step 3 and download as NetCDF

## What I expected
An email

## What happened
No email

**Comment by lwgordonimos** [comment]
Resolved in https://github.com/aodn/chef-private/pull/2043

For some reason I excluded the SMTP details from the beanstalk deploy config
