### ISSUE TITLE
Layers displayed for incorrect dates

### ISSUE THREAD

**Issue by bhasin85** [aodn/aodn-portal#2281]
**Steps to reproduce**

1. Select "IMOS - SRS Satellite - SST L3S - 01 day composite - night time"
2. Go to Step 2
3. Enter From Date 1990/03/21
4. Enter To Date 1991/03/21

**What I expected**

No layer should be displayed

**What happened**

Layers are getting displayed
![5](https://cloud.githubusercontent.com/assets/2552378/17993843/e4049f56-6b96-11e6-82a4-89cc19edde8f.png)

**Comment by pblain** [comment]
@bhasin85 - this behaviour is intentional (if I understand your meaning) - but that doesn't mean there's not a usability issue here.  You can see the displayed date below the << >> arrows.  I'll close it for now, but I think we may be able to make this more intuitive.
