### ISSUE TITLE
Bounding box coordinates not getting clear

### ISSUE THREAD

**Issue by bhasin85** [aodn/aodn-portal#2283]
**Steps to reproduce**

1. Select "IMOS - Argo Profiles"
2. Go to Step 2
3. Select bounding box anywhere on the map
4. Change the spatial subset to polygon
5. Change the spatial subset to bounding box

**What I expected**

Bounding box coordinates should be empty

**What happened**

Old bounding box coordinates are displayed
![7](https://cloud.githubusercontent.com/assets/2552378/17995012/4173ec14-6ba1-11e6-9847-240c21b3312e.png)

**Comment by pblain** [comment]
It's fine if the bounding box returns after flipping to polygon and back.  A user might select polygon accidentally and it would be annoying to lose the subset - especially if the user had typed in specific coordinates.
