### ISSUE TITLE
Unable to draw a bounding box properly

### ISSUE THREAD

**Issue by bhasin85** [aodn/aodn-portal#2284]
**Steps to reproduce**

1. Select "IMOS - SRS Satellite - SST L3S - 01 day composite - night time"
2. Go to Step 2
3. Draw a bounding box
4. Remove the data collection from the subset
5. Go to Step 1
6. Select "CARS 2009 - World Monthly"
7. Go to Step 2
8. Draw a bounding box

**What I expected**

New bounding box should get created

**What happened**

Old bounding box remains and the new one does not get created properly

**Comment by pmbohm** [comment]
Fixed in current master
