### ISSUE TITLE
Missing Date Validation Error Message

### ISSUE THREAD

**Issue by bhasin85** [aodn/aodn-portal#2285]
**Steps to reproduce**

1. Select "IMOS - SRS Satellite - SST L3S - 01 day composite - night time"
2. Go to Step 2
3. Enter From Date 2014-01-04

**What I expected**

Validation error message

**What happened**

No error message displayed
![8](https://cloud.githubusercontent.com/assets/2552378/17995804/088aff3a-6ba8-11e6-8a3f-948299cd7f0a.png)

**Comment by jachope** [comment]
Already logged as a bug two iterations ago - https://github.com/aodn/aodn-portal/issues/2249

**Comment by pmbohm** [comment]
Fixed by https://github.com/aodn/aodn-portal/pull/2295
