### ISSUE TITLE
CAPTCHA - not enabled

### ISSUE THREAD

**Issue by jachope** [aodn/aodn-portal#2291]
https://portal-systest.aodn.org.au
v4.25.5

Steps to reproduce:
Add an acorn collection and subset to one day and draw bounding box over half map diplay otherwise gogoduck will clog up.

Proceed to step 3 and select download as netCDF. Repeat 3 times on the third try CAPTCHA box will open enter CAPTCHA figures, attempt to download for a 4th time.

What does happen:
No CAPTCHA initiated at all

What should happen:
If a user tried to do more than 3 downloads in 10 minutes are they required to enter CAPTCHA code

**Comment by pmbohm** [comment]
With AWS deployments the behaviour was changed creating this bug,
With https://github.com/aodn/chef-private/pull/2055 the AWS portals will not show the CAPTCHA for ipaddresses matching `/131\.217\.38\..+/` ***except for*** portal-systest.aodn.org.au
