### ISSUE TITLE
GFI not displayed for Bounding Box Control

### ISSUE THREAD

**Issue by jachope** [aodn/aodn-portal#2292]
https://portal-systest.aodn.org.au
v4.25.5

Steps to reproduce:
Add any ncMWS collection to the map

On Bounding Box mode click on the collection.

What should happen:
GFI is populated with information about collection

What does happen:
GFI is empty.

Note: GFI should be populated for both the Pan Hand control (this is working) and the Bounding Box control (this isn't working)

**Comment by pmbohm** [comment]
Not reproducible in master
