### ISSUE TITLE
VM image (vagrant and Nectar) which has a running portal and scanners

### ISSUE THREAD

**Issue by jkburges** [aodn/aodn-portal#230]
There is a requirement to make it easy for people to easily run up a portal (and associated services).

One solution is to package up a VM image and make it available on Nectar as a public image, as well as publicly available as a vagrant box (on our FTP site perhaps).

The steps to achieve this are:

1. Move cookbooks required to deploy portal and associated services (i.e. postgresql, wms/wfs scanners) to a location outside of the current chef git repo);
2. Write Berksfile, Vagrantfile, databags (with users etc that are not the same as what's in our chef repo) and node definition such that a vagrant VM can be run up with portal and associated services running on it (these could probably all live in a subdir 'public_vm' or some such in this repo, so as to not clutter the root dir);
3. Deploy some example application data (i.e. layers etc) to the VM (note that this could possibly be done in a cookbook and so really be part of (2) above);
4. Have a jenkins job which creates a VM using the above, uploads disk image to Nectar and uploads vagrant box to FTP site which is run whenever the production portals are updated;
5. Update documentation indicating how to make use of the Nectar image or the Vagrant box.

**Comment by dnahodil** [comment]
In the backlog. See https://github.com/aodn/backlog/issues/63
