### ISSUE TITLE
Unable to select spatial subset beyond E:180

### ISSUE THREAD

**Issue by bhasin85** [aodn/aodn-portal#2300]
**Steps to reproduce**

1. Select "IMOS - SRS Satellite - SST L3S - 01 day composite - night time"
2. Draw a bounding box (W: 70, S: -70, E: 190, N: 20) 

**What I expected**
No Error Message

**What happened**
Error Message Displayed - Unable to select spatial subset beyond E:180
![open access to ocean data](https://cloud.githubusercontent.com/assets/2552378/18112320/f05cfdee-6f69-11e6-9018-256ec2ee1e47.png)

**Comment by pblain** [comment]
@bhasin85 - unless I'm misunderstanding this isn't a bug - it's a technical limitations that makes these kinds of subsets impossible - so if the user draws (or types) a bounding box across the anti-meridian a warning is displayed.
