### ISSUE TITLE
GFI does not work in Chrome on Rog's computer

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2315]
Unfortunately I cannot reproduce this or Jac either. But definitely see it on Rog's computer for production (systest does work though so leading to believe version related?).

Steps to reproduce:

Open chrome browser (53.0.2785.101 m) Add any collection to the portal (Rog was originally looking at MARVL3 - Australian shelf temperature data atlas), once take to step 2 click any point on the collection display, even zoom in to ensure clicking exactly on collection display

What should happen:

GFI opens with all relevant information

What does happen:

GFI opens but is empty.

I also compared versions of Chrome and I had an older one so upgraded to the new one to match Rog and I can still get GFI information.

**Comment by kereid** [comment]
Rog also just came to say that the Temporal Extent is not being applied to step 3 (again I tried on my computer and it works fine

**Comment by bhasin85** [comment]
Fixed by reinstalling chrome. :wink:
