### ISSUE TITLE
Download size estimated twice after performing download

### ISSUE THREAD

**Issue by jonescc** [aodn/aodn-portal#2321]
### To Reproduce

Select IMOS - SRS Satellite - SST L3S - 01 day composite - night time on step 1
Select a couple of days worth of data on step 2
On Step 3 select download and download file

### What happens

Two estimate download size requests are sent to the backend along with the download request and the estimated download size is updated

### What I expect to happen

The subset hasn't changed - there's no reason to estimate the download size again even once.

**Comment by anguss00** [comment]
Halting work on this as it requires refactoring of download estimation on step 3 to fix (pair with @jonescc). See https://github.com/aodn/backlog/issues/448

**Comment by anguss00** [comment]
"Fixed" by https://github.com/aodn/aodn-portal/pull/2347
