### ISSUE TITLE
Download estimate indicates no data when bounding box drawn over whole collection extent

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2323]
App version: 4.25.7 - Systest
            Build date: Mon Sep 12 13:50:54 AEST 2016
            Build number: 71
            Git ref: dd65fa212b67f6a081fed068f319ee89ddd49021
        -->

Steps to reproduce:

Add any collection that has a working download estimate, draw a bounding box that covers the whole collection extent and then some 
![downloadestimate](https://cloud.githubusercontent.com/assets/2906602/18537282/cf09d074-7b47-11e6-944f-f16a25e5102d.png)

Proceed to step 3 and observe download estimate

What should happen:

Estimate is big as it is the whole collection

What does happen:

See "no data available (try changing filters)

**Comment by anguss00** [comment]
@pblain should we be halting work on this too given the backlog item https://github.com/aodn/backlog/issues/448?

**Comment by pblain** [comment]
@anguss00 - please resolve this bug by removing the download estimate.

**Comment by anguss00** [comment]
Ok no worries @pblain
