### ISSUE TITLE
If first bounding box drawn is over antimeridian the red box and line remain

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2324]
App version: 4.25.7 - Systes
            Build date: Mon Sep 12 13:50:54 AEST 2016
            Build number: 71
            Git ref: dd65fa212b67f6a081fed068f319ee89ddd49021
        -->

Steps to reproduce:

Add any collection, draw a bounding box that crosses the antimeridian at 180.

What should happen:

Red error box and line flash up then dissapear to indicate invalid box

What does happen:

Red error box and line remain until another box is drawn

**Comment by anguss00** [comment]
Fixed by #2336
