### ISSUE TITLE
Contact link in footer opens a new tab in Chrome

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2334]
Seen on systest on Chrome

Steps to reproduce:

Open portal and click on contact link

What should happen:

Pop-up from users email client opens and address pre-entered in to line

What does happen:

Pop up does open but also a tab in the browser with url: mailto:info@aodn.org.au?subject=Portal%20enquiry%20-

**Comment by lwgordonimos** [comment]
This should resolve it: https://github.com/aodn/aodn-portal/pull/2335
