### ISSUE TITLE
Cannot move time forward on map

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2340]
App version: 4.25.9 - Systest on Chrome
            Build date: Thu Sep 22 13:15:18 AEST 2016
            Build number: 73
            Git ref: fcd27bff088ce4cb22731561ed1de45c3d9c16ff

Steps to reproduce:

Add any ncWMS (i.e. ACORN) Collection, select a different time for the from date (but not the last in the drop down list). note the Displayed date and time changes to that date and time. Try to click the right facing arrows to change the display on the map

What should happen:

Diplay on map proceeds forward to next time on that from date.

What does happen:

Nothing the right facing arrows aren't active - however if you click the left then the right they do activate.

**Comment by bhasin85** [comment]
Unable to reproduce on FireFox/Chrome.

**Comment by kereid** [comment]
Re-opening can still reproduce on both Firefox and chrome

**Comment by anguss00** [comment]
Cool, I'll come and have a chat to you tomorrow @kereid

**Comment by bhasin85** [comment]
@anguss00  I had a chat with Kate and she showed me how to reproduce it. Let me know if you need more details.
