### ISSUE TITLE
Error message for no data much longer than required

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2342]
App version: 4.25.9
            Build date: Thu Sep 22 13:15:18 AEST 2016
            Build number: 73
            Git ref: fcd27bff088ce4cb22731561ed1de45c3d9c16ff

Steps to reproduce:
Select any SRS SATELLITE - OC MODIS collection and add to the Portal.
Draw a bounding box away outside the extreme range of co-ordinates (ie outside the box).
Go to step 3 and select a netCDF download.

What should happen:

(Ideally user gets indication no data to download which will eventually come with estimate enhancements)

But for the last 2 months the error has been a simple one liner of:
Process failed during execution /mnt/ebs/geoserver_wps_systest/temp/wps/e6f67903-c4e2-49c1-919b-6e47d3104d2b/out/srs_sst_l3s_1d_day_gridded_url.nc must be netcdf-3 or netcdf-4 file 

What does happen:
User gets still uninformative error but much longer (not sure that it should have changed?):

Process failed during execution Could not concatenate files: [/mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160921T000000Z.aust.sst.nc, /mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160924T000000Z.aust.sst.nc, /mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160920T000000Z.aust.sst.nc, /mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160923T000000Z.aust.sst.nc, /mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160922T000000Z.aust.sst.nc] into a single file: '/mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/out/srs_oc_sst_1d_aqua_url.nc' Could not concatenate files: [/mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160921T000000Z.aust.sst.nc, /mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160924T000000Z.aust.sst.nc, /mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160920T000000Z.aust.sst.nc, /mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160923T000000Z.aust.sst.nc, /mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160922T000000Z.aust.sst.nc] into a single file: '/mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/out/srs_oc_sst_1d_aqua_url.nc' Could not concatenate files: [/mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160921T000000Z.aust.sst.nc, /mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160924T000000Z.aust.sst.nc, /mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160920T000000Z.aust.sst.nc, /mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160923T000000Z.aust.sst.nc, /mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160922T000000Z.aust.sst.nc] into a single file: '/mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/out/srs_oc_sst_1d_aqua_url.nc' ncrcat: INFO Build compiler lacked (or user turned off) OpenMP support. Code will execute with single thread in Uni-Processor (UP) mode.ncrcat: ERROR input file /mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160920T000000Z.aust.sst.nc lacks a record dimension[/usr/bin/ncrcat, -D2, -4, -h, -O, /mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160920T000000Z.aust.sst.nc, /mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160921T000000Z.aust.sst.nc, /mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160922T000000Z.aust.sst.nc, /mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160923T000000Z.aust.sst.nc, /mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/tmp/62e9e4cd-9b5c-42a1-b256-fdb1bba19eeb/gogoduck7837437194712729596/A.P1D.20160924T000000Z.aust.sst.nc, /mnt/ebs/geoserver_wps_systest/temp/wps/beeff1be-d2e4-4d0f-9e76-48e77843be46/out/srs_oc_sst_1d_aqua_url.nc]

**Comment by pblain** [comment]
Even the one liner is not appropriate.  This is a user error - but the message indicates a system error.  A message along the lines of "Your spatial subset is out of bounds" would be more appropriate.
