### ISSUE TITLE
GoGoDuck - Your aggregation failed! Reason for failure is: 'null'

### ISSUE THREAD

**Issue by jonescc** [aodn/aodn-portal#2351]
### To reproduce

Submit a gogoduck request directly to geoserver-wps requesting a subset on a layer which doesn't exist (as per requests by MARVL).

### What happens 

Get Your aggregation failed! Reason for failure is: 'null'

### What I expect to happen

Get an understandable error message or a valid file

**Comment by jonescc** [comment]
Still get an incomprehensible error message here albeit slightly different wording:

"Could not obtain list of URLs: 'null'"

In the log we get:

```
19 Oct 01:13:18 ERROR [worker.GoGoDuck] - Invalid Layer: csiro_cars_world_monthly_url
java.lang.Exception: Invalid Layer: csiro_cars_world_monthly_url
        at au.org.emii.core.Config.getLayerConfigPath(Config.java:134)
...
```

But this is of no use to the end user.

**Comment by bhasin85** [comment]
@jonescc  I am now passing the error message to the user. Now users will see 

> "Invalid Layer: cars_world_monthly"

which will be more meaningful.
