### ISSUE TITLE
GoGoDuck Spatial subset out of range

### ISSUE THREAD

**Issue by bhasin85** [aodn/aodn-portal#2353]
05 Oct 23:10:50 ERROR [worker.GoGoDuck] - NetCdf Tool Error: 'ncrcat: INFO Build compiler lacked (or user turned off) OpenMP support. Code will execute with single thread in Uni-Processor (UP) mode.ncrcat: ERROR input file /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19930331092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc lacks a record dimension[/usr/bin/ncrcat, -D2, -4, -h, -O, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19930331092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19930430212000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19930531092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19930630212000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19930731092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19930831092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19930930212000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19931031092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19931130212000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19931231092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19940131092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19940228212000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/out/srs_sst_l3s_1m_dn_gridded_url.nc]'
au.org.emii.gogoduck.exception.NetCdfProcessingException: ncrcat: INFO Build compiler lacked (or user turned off) OpenMP support. Code will execute with single thread in Uni-Processor (UP) mode.ncrcat: ERROR input file /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19930331092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc lacks a record dimension[/usr/bin/ncrcat, -D2, -4, -h, -O, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19930331092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19930430212000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19930531092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19930630212000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19930731092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19930831092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19930930212000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19931031092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19931130212000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19931231092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19940131092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19940228212000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/out/srs_sst_l3s_1m_dn_gridded_url.nc]
	at au.org.emii.gogoduck.worker.GoGoDuck.execute(GoGoDuck.java:444)
	at au.org.emii.gogoduck.worker.GoGoDuck.aggregate(GoGoDuck.java:379)
	at au.org.emii.gogoduck.worker.GoGoDuck.run(GoGoDuck.java:103)
	at au.org.emii.wps.GoGoDuckProcess.execute(GoGoDuckProcess.java:80)
	at sun.reflect.GeneratedMethodAccessor201.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.geotools.process.factory.AnnotationDrivenProcessFactory$InvokeMethodProcess.execute(AnnotationDrivenProcessFactory.java:549)
	at org.geoserver.wps.executor.ProcessStartupFilter$ProcessStartupWrapper.execute(ProcessStartupFilter.java:51)
	at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:201)
	at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:169)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jonescc** [comment]
SRS is meant to use --mk_rec_dmn time -d - so problem with config or logic?

**Comment by jonescc** [comment]
Or content - if this is different to other SRS files

**Comment by jonescc** [comment]
Getting this error because  ncks failed to subset files because the supplied spatial subset did not include any data actually in the file.  This left the the file unsubsetted and the time dimension limited.  GoGoDuck continued on anyway, unpacked the file and then tried to concatenate it with other unsubsetted files causing ncrcat to fall over with this error

What we should do:

* Check to ensure the spatial subset selects some data from the file (testing the first file would do) and return a spatial subset returns no data error or similar
* When an error is returned subsetting, unpacking or conactenating or updating attributes - stop processing files!

````
05 Oct 22:54:21 ERROR [worker.GoGoDuck] - NetCdf Tool Error: 'ncks: ERROR User-specified coordinate value range 30.96 <= lat <= 38.61 does not fall within valid coordinate range -69.99 <= lat <= 19.99[/usr/bin/ncks, -a, -4, -O, --mk_rec_dmn, time, -d, time,1993-03-16T09:20:00.000Z,1994-02-14T21:20:00.000999Z, -d, lon,128.65,141.09, -d, lat,30.96,38.61, -v, time,lat,lon,dt_analysis,l2p_flags,quality_level,satellite_zenith_angle,sea_surface_temperature,sses_bias,sses_count,sses_standard_deviation,sst_dtime, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19931031092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/tomcat7/geoserver_wps/temp/tmp3279674946972929694.nc]'
au.org.emii.gogoduck.exception.NetCdfProcessingException: ncks: ERROR User-specified coordinate value range 30.96 <= lat <= 38.61 does not fall within valid coordinate range -69.99 <= lat <= 19.99[/usr/bin/ncks, -a, -4, -O, --mk_rec_dmn, time, -d, time,1993-03-16T09:20:00.000Z,1994-02-14T21:20:00.000999Z, -d, lon,128.65,141.09, -d, lat,30.96,38.61, -v, time,lat,lon,dt_analysis,l2p_flags,quality_level,satellite_zenith_angle,sea_surface_temperature,sses_bias,sses_count,sses_standard_deviation,sst_dtime, /mnt/ebs/geoserver_wps/temp/wps/81a302d0-e7a0-45c1-be39-b0364455256c/tmp/df9ffb21-3bd7-4699-930d-989d0a91d2ef/gogoduck4190927470428961308/19931031092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc, /mnt/ebs/tomcat7/geoserver_wps/temp/tmp3279674946972929694.nc]
	at au.org.emii.gogoduck.worker.GoGoDuck.execute(GoGoDuck.java:444)
	at au.org.emii.gogoduck.worker.GoGoDuck.applySubsetSingleFileNcks(GoGoDuck.java:258)
```

**Comment by jonescc** [comment]
Same as https://github.com/aodn/aodn-portal/issues/2342
