### ISSUE TITLE
GoGoDuck over estimates size of multi-timestep files

### ISSUE THREAD

**Issue by jonescc** [aodn/aodn-portal#2360]
### To reproduce

o Set the fileSizeLimit to 400000000 (~381MB) 
o Select CARS Monthly collection and download as netcdf without subsetting
### What happens

Get an error:

"Process failed during execution Total file size 3 GB for 1 files, exceeds the limit 381 MB"
### What I expect to happen

The aggregation is successful as the size of the CARS NetCDF file is 314MB which is less than 381MB (3GB is right out)

**Comment by bhasin85** [comment]
@jonescc  My understanding is that you always get back one file for the cars collection, which is compared to the file size limit. Currently we have a file size limit of 20GB and the cars monthly collection is about 300MB, which is well below the 20 GB limit. Therefore, we should not have any issues downloading cars collection. Look like I am missing something here. A GeoServer WPS request with the above issue will be handy to verify the above case.

**Comment by jonescc** [comment]
@bhasin85, I've updated the description of this issue to more clearly outline how to reproduce this issue.  The problem is caused by GoGoDuck  adding the size of the file to the total size for each timestep included in the file (there are 12 timesteps in this file) instead of just once.

This may be a problem for other datasets later down the track as noted for Ocean Acidification or if we revisit the fileSizeLimit.   Its not a high priority to fix this at the moment as its not a problem with our current production setup/collections.

**Comment by jonescc** [comment]
Refer https://github.com/aodn/geoserver-build/issues/197
