### ISSUE TITLE
GoGoDuck empty subset returns non-empty file

### ISSUE THREAD

**Issue by jonescc** [aodn/aodn-portal#2363]
### To reproduce

Submit a request with a spatial subset which does not overlap the spatial extent of the data: 

[empty-subset.txt](https://github.com/aodn/aodn-portal/files/540754/empty-subset.txt)

### What happens

I get a bunch of errors in the log from ncks telling me that the lat/lon is outside the range of the lat/lon in the dataset, but the agregation proceeds and I get a non-empty file back (I assume its the unsubsetted data)

### What I expect to happen

I get an error telling me the requested spatial subset does not include any data

**Comment by jonescc** [comment]
To do this, for example, we could determine the min/max latitude and longitude when probing the first file for aggregation metadata

**Comment by anguss00** [comment]
Fixed by https://github.com/aodn/geoserver-build/pull/187
