### ISSUE TITLE
GoGoDuck get "No data to display. Your spatial subset is out of bounds." when subset is in bounds

### ISSUE THREAD

**Issue by jonescc** [aodn/aodn-portal#2368]
### To Reproduce

In portal-systest:

Select an acorn collection
Go to step 2
Select a spatial subset outside of the spatial extent of the collection
Go to step 3
Go to Step 2
Select a spatial extent overlapping the spatial extent of the collection 
Go to step 3

### What happens

I get "No data to display. Your spatial subset is out of bounds."

### What I expect to happen

I am able to perform the subset

**Comment by bhasin85** [comment]
Spatial Subset with the issue.

![error](https://cloud.githubusercontent.com/assets/2552378/19670881/8c86262e-9ab6-11e6-87d7-644503f888cc.png)

**Comment by kereid** [comment]
#2323

**Comment by kereid** [comment]
Also would it make a bit more sense to state "no data to download" (when there isn't any) rather than "no data to display" because step 2 is the display of the data? Thought maybe this could get fixed at the same time as the bigger issue :-)
