### ISSUE TITLE
Gogoduck cannot subset data collections using non lat-lon projections

### ISSUE THREAD

**Issue by julian1** [aodn/aodn-portal#2376]
Data collections affected - at least -Turquoise Coast and Bonny Coast. 

Possible fast 'fix' is to disable the service on those collections.

**Comment by julian1** [comment]
@pblain this should be fixed by @jonescc work. Not sure if it should have gone into the iteration.

**Comment by pblain** [comment]
@julian1 - If true this is a VIT because it's affecting users.  We should disable the service until the GGD can subset these collections.

**Comment by julian1** [comment]
@pblain I think @atkinsn should be able to delete the gogoduck resource for the collections.

**Comment by atkinsn** [comment]
Just a heads up @ggalibert

**Comment by lbesnard** [comment]
@julian1 Could this be clarified ? I don't really understand. Lat and Lon are only a coordinate system, not a projection. Do you mean that if the data doesn't have lat and lon variable names, but let say x and y, the aggregation can't be done ?

**Comment by ggalibert** [comment]
ACORN CODAR systems (site BONC and TURQ) use a lat-lon grid that is rotated making these lat-lon variables impossible to be coordinate variables in the CF sense. These lat-lon variables are a function of I and J which are the coordinate variables in the CF sense. This wasn't a problem in the recent past and was handled fine by GoGoDuck, I believe Dan had implement some specific code to handle the CODAR case.

Has anything changed recently in GoGoDuck's implementation?

**Comment by julian1** [comment]
@smancini @atkinsn @ggalibert what's the status of the metadata change?

**Comment by ggalibert** [comment]
GoGoDuck service will be removed from 4 metadata records:
* BONC non QC
* TURQ non QC
* BONC QC
* TURQ QC

Will need to be re-enabled when Craig's new code is deployed and tested.

**Comment by atkinsn** [comment]
GoGo Duck services removed from those records above. will propogate through to Portal tomorrow.

**Comment by pblain** [comment]
Will be addressed by Java GGD

**Comment by kereid** [comment]
Have emailed @atkinsn to let her know Javaduck is now in prod so these collections can have the protocol added back.

**Comment by atkinsn** [comment]
Added back in.

**Comment by ggalibert** [comment]
I can see that the metadata records are back with gogoduck entries in distribution, yet the portal is not showing a NetCDF option for download.

**Comment by jonescc** [comment]
Looks like they have invalid '--' characters in the protocol.  @atkinsn - word paste issues again?

**Comment by atkinsn** [comment]
Yep - already fixed...
