### ISSUE TITLE
Improve user error message with hint

### ISSUE THREAD

**Issue by bhasin85** [aodn/aodn-portal#2379]
### To reproduce

In systest:

Select a gridded dataset 
Select large bounding box
### What happens

![imos download error e4312fae 82d0 4ca4 b6ba fd690c1c103a](https://cloud.githubusercontent.com/assets/2552378/19840501/60d0e23c-9f4b-11e6-915e-4ef4738632f1.png)
### What I expect to happen

An error message like 

> Process failed during execution Aggregation asked for 53442 files, we allow only 2232 files. Please try again with a smaller bounding box and/or smaller time period.

**Comment by jonescc** [comment]
Fixed by https://github.com/aodn/geoserver-build/pull/196
