### ISSUE TITLE
Undefined word on step 3 in Firefox

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2381]
App version: 4.27.0
            Build date: Wed Nov 02 09:41:17 AEDT 2016
            Build number: 80
            Git ref: 9d6330b9af9699b605b61b7a42e01251431bf545
Systest:

Steps to reproduce:

Add any collection and proceed to step 3

What should happen: 
Do not see the word undefined where subsets will be listed

What does happen:

The word undefined is there for every collection - similar to https://github.com/aodn/aodn-portal/issues/2352 however it is in a different place now.

**Comment by pmbohm** [comment]
Fixed by https://github.com/aodn/aodn-portal/pull/2382
