### ISSUE TITLE
Glider collections have no GFI

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2383]
In Systest:
App version: 4.27.0
            Build date: Wed Nov 02 09:41:17 AEDT 2016
            Build number: 80
            Git ref: 9d6330b9af9699b605b61b7a42e01251431bf545

Steps to reproduce:

Add any glider collection 

Click on the collection display on the map

What should happen:

Populated GFI opens

What does happen:

GFI opens with no information

**Comment by pmbohm** [comment]
May be related to https://github.com/aodn/aodn-portal/issues/2333

**Comment by pmbohm** [comment]
Fixed by missing values added by https://github.com/aodn/chef-private/pull/2150
