### ISSUE TITLE
Thredds link in info panel broken

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2384]
In systest:

App version: 4.27.0
            Build date: Wed Nov 02 09:41:17 AEDT 2016
            Build number: 80
            Git ref: 9d6330b9af9699b605b61b7a42e01251431bf545

Steps to reproduce:
Add any ACORN collection

Click the second link to thredds in the info panel

What should happen:

Taken to thredds page that works

What does happen:

Get a 404 error:

HTTP Status 404 - Not Found

Status 404 - Not Found
THREDDS Data Server Version 4.6 -- Documentation

**Comment by jonescc** [comment]
This is a content issue.

The new version of thredds we are using in systest now correctly identifies when there is no data at the requested thredds location.   In prod you just get an empty page.

The metadat should be updated to point to the actual location of the files.
