### ISSUE TITLE
Cannot move time forward on map

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2398]
Not sure if this is related to https://github.com/aodn/VIT/issues/19

Steps to reproduce:

Add any ncWMS (i.e. ACORN) Collection, select a different time for the from date (but not the last in the drop down list). note the Displayed date and time changes to that date and time. Try to click the right facing arrows to change the display on the map

What should happen:

Display on map proceeds forward to next time on that from date.

What does happen:

Nothing the right facing arrows aren't active.

Might be the same as https://github.com/aodn/aodn-portal/issues/2340 but when user clicks left arrow then right time can only be changed once then arrow becomes inactive again.

**Comment by pblain** [comment]
@jonescc - is this related to the VIT? aodn/VIT#19

**Comment by jonescc** [comment]
No its not related to aodn/VIT#19 - layers and timestep information are being retrieved from thredds OK. Looks like a UI issue to me.

**Comment by anguss00** [comment]
Fixed by https://github.com/aodn/aodn-portal/pull/2404
