### ISSUE TITLE
Second click of grey button hides collection info on step 1

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2399]
Steps to reproduce:

Add any collection, go back to step 1 and click the select button again for the same collection then go back to step 1 again.

What should happen:

Still see all the details like geographic extent and parameters etc.

What does happen:

Only see title and select button for collection

TBH I think this has been around for a fair while I just never realised why it happened.

**Comment by pmbohm** [comment]
This comes from collapse/expand functionality introduced by https://github.com/aodn/aodn-portal/pull/2227
But yes the select button (grey or orange) should have been excluded from this selector as it makes zero sense
