### ISSUE TITLE
Map shows data in bounding box, download page says "No data is available"

### ISSUE THREAD

**Issue by mhidas** [aodn/aodn-portal#2401]
### Steps to reproduce
 1. Select the [NSW-OEH Bathymetry layer](https://portal.aodn.org.au/search?uuid=60160b01-8ffc-45ce-a6f4-ee70ce391ec6)
 2. Zoom in on northern NSW and draw a smallish bounding box around the dot (see below)
 3. Go to Step 3

![portao_nsw-oeh_step2](https://cloud.githubusercontent.com/assets/3579859/21088464/50784c82-c083-11e6-8cb5-ba71abd0748f.png)

### What happens
The download page says "No data is available using your chosen spatial subset." and no donwload options are available.

![portal_nsw-oeh_step3](https://cloud.githubusercontent.com/assets/3579859/21088475/7b222e12-c083-11e6-8823-b2151410e62f.png)

### What should happen
Since the box is clearly drawn around a point indicating data, there should be data available to download.

**Comment by mhidas** [comment]
There seems to be some kind of small offset ... if I repeat the above with a much bigger bounding box, I get the data. In fact I can get it even when the survey location is *outside bounding box* (and north of it) as show by the portal:
![portal_nsw-oeh_offset](https://cloud.githubusercontent.com/assets/3579859/21088655/4be81196-c085-11e6-8af6-5a6821954d2d.png)

**Comment by mhidas** [comment]
Maybe the "No data is available ..." message appears based on the spatial extent info in the metadata record? or in the geonetwork layer config? Both of these can be somewhat misleading, especially the latter, which -- as far as I know -- is never updated as the collection grows!

**Comment by pmbohm** [comment]
@jonescc How often are bbox's refreshed in Geonetwork?

**Comment by pmbohm** [comment]
@mhidas Some of the hits and misses can be explained by the granularity of the bbox as defined in Geonetwork and that the survey is represented on the Portal as a point with no area. 
The portal is using Geonetwork information not Geoservers. Today there is a new point added that I can see in portal and also the corresponding Geonetwork record. So today it seems to make sense.
The question is how long could Geonetwork be out of step with Geoserver and is this a problem?

![screen shot 2016-12-14 at 11 59 46 am](https://cloud.githubusercontent.com/assets/1066981/21165717/50184530-c1f5-11e6-9088-656144a32003.png)

**Comment by jonescc** [comment]
For talend harvester updated bounding boxes - whenever the talend harvester is run (usually triggered by the pipeline ).

Other bounding boxes are updated manually (e.g. gridded data which doesn't change)

**Comment by mhidas** [comment]
Thanks @pmbohm . That explains the "false hits"... in my [second post](https://github.com/aodn/aodn-portal/issues/2401#issuecomment-266344503) above. I was actually getting the data from a newer survey added that day, which just hadn't appeared yet on the map because of caching.

However, it doesn't explain why I was told there's no data in the first case. The metadata record in GN should have been updated when the survey was published. The Geographic Extent added is a square box that should include the survey. So if in the portal I draw a bounding box around the survey, it should also overlap the Geographic Extent in the metadata record!

Unfortunately I can't reproduce this anymore, now that there are more surveys in there.

**Comment by mhidas** [comment]
But I can still put a bounding box just outside the actual data coverage seen in the map, get no warning about no data, select a download option, and get an empty zip file!

Shouldn't the portal actually query the geoserver WFS to determine whether there is any data to be downloaded? Otherwise the answer can be plain wrong.

**Comment by pmbohm** [comment]
Agreed that querying the Geoserver would lead to less confusion. This topic has been discussed previously and for the moment the spatial info will come from Geonetwork
