### ISSUE TITLE
Message from webpage in Unsupported browser

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2411]
This is in production and also systest - not sure if bug.. maybe enhancement.

Steps to repeat - open portal in Internet explorer or any other unsupported browser

What happens:

See message: Your browser or device is unsupported and may not work with this site. Please use Chrome or Firefox on a later generation Windows PC, Linux or Macbook/iMac for the best experience.

What should happen:

Message says:

Your browser or device is unsupported. Please use Chrome or Firefox on a later generation Windows PC, Linux or Macbook/iMac.

**Comment by lwgordonimos** [comment]
I think referencing Macbook/iMac isn't really the best wording any more. In fact even mentioning the OS at all is probably redundant when Chrome and Firefox are the real target platforms. Could we just simplify it down even more to something like:

_Your browser is unsupported. Please use Chrome or Firefox for the best user experience._

Or similar... thoughts?

**Comment by kereid** [comment]
Yes agree, the more simple the better.

**Comment by anguss00** [comment]
![meekat](https://cloud.githubusercontent.com/assets/5964166/22049460/6c104730-dd87-11e6-82ff-e97f0921f8f6.gif)
