### ISSUE TITLE
Js Console error in step 2 spatial extent filter for NcWms layers

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2413]
Same as https://github.com/aodn/aodn-portal/issues/1069 Seeing in systest

Add any SRS Collection

Turn on firebug (for Firefox - other browser use appropriate dev tool)

Click in start date field and type 2014-01-4 and then click mouse outside of date field

What should happen:

Not see console error

What does happen:

See console error

TypeError: this.dateValue is undefined

**Comment by akashisama** [comment]
Couldn't replicate
