### ISSUE TITLE
portal-123 still works

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2419]
Steps to reproduce:

Type in the address bar portal-123.aodn.org.au

What should happen:
User redirected to portal.aodn.org.au
 
What does happen:
User sees portal-123 in the address bar, but all functionality seems to still be there so it might be the correct portal just not changing the address.

**Comment by lwgordonimos** [comment]
It is the correct portal, but you're right, it should be redirecting the URL to the correct one. Shouldn't be too hard to fix.

```bash
09:57:00 ~$ nslookup portal-123.aodn.org.au
Server:		131.217.0.19
Address:	131.217.0.19#53

Non-authoritative answer:
portal-123.aodn.org.au	canonical name = portal.aodn.org.au.
Name:	portal.aodn.org.au
Address: 13.54.30.17
Name:	portal.aodn.org.au
Address: 13.55.198.89
```
