### ISSUE TITLE
Date selected does not show in step 3 

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2420]
I have a very vague recollection that this has occurred once before but cannot find any issues about it.

Steps to reproduce:

Add https://portal.aodn.org.au/search?uuid=ca15915b-38c5-4e95-8d25-9cc42c4dd485 to the map

Select Seaflyte from Vessel name

Select any date in September 2016 from either the calendar or manually type it, proceed to step 3

What should happen:

Step 3 indicates date selected in September

What does happen:

Step 3 shows date as being the day selected but in October 2016 

If user selects dates before or after this month and downloads as URL the September dates are there so it's not like the data isn't there

**Comment by kereid** [comment]
Actually I just checked for other non gridded sets and it seems to be occurring for all of them and this is in production

**Comment by pmbohm** [comment]
cant reproduce.
