### ISSUE TITLE
Console error in chrome when adding any collection

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2421]
Steps to reproduce:

Open Chrome and open developer tools

Add any collection

What should happen:

no errors in the console

What does happen:

See the error:

jquery-1.6.min.js:16 'webkitRequestAnimationFrame' is vendor-specific. Please use the standard 'requestAnimationFrame' instead.

Same as #2337

**Comment by pmbohm** [comment]
This one is a warning message only. It just an annoyance that comes from using an older jQuery library basically
