### ISSUE TITLE
adding R scripts to download options

### ISSUE THREAD

**Issue by mdsumner** [aodn/aodn-portal#2426]
I'm keen to help develop R examples to go alongside the Python ones.  Clearly we could also have Python and R tools to generate these URLs from within existing data set and mapping contexts in those languages. 

```R
collection_url <- "http://geoserver-123.aodn.org.au/geoserver/ows?typeName=imos:argo_profile_data&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=INTERSECTS(position%2CPOLYGON((142.822265625%20-43.814453125%2C142.822265625%20-42.759765625%2C150.380859375%20-42.759765625%2C150.380859375%20-43.814453125%2C142.822265625%20-43.814453125)))%20AND%20oxygen_sensor%20%3D%20true"

## install.packages("readr")
library(readr)
## read into a data frame
d <- read_csv(collection_url)

## install.packages("ggplot2")
## uncomment this code to make a plot from the "d" object above
#library(ggplot2)
#ggplot(d[d$pres < 100, ]) + aes(longitude, latitude, col = psal) + geom_point()
#ggplot(d) + aes(psal, -pres, col = temp) + 
# geom_point() + 
#  facet_wrap(~platform_number) 
```

It's possible as well with ggplot2 to have pretty concise code for very general plots, and having that in the code, or possibly even delivering as a more integrated data/documentation package could be really interesting. Here's the second plot from the code above. 

![image](https://cloud.githubusercontent.com/assets/4107631/22533290/47dbab96-e941-11e6-8a5d-eba8897f1232.png)

**Comment by pblain** [comment]
@mdsumner - good idea. I added this to our product backlog (another GitHub repo) for prioritisation.  I'm going to close this issue to avoid duplication.
