### ISSUE TITLE
Temporal subsetting fails for time selection prior to year 1900

### ISSUE THREAD

**Issue by bpasquer** [aodn/aodn-portal#2433]
Step to reproduce:
select Ocean Acidification reconstruction collection.
Select a spatial subset on the map, then select a temporal extent that includes pre 1900 dates, 

What happens:
The requested Netcdf download fails. The job reports says:
"Status :
Unknown status, error retrieving status from WPS server"

What should happen:
The subset should be successfully created and ready for download.

**Comment by pmbohm** [comment]
Will be fixed by the work for https://github.com/aodn/backlog/issues/557.
Ps: Time validator in Geoserver-build had a regex that expected datetimes to start with `19` or `20`
