### ISSUE TITLE
No go button for keyword search

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2448]
In Systest:

Steps to reproduce:

Type a word in the keyword search

What happens:

Can't see where to submit request try to click big magnifying glass as that would be the other logical way but that also does nothing - it does work if user clicks enter

What should happen:

There should be a go and clear button to match the rest of the other facets such as geographic bounding and date where they have default go and clear buttons. The same as what is currently in production now when keyword search is opened.

**Comment by pblain** [comment]
This is more of a feature request than a bug. I will add a backlog item to count the number of users who are confused by this (using Google Analytics).  If it proves to be a usability issue we'll fix it.
