### ISSUE TITLE
Shapefile download does not show spatial subset on step 3

### ISSUE THREAD

**Issue by anguss00** [aodn/aodn-portal#2454]
In portal-edge, build 4.28.6

Steps to reproduce:
Go to http://portal-edge.aodn.org.au/search?uuid=9d6b28d2-2d6b-4726-b603-ab03e3d15d34 and select any bbox. Go to step 3 and download the data. Note the data HAS been subsetted AFAIK.
Expected:
Step 3 shows the spatial subset params.
Observed:
Step 3 says yo gonna download the whole collection (which is not true).

**Comment by pblain** [comment]
Not an issue according to @bhasin85
