### ISSUE TITLE
GoGoDuck jobs are only being kept for 48 hours - should be kept a week

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2464]
Steps to reproduce:

Complete any small gridded collection download. 
Wait 48 hours

What should happen:

Still be able to access download for a week after completion

What does happen:
Job is discarded after 48 hours

This was set to a week in early December 2016, and not sure why it has changed - or when it changed, only realised it changed when a user wrote in to say they got succeeded email on Friday and by Saturday the job was gone!

**Comment by kereid** [comment]
Changed my mind opening as a VIT as it is affecting user access to data

**Comment by kereid** [comment]
Reopening as we shouldn't start an iteration with a VIT so it should be a bug

**Comment by pblain** [comment]
This is in the backlog https://github.com/aodn/backlog/issues/605
