### ISSUE TITLE
Portal-edge does not register GA events

### ISSUE THREAD

**Issue by anguss00** [aodn/aodn-portal#2465]
Version 4.28.7 Edge build

Steps to reproduce:
Go to portal-edge, open GA -> Real-time -> active users. 

Observed behaviour: no active users

Expected behaviour: 1 active user

**Comment by bhasin85** [comment]
![events overview analytics](https://cloud.githubusercontent.com/assets/2552378/24943156/7c81de46-1f98-11e7-9f61-398737a3a98a.png)
![audience overview analytics](https://cloud.githubusercontent.com/assets/2552378/24943157/7dd4d87a-1f98-11e7-8cf2-7a0cd99d3d40.png)


Google Analytics is getting updated, but the events/sessions take time to reflect.
