### ISSUE TITLE
Gridded collections not working in production 

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2466]
This is the VIT that was investigated it was seen in Systest Friday and @jonescc fixed it there yet it somehow got to production! @lwgordonimos solved for now by reverting the system clock back to UTC so that the portal is working whilst this is investigated. As we should not start an iteration with a VIT logging it here as a bug:

See https://github.com/aodn/issues/issues/36 for further information on issue.

**Comment by lwgordonimos** [comment]
@jonescc I have put up a PR which fixes the issue. Simply installing the package looks to resolve the problem: https://github.com/aodn/chef/pull/484

For the URL: http://geoserver-123.aodn.org.au/geoserver/imos/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=imos:acorn_hourly_avg_rot_qc_timeseries_url&maxFeatures=50&sortBy=time&outputFormat=application%2Fgml%2Bxml%3B+version%3D3.2

tzdata-java installed:
```xml
<wfs:member>
<imos:acorn_hourly_avg_rot_qc_timeseries_url gml:id="acorn_hourly_avg_rot_qc_timeseries_url.fid-b0ceb20_15b56baf762_-7fcb">
<imos:timeseries_id>797823</imos:timeseries_id>
<imos:file_url>IMOS/ACORN/gridded_1h-avg-current-map_QC/ROT/2010/02/23/IMOS_ACORN_V_20100223T063000Z_ROT_FV01_1-hour-avg.nc</imos:file_url><imos:size>103837.0</imos:size>
<imos:site_code>ROT, Rottnest Shelf</imos:site_code>
<imos:time>2010-02-23T06:30:00Z</imos:time>
<imos:st_makepoint>
<gml:Point srsName="http://www.opengis.net/gml/srs/epsg.xml#4326" srsDimension="2">
<gml:pos>1 2</gml:pos>
</gml:Point>
</imos:st_makepoint>
</imos:acorn_hourly_avg_rot_qc_timeseries_url>
</wfs:member>
```
tzdata-java *not* installed:
```xml
<wfs:member>
<imos:acorn_hourly_avg_rot_qc_timeseries_url gml:id="acorn_hourly_avg_rot_qc_timeseries_url.fid--13297e43_15b56c0061a_-7ffd">
<imos:timeseries_id>797823</imos:timeseries_id>
<imos:file_url>
IMOS/ACORN/gridded_1h-avg-current-map_QC/ROT/2010/02/23/IMOS_ACORN_V_20100223T063000Z_ROT_FV01_1-hour-avg.nc
</imos:file_url>
<imos:size>103837.0</imos:size>
<imos:site_code>ROT, Rottnest Shelf</imos:site_code>
<imos:time>2010-02-22T20:30:00Z</imos:time>
<imos:st_makepoint>
<gml:Point srsName="http://www.opengis.net/gml/srs/epsg.xml#4326" srsDimension="2">
<gml:pos>1 2</gml:pos>
</gml:Point>
</imos:st_makepoint>
</imos:acorn_hourly_avg_rot_qc_timeseries_url>
</wfs:member>
```

**Comment by jonescc** [comment]
Fixed by https://github.com/aodn/chef/pull/484
