### ISSUE TITLE
No options in filter download where there always has been and still is in production

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2468]
Seeing in sytest

Steps to reproduce:

Add Australian National Mooring Network (ANMN) Facility - Current velocity time-series collection

On step 2 select deployment code CH070-0910

What should happen:

Can actually select codes from a dropdown 

What does happen:

The filter is not populated it just says no options available.

Checked production and they are still there, and have always been there because that is a specific test case I have. @lbesnard tagging you just to see if you have any thoughts?

**Comment by pmbohm** [comment]
Works currently in systest and dev environment now. @kereid 
@lwgordonimos @anguss00 @akashisama - Wasn't there a DB problem recently?

**Comment by kereid** [comment]
Hmm weird guess it can't be reproduced so it can be closed
