### ISSUE TITLE
Layers with Red Square style showing Phytoplankton style instead

### ISSUE THREAD

**Issue by akashisama** [aodn/aodn-portal#2471]
Occurring on all portals/geoservers

Steps to reproduce:

Add SOTS layer (https://portal.aodn.org.au/search?uuid=723a3e85-04ae-40e6-ac2a-237a93d84abe)
Click on "Layer" in the sidebar

What should happen:
"Red square" listed as style and map icons are red squares

What does happen:
"Phytoplankton Location" listed as style and map icons are pretty green circles.

Discussed in https://github.com/aodn/content/issues/237

**Comment by kereid** [comment]
Been around since 2015 ... https://github.com/aodn/content/issues/143

**Comment by pblain** [comment]
Content issue
