### ISSUE TITLE
JavaDuck and geospatial_lat/lon_min/max attributes

### ISSUE THREAD

**Issue by ggalibert** [aodn/aodn-portal#2472]
In systest

**Steps to reproduce:**

Add any radar data collection and in step 2 define a temporal extent so that it includes 2 or 3 time steps (faster). No need to subset spatially.

Proceed to step 3 and select download as netcdf.

**What should happen:**

The following attributes:
-geospatial_lat_min
-geospatial_lat_max
-geospatial_lon_min
-geospatial_lon_max

should be updated to reflect what is actually found in the aggregated file with values of the same "type" as the LATITUDE/LONGITUDE variables (usually Double) or at least should be numeric (IMOS checker requirement).

**What does happen:**

The following attributes:
-geospatial_lat_min
-geospatial_lat_max
-geospatial_lon_min
-geospatial_lon_max

are being updated with the correct values but using the "type" String. Below is the diffrence between one of the original file and the aggregated file:
```
< 		:geospatial_lat_min = -33.433849 ;
< 		:geospatial_lat_max = -30.150743 ;
---
> 		:geospatial_lat_min = "-33.433849" ;
> 		:geospatial_lat_max = "-30.150743" ;
```

**Comment by ggalibert** [comment]
This is also valid for GSLA collections.

**Comment by ggalibert** [comment]
Also valid for CARS.

**Comment by jonescc** [comment]
The type of these global attributes can be set in the new aggregation template functionality refer [Controlling aggregation output](https://github.com/aodn/geoserver-build/blob/master/src/extension/wps/doc/GOGODUCK_README.md#controlling-aggregation-output) in the javaduck configuration documentation.   Its currently defaulting to String as per the old version of GoGoDuck.   This functionality should be tested in RC when javaduck is promoted to production.

**Comment by ggalibert** [comment]
@pblain, didn't you want me to test again before you close?

**Comment by pblain** [comment]
@ggalibert - as I understand it the template code has been unit tested and is ready for release to production - pending Kate's front end testing. You'll need to test in RC following the release. Let me know (and reopen it) if you find an issue.  The issue belongs in geoserver-build repo BTW.
