### ISSUE TITLE
Lots of red in console when adding collections

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2478]
Seeing in systest using firefox:

Steps to reproduce:

Open firebug and then add any collection to the map

What should happen:
No red in console.

What does happen:
See this error for every single collection added.

XML Parsing Error: no root element found
Location: https://portal-systest.aodn.org.au/proxy?url=https%3A%2F%2Fcatalogue-systest.aodn.org.au%2Fgeonetwork%2Fsrv%2Feng%2Fxml_iso19139%3Fuuid%3D4402cb50-e20a-44ee-93e6-4728259250d2&_dc=1493678924201
Line Number 1, Column 39:

**Comment by kereid** [comment]
Just checked and it's in production too

**Comment by julian1** [comment]
# The url that fails
$ curl --insecure 'https://catalogue-systest.aodn.org.au/geonetwork/srv/eng/xml_iso19139?uuid=4402cb50-e20a-44ee-93e6-4728259250d2&styleSheet=xml_iso19139.mcp.xsl' | less

# Specifying mcp schema and it's ok,
$ curl --insecure 'https://catalogue-systest.aodn.org.au/geonetwork/srv/eng/xml_iso19139.mcp?uuid=4402cb50-e20a-44ee-93e6-4728259250d2&styleSheet=xml_iso19139.mcp.xsl' | less
