### ISSUE TITLE
The Australian Phytoplankton Database (1844 - 2016)

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#2484]
## Steps to reproduce
Find Australian Phytoplankton Database (1844 - 2016) - abundance and biovolume on Step 1

## What happens
Can't see the date range because of the organisations

## What should happen
Can see the date range.

**Comment by atkinsn** [comment]
I would like to put a vote in for not losing any of the organisation names (i.e. hiding half the list), and reverting to how this collection was first displayed in the search results when initially released - which was by being fully expanded to show all content.

**Comment by julian1** [comment]
I asked @pmbohm about this on Tuesday. His opinion was that it was not a bug. @pblain probably needs your input.

**Comment by pblain** [comment]
Step 1 is a faceted search.  The purpose of the faceted search is to allow users to search for data collections. Step 1 has _no other purpose_ apart from searching. All layout decisions need to be made with this purpose in mind. It is vital that each search result is easy to read - and easy to compare with the other results in list. Users need to be able to see the date range.  If they can't see the date range we have a bug.  

Giving recognition to each of the contributing organisations is important. We should provide the extended list of contributing organisations in the metadata, and perhaps on the step 3 popup, and perhaps in the download. They should also be available under the organisation facet. But we shouldn't swamp a search result with too many organisations, or anything else.  The faceted search is not the place to do it. The purpose of the faceted search is searching. It will make it more difficult (not easier) to search if we swamp it with too many organisations. If it doesn't make searching easier we shouldn't do it.

**Comment by pmbohm** [comment]
+1 @pblain  So to achieve this, the order of details should be changed in order of importance to Portal users. 
1. Title
1. Date Range
1. Organisations

**Comment by atkinsn** [comment]
The listing of the organisation name is not only from a contribution point of view - users also use this to identify collections involving organisations that they might be interested in - so to SEARCH by.

What is the assumption that date is a more important search function that organsation derived from?

Giving recognition is important - and all organisations are already listed in the metadata record - as this is where this list on step 1 is pulled from. And the relevant people are already acknowledged and listed in the data download popup.

I am happy with @pmbohm suggestion to swap the order of display - but I would like the capacity of users to be able to expand out this search window to be retained as it currently works - so users can still expose the full list if they chose.

**Comment by pmbohm** [comment]
@atkinsn Your probably interested in https://github.com/aodn/aodn-portal/issues/2486

**Comment by pblain** [comment]
@atkinsn - I'm happy with that

**Comment by atkinsn** [comment]
🥇 :)
