### ISSUE TITLE
Commas in Step 1 search result organisation names 

### ISSUE THREAD

**Issue by pmbohm** [aodn/aodn-portal#2486]
## To visualise
To reproduce search for  `Phytoplankton` and note the `The Australian Phytoplankton Database (1844 - 2016) - abundance and biovolume` collection has many organisations

### What happens
Organisations have commas within the name and the list is concatenated with commas leading to confusion as to who are the contributors
EG: School of Biological Sciences, Flinders University, .... is one organisation not two

### What should happen
commas should be stripped from organisation names in Portal Step 1 search results
`School of Biological Sciences, Flinders University, .. ` would become
`School of Biological Sciences Flinders University, .. `

**Comment by atkinsn** [comment]
The AODN organisation vocabulary has these organisations listed, with commas between the different divisions in the name. Removal of these commas, essentially changes the names of these organisations (and we should be honoring our own managed vocabulary), and for some long convoluted one would start to look messy. 

What is wrong with replacing the commas between organisation names with semi-colons??
