### ISSUE TITLE
No warning about incompatibility with Microsoft Edge web browser

### ISSUE THREAD

**Issue by ggalibert** [aodn/aodn-portal#2490]
The PC room used by students downstairs is equipped with Microsoft Windows 10 Enterprise which comes with Edge 25 web browser.

**What happens**
Go to the portal with Edge web browser. I can continue to Step 1 without any trouble and face features that are not supported like the parameters involved in data collections.

**What should happen**
There should be a warning displayed in a pop up window about incompatibility with this browser, suggesting we should use either Firefox or Chrome.

**Comment by pmbohm** [comment]
@ggalibert Thanks,  I had never even heard of Edge 25

**Comment by pblain** [comment]
@ggalibert - note: I closed it because it's ready for testing

**Comment by ggalibert** [comment]
Thanks @pblain , I was just unaware of your workflow and it seemed strange to me to close an issue when a fix hasn't been tested/approved.
