### ISSUE TITLE
WPS status page, 'conditions of use' link returns 404

### ISSUE THREAD

**Issue by julian1** [aodn/aodn-portal#2493]
Steps to reproduce: same as https://github.com/aodn/aodn-portal/issues/2480

Click 'Conditions of use' link of

```
Use of this web site and information available from it is subject to our Conditions of use 
```

get 404 for  http://imos.org.au/imostermsofuse0.html

**Comment by kereid** [comment]
@julian1 the IMOS website got updated last week (all the slugs changed so I suspect that's the cause) so I will get Marian to just check it before we change anything here as they may be able to sort it.

**Comment by julian1** [comment]
No problem. Just noticed the behavior and felt it should be documented.

**Comment by kereid** [comment]
Well spotted!

**Comment by kereid** [comment]
The redirect for the page was not turned on - Marian created it yesterday so all working as it should.
