### ISSUE TITLE
Cannot un-expand search result details

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2507]
This is the same as https://github.com/aodn/aodn-portal/issues/2481

I'm still seeing this in systest for both Chrome AND Firefox yet it was closed 15 days ago so assuming it would have been released into systest...

Steps to reproduce: 

On step 1 click the result of Australian Phytoplankton database to see all of the organisations that contributed. Click again.

What should happen:
Result text unexpands

What does happen:
Remains expanded - sometimes it unexpands and then straight away expands again.

**Comment by pmbohm** [comment]
@kereid Works 100% seamlessly for me with Chrome Version 58.0.3029.110 (64-bit)
Probably cache or another JS error was thrown moments before?

**Comment by kereid** [comment]
@anguss00 would this be fixed in the systest I am currently testing?

**Comment by kereid** [comment]
@pblain I can still reproduce this on systest - I click multiple times to get it to happen but cannot advise how many clicks or where to click to reproduce it. I think it's always been this way I've just never logged it as didn't think anyone else would click as much as I do on it. So just wondering if this is something worth investigating any further as it's spanned 2 iterations and I don't think users will really click as much as I will. But if you still want it investigated let me know and I will open a new bug for it.

**Comment by akashisama** [comment]
@kereid looks like the (potential) fix didn't make it into systest yet

**Comment by pblain** [comment]
@akashisama - do you mean the fix by @pmbohm - or a more recent potential fix?

**Comment by akashisama** [comment]
the most recent one, it went into master a day after the latest systest was built

**Comment by pblain** [comment]
Great. @kereid - please test it again next test cycle and re-open if the bug's still there. Hopefully it was squashed for good this time!

**Comment by jachope** [comment]
Testing V4.29.8 - this issue is still there.

**Comment by jachope** [comment]
Testing V4.29.11 - this issue is still there.

**Comment by pblain** [comment]
Flagging as won't fix until we get the new organisation vocab.
