### ISSUE TITLE
Collection with broken link not removed by Online Resource monitor

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2508]
In systest:

Steps to reproduce:

Refresh portal

Pick a collection to add (soop sst near real time) and then using info tab

Login to systest geonetwork http://catalogue-systest.aodn.org.au/geonetwork/srv/eng/main.home

Find collection - search soop sst near

Change online resource from geoserver to beoserver

Wait for a while (think I've been waiting over 2 hours today)  

What should happen:

Collection placed onto "bad" liast

What does happen:

Collection is still in noraml result list

**Comment by akashisama** [comment]
The online monitor has started up now but it's moving all our layers to health=bad because the getcapabilities check is failing. Ncwms tile request checks are also failing even though they work fine in portal.
