### ISSUE TITLE
Large CSV fails

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2518]
Sorry if this has already been address as I'm sure I recall reading about it but can't find the issue:
Found in Chrome from testing trying to get a csv more than 1million rows

Steps to reproduce:

Add a large collection such as ANMN Temperature Salinity Time Series, do not apply any filtering. Proceed to step 3 and download as csv 

What should happen:

Download succeeds

What does happen:

Download fails - error is "network error"

**Comment by kereid** [comment]
@pblain I had another look at this as requested, so I tried a very large bounding box over all data and it failed, then a smaller bounding box over half still failed, then a smaller bounding box over about a quarter which worked and was over a million rows.

**Comment by jonescc** [comment]
Looking at the systest logs, there are no errors reported for wfs downloads of anmn_ts this morning.

apache logs:

```54.252.221.0 - - [13/Jul/2017:10:38:20 +1000] "GET /geoserver/ows?typeName=anmn_ts_timeseries_data&SERVICE=WFS&outputFormat=csv-with-metadata-header&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=INTERSECTS(geom%2CPOLYGON((112.0166015625%20-23.4677734375%2C112.0166015625%20-10.5478515625%2C159.9169921875%20-10.5478515625%2C159.9169921875%20-23.4677734375%2C112.0166015625%20-23.4677734375)))&downloadToken=1499906300098 HTTP/1.1" 200 1533240588 "-" "Java/1.8.0_111"
54.206.93.147 - - [13/Jul/2017:10:55:24 +1000] "GET /geoserver/ows?typeName=anmn_ts_timeseries_data&SERVICE=WFS&outputFormat=csv-with-metadata-header&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=INTERSECTS(geom%2CPOLYGON((142.7783203125%20-25.62109375%2C142.7783203125%20-13.052734375%2C155.2587890625%20-13.052734374999998%2C155.2587890625%20-25.62109375%2C142.7783203125%20-25.62109375)))%20AND%20TIME%20%3E%3D%20'2015-11-03T00%3A00%3A00.000Z'%20AND%20TIME%20%3C%3D%20'2017-07-13T23%3A59%3A59.999Z'&downloadToken=1499907324732 HTTP/1.1" 200 2719924445 "-" "Java/1.8.0_111"
54.252.222.187 - - [13/Jul/2017:12:04:17 +1000] "GET /geoserver/ows?typeName=anmn_ts_timeseries_data&SERVICE=WFS&outputFormat=csv-with-metadata-header&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=INTERSECTS(geom%2CPOLYGON((143.3935546875%20-21.578125%2C143.3935546875%20-13.931640625%2C149.0185546875%20-13.931640625%2C149.0185546875%20-21.578125%2C143.3935546875%20-21.578125)))%20AND%20TIME%20%3E%3D%20'2015-11-03T00%3A00%3A00.000Z'%20AND%20TIME%20%3C%3D%20'2017-07-13T23%3A59%3A59.999Z'&downloadToken=1499911456368 HTTP/1.1" 200 1906054326 "-" "Java/1.8.0_111"
54.206.93.147 - - [13/Jul/2017:10:54:44 +1000] "GET /geoserver/ows?typeName=anmn_ts_timeseries_data&SERVICE=WFS&outputFormat=csv-with-metadata-header&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=INTERSECTS(geom%2CPOLYGON((142.7783203125%20-25.62109375%2C142.7783203125%20-13.052734375%2C155.2587890625%20-13.052734374999998%2C155.2587890625%20-25.62109375%2C142.7783203125%20-25.62109375)))&downloadToken=1499907284485 HTTP/1.1" 200 11284942911 "-" "Java/1.8.0_111"
```

Looks like elastic beanstalk replaced an instance about the time that these requests were being performed.  Any downloads being performed at that time would be killed (wfs downloads are proxied through the portal).

https://jenkins.aodn.org.au/job/portal_4_systest_deploy/changes

**Comment by jonescc** [comment]
Doesn't look like a software error.   Closing

**Comment by jonescc** [comment]
Actually reopening - not clear why a geoserver-portal jndi change would trigger a portal-systest redeploy

**Comment by jonescc** [comment]
Not a portal issue - opened a cross-cutting issue to address portal-systest deploys being triggered by apparently unrelated changes: https://github.com/aodn/issues/issues/80
