### ISSUE TITLE
Warning message when no temporal info exists

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#2524]
## Steps to reproduce
1. Select the bathymetry layer (i.e. the new layer with no time steps)
2. Go to step 2

## What happens
1. A warning message appears that reads "The dataset has no temporal information" 

## What should happen
1. No warning message
2. Info text that reads "Spatial subsetting only for this data collection"
3. Info text is styled black/grey not orange.

**Comment by pmbohm** [comment]
@pblain Do you want everything to remain the same for step 3 ?

**Comment by pblain** [comment]
@pmbohm - I only got a quick look at it, but from what I recall step 3 was fine. Maybe you can show it to me though.
