### ISSUE TITLE
Users event category not appearing in Google Analytics

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#2532]
## Steps to reproduce
1. Go to Google Analytics
1. Go to Behaviour->Events->Top Events

## What I expected
1. Users event category as per acceptance criteria here: https://github.com/aodn/backlog/issues/647#issuecomment-310287796

## What happened
1. Users event category not visible

**Comment by pmbohm** [comment]
@pblain Using the GA Debug plugin for Chrome I discovered the message `analytics_debug.js:10 Expected an integer value for the field: "eventValue". But found: "emailWasRequested".`
To fix I will make the eventValue = 1 where "emailWasRequested"

Also I discovered that the ga.js library is legacy!
https://developers.google.com/analytics/devguides/collection/upgrade/
