### ISSUE TITLE
NetCDF Aggregation request slows portal systest

### ISSUE THREAD

**Issue by akashisama** [aodn/aodn-portal#2534]
### To reproduce
Follow the instructions at https://github.com/aodn/geoserver-build/issues/240

I'm logging this as a separate bug because the portal shouldn't fall over because of a bug in another system.

### What should happen
An error message appears saying the aggregation failed, and then the portal continues to run smoothly like it was before.

### What actually happens
After the aggregation fails the portal becomes unusable, with proxied requests to any external service (such as catalogue-systest and geoserver-systest) constantly timing out. For instance, go back to step one and choose a facet, you will get a "Search is currently unavailable." error. This occurs not just for the user who has requested the aggregation, but any user running the portal via the impacted EB instance.

**Comment by pmbohm** [comment]
Can this be fixed by any portal code changes? Is this manifestation occurring because the Systest EB stack is sharing memory? If so, this cant be a portal issue

**Comment by pmbohm** [comment]
An issue can be triggered that shows weakness in our Portal proxy code. If a layer is loaded and the WMS is unresponsive the maximum connections can be reached in a browser session. 
#### To Trigger
 1) Use `geonetwork.url = "http://catalogue-systest.aodn.org.au/geonetwork"` portal.groovy in dev environment 
2) Load a gridded dataset and the URL's are like  `http://geoserver-systest-internal.aodn.org.au/geoserver/ncwms?LAYERS=blagh.....`
3) Try to use free text search on step one and notice the portal is unresponsive
