### ISSUE TITLE
Lose big job when testing in systest

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2535]
Seeing this in systest - 

Steps to reproduce:
Create a large netCDF aggregation job i.e. all date range for csv at point for a satellite collection. Wait for it to process

What should happen:
If it takes longer than 24 hours then the job should continue processing for testing processes - or if it is still processing then I should be able to get to the status page for it

What does happen:
Clicked email and got error message:
Unknown status, error retrieving status from WPS server

**Comment by kereid** [comment]
Ok thanks thought that might have been the case is that a one off because they've been kept in the past?

**Comment by jonescc** [comment]
Once the job has completed the status is stored and is available until cleaned up.   This is a change we made a little while ago.  However, if geoserver is restarted while running the job, all history of it is lost.  This is something that should be fixed when we move to AWS Batch.

**Comment by jonescc** [comment]
Most likely caused accidently by https://github.com/aodn/chef-private/pull/2438 - this change was made at 13:41 and chef ran at 18:20 and restarted geoserver-wps-systest.  Normally geoserever-wps-systest wouldn't be restarted during testing.

**Comment by pblain** [comment]
@kereid - does the above answer your question?

**Comment by kereid** [comment]
@pblain yes it has
