### ISSUE TITLE
Selenium browser update failing ExpandCollapseLargeRecordTest

### ISSUE THREAD

**Issue by bhasin85** [aodn/aodn-portal#2542]
Test | OS | Browser | Duration | Finished
-- | -- | -- | -- | --
ExpandCollapseLargeRecordTest | Win 10 | Firefox 55.0 | 41s | 3d ago
ExpandCollapseLargeRecordTest | Win 10 | Firefox 54.0 | 45s | 3d ago
ExpandCollapseLargeRecordTest | Win 10 | Firefox 53.0 | 45s | 3d ago

**Comment by bhasin85** [comment]
Able to reproduce.

**Comment by akashisama** [comment]
Re-opening, latest fix fixes the functionality, but the selenium test is still failing on some browser/os combinations.

**Comment by akashisama** [comment]
Sorry, no, correction, looking at the test run video again, the functionality _is_ failing still :(
