### ISSUE TITLE
Selenium browser update failing PortalTest

### ISSUE THREAD

**Issue by bhasin85** [aodn/aodn-portal#2547]
Test | OS | Browser | Duration | Finished
-- | -- | -- | -- | --
PortalTest | Win 10 | Firefox 54.0 | 1m 9s | 3d ago
PortalTest | El Capitan | Firefox 55.0 | 35s | 3d ago
PortalTest | El Capitan | Firefox 53.0 | 34s | 3d ago

**Comment by bhasin85** [comment]
Unable to reproduce.

**Comment by akashisama** [comment]
This one's still happening
