### ISSUE TITLE
The URL to the collection in the Python download is incorrect

### ISSUE THREAD

**Issue by smancini** [aodn/aodn-portal#2564]
# Steps to reproduce:

Select the following dataset colelction on the AODN Portal
https://portal.aodn.org.au/search?uuid=ca15915b-38c5-4e95-8d25-9cc42c4dd485
Select the Python download in step 3.
Open the python code in text editor or try to run the python code

# What does happen

The Python code does not work properly because the the URL to the collection start with
http://geoserver-portal-internal.aodn.org.au

# What should happen

The URL to the collection in the python code should start by:
Http://geoserver-123.aodn.org.au

**Comment by pmbohm** [comment]
Fixed by https://github.com/aodn/schema-plugins/pull/53

**Comment by anguss00** [comment]
Will run pipeline to deploy this to prod!
