### ISSUE TITLE
bio-acoustic data (BA-SOOP) image display

### ISSUE THREAD

**Issue by rogerproctor** [aodn/aodn-portal#2569]
selecting any track provides you with a pop-up window containing an image of the track data. 

Next to the image is a label 'View'. This is confusing, as one might think it means view the image, but it takes you to the S3 archive of files. This label needs changing to reflect what really happens (e.g. Go to data files).

if using right mouse click on the image and selecting 'View image' brings up the .png file as a full window. The only option to the user to exit this view is the 'back' browser button; unfortunately this takes you to Step 1 not back to the map.
What should happen ... either a) the back button returns you to the map and selected collections, or b) the 'View image' should open a new tab for displaying the image.

**Comment by pblain** [comment]
Sounds like it should be opening in a new tab

**Comment by anguss00** [comment]
I'll open a new issue @rogerproctor @pblain for opening in a new tab and changing the label.

**Comment by anguss00** [comment]
Closing as I've created a new issue https://github.com/aodn/issues/issues/117
