### ISSUE TITLE
Simple baselayer does not display land correctly when zoomed

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2573]
Seeing in production and systest - not sure how long it's been around as haven't zoomed in on simple baselayer before that I can recall

Steps to reproduce:

Add any collection to the map.
On step 2 change to pan control and change the baselayer to the simple baselayer
Move the map over New Zealand or Indonesia zoom in two mouse wheel clicks

What should happen:

Islands still appear as white filled islands

What does happen:
See just a blue outline of the islands

**Comment by pmbohm** [comment]
Fixed by https://github.com/aodn/geoserver-config-static/pull/9

**Comment by pmbohm** [comment]
@kereid This should be fixed now?

**Comment by pmbohm** [comment]
It required a re-seed of squid for this layer. Should be fixed now.

`pmbohm@1-aws-syd:~$ /usr/local/bin/geoserver_seeder.rb -l default_basemap_simple -g http://geoserver-static.aodn.org.au/geoserver/baselayers/wms -p 8083 -P true -s 8 -e 10 -t 8 -T 256 -G 0 -U 'LAYERS=layer_name&TRANSPARENT=TRUE&VERSION=1.1.1&FORMAT=image%2Fpng&QUERYABLE=true&EXCEPTIONS=application%2Fvnd.ogc.se_xml&SERVICE=WMS&REQUEST=GetMap&STYLES=&SRS=EPSG%3A4326&BBOX=135,-90,180,-45&WIDTH=256&HEIGHT=256'`

**Comment by pmbohm** [comment]
@kereid ?

**Comment by kereid** [comment]
Looks good closing
