### ISSUE TITLE
GFI large tables results cant be viewed

### ISSUE THREAD

**Issue by pmbohm** [aodn/aodn-portal#2574]
### Whats happening
On the new https://vmdp.deakin.edu.au/portal/search portal they are using tables content.ftl's (or no content.ftl) for GetFeatureInfo, resulting in large tables of results that cant be scrolled as there is no available horizontal scrolling.
Also happening in our portal with the new Animal Tracking QC layer http://portal-rc.aodn.org.au/search?uuid=0ede6b3d-8635-472f-b91c-56a758b4e091

### What should happen
Content should be accessible 

<img width="1247" alt="screen shot 2017-11-15 at 11 00 14 am" src="https://user-images.githubusercontent.com/1066981/32811590-bf3a05f4-c9f4-11e7-9631-79b516456825.png">

<img width="1119" alt="screen shot 2017-11-15 at 11 12 18 am" src="https://user-images.githubusercontent.com/1066981/32811854-f9d61daa-c9f5-11e7-875e-ef65a0f81692.png">

**Comment by pblain** [comment]
@pmbohm - is this a content issue?

**Comment by pmbohm** [comment]
@pblain This is a taste of what is coming in the AODN space. If a table is the providers best option to show data at a point we cant get in their way.
BTW: We need to be able to show the contents of tables in the popup and also when the popup is maximised
