### ISSUE TITLE
Selections in step 1 not carried to step 2

### ISSUE THREAD

**Issue by petejan** [aodn/aodn-portal#2577]
Selecting a time, geographic extent, parameter in step 1 to select a dataset are not carried to step 2 in the portal to subset a dataset.

**Comment by kereid** [comment]
Hi @petejan, thank for this suggestion also. This one is in our backlog too (https://github.com/aodn/backlog/issues/22) although it has been there much longer than your other suggestion. I have re-tagged the item for re-prioritisation at the next meeting and will let you know the outcome. 

Closing as already in backlog

**Comment by petejan** [comment]
That's not all that helpful, as the backlog repo seems to be private, so you're link returns page not found. Would you not be better to put the link to this issue in your backlog repo?
