### ISSUE TITLE
No depth information in systest

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2582]
Steps to reproduce:

Add any collection to get to step 2.
Click anywhere on the map.

What should happen:

In GFI can see lat/long and depth/height

What does happen:

No lat/long/ depth information

**Comment by kereid** [comment]
Depth information has just come back at aprox 11:50 Friday 01 December. I'm leaving this open for investigation though

**Comment by pmbohm** [comment]
These are all of the ip's that were blocked by `client denied by server configuration: /var/www/depthservice/depth.xml`
Logs from November the 9th till December the 5th

128.184.188.70
129.184.188.70
130.184.188.70
131.184.188.70
66.249.75.146
66.249.70.6
52.221.245.96
138.7.36.217
13.210.71.110
13.210.70.102
13.210.66.196
13.210.205.101
128.184.188.70
128.184.188.40
124.47.150.1
