### ISSUE TITLE
portal step 3 does not show anything when no files are avaliable

### ISSUE THREAD

**Issue by petejan** [aodn/aodn-portal#2584]
When getting to step 3, there is no indication in this step that there are no files to download. 

![image](https://user-images.githubusercontent.com/723918/33918973-541e9a38-e00a-11e7-9490-44596d3dd19d.png)

This dataset link,

https://portal.aodn.org.au/search?uuid=723a3e85-04ae-40e6-ac2a-237a93d84abe

when selecting has fluorescence has no files (although it should, but that is a different problem) when getting the list of netcdf urls returns a zero length file.

**Comment by pblain** [comment]
The is a request for a new feature so adding to the backlog for consideration in the next iteration. https://github.com/aodn/backlog/issues/762

@petejan - I realise the backlog is currently private. We are making changes to  allow external users to track requests like this. In the mean time you'll just have to take my word for it that it's been moved to the backlog. I will let you know the outcome of the next AODN planning meeting, which will be on the 8th of Jan (i.e. I'll let you know when this is likely to be implemented).

**Comment by pblain** [comment]
@petejan - just an update. Out planning was delayed until yesterday. This feature made it into the iteration. This means we will attempt to implement it this fortnight. If things go well well put it into systest the following week and release it. This is a best case scenario though, so I'll keep you posted.

**Comment by pblain** [comment]
@petejan - this is now live. 

![page4](https://user-images.githubusercontent.com/2802359/35718346-2e7eae84-0838-11e8-8cce-f19d13690785.png)
