### ISSUE TITLE
Link in succeeded email different with batch

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2585]
Steps to reproduce:

Proceed forward with any gridded download (just small so it does not take too long and will succeed)
When receive succeeded email click the link in the email.

What should happen:

Old gogoduck email link takes user to the status page and then they can choose to start the download.

What does happen:

User clicks the link and the download starts (probably not good if you have a big download and a small mobile data plan;-) - also the user can see the link is to s3...

**Comment by ccmoloney** [comment]
I will modify it to have a link to the status page as per the current production emails.  The status page contains a link to the output file in S3 (the same link that we are currently putting in the email).

**Comment by ccmoloney** [comment]
Will be resolved by PR: https://github.com/aodn/aws-wps/pull/207
