### ISSUE TITLE
Depth filter not applied

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2614]
Steps to reproduce:

Add CARS 2009 Australian Weekly, leave temporal filter as is, change depth filter to 0 and 0, select csv at a point, proceed to step 3 and download

What should happen:

Get a file with only data at 0 depth

What does happen:
The file is either just all a metadata header = no data = shouldn't be able to start download.

Or it has no metadata header and just data but it has data for 0, 10, 50, 100, 200, 1000, 2000, 5000

**Comment by ggalibert** [comment]
Tried the above use case and got a CSV at a point with metadata and data but depth filter set from 0 to 0 hasn't been applied.
![screenshot from 2018-02-28 13-14-17](https://user-images.githubusercontent.com/3498686/36766311-6c02589a-1c89-11e8-8e9a-4daaabd33bff.png)
