### ISSUE TITLE
CARS download does not work

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2618]
Steps to reproduce:

Add CARS collection to the portal, subset on step 2 so the download won't be too big. Proceed to step 3 and downlaod

What should happen:

Download succeeds

What does happen:

Download fails

Exception occurred during aggregation : For input string: "${Z_MAX}"

**Comment by pblain** [comment]
@kereid - do you know if this happens in prod?

**Comment by kereid** [comment]
@pblain I'll check

**Comment by kereid** [comment]
@pblain it succeeds in prod so it's something new.

**Comment by pblain** [comment]
Thanks kate

**Comment by anguss00** [comment]
I'm pretty sure I've worked out what the issue is, this is going to block a production release right?
