### ISSUE TITLE
AODN logo link to landing page on systest invalid

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2627]
Steps to reproduce:

Open up systest, add a collection to be taken to step 2, click the AODN logo in the top left of the screen to be taken back to the landing page.

What should happen:

Taken to landing page

What does happen:  

Get taken to https://aodn-portal-ci-eb-aodn-portal-systest.dev.aodn.org.au/ with error indicating "Site cannot be reached"

**Comment by gsatimos** [comment]
(Note to self) elastic beanstalk is being deployed with configuration item
`grails.serverURL = "https://aodn-portal-ci-eb-aodn-portal-systest.dev.aodn.org.au"`
which can be found by downloading the source for the application version in the EB console and unzipping the contents.

Need to find out how this is being set.

**Comment by anguss00** [comment]
@gsatimos here's where it's being set for reference https://github.com/aodn/chef-private/blob/master/aws/ebprep/conf/templates/aodn-portal/Portal.groovy.template#L2

**Comment by gsatimos** [comment]
thanks @anguss00 
This doesn't fix this apparent mis-configuration but shouldn't this link be changed to a relative link like this: https://github.com/aodn/aodn-portal/commit/db11b3468526b4816bc6fc5f10867300b592cfca 
?

**Comment by gsatimos** [comment]
Fixed by:
https://github.com/aodn/ci-config/pull/163/files
https://github.com/aodn/cloud-deploy/pull/15/files
https://github.com/aodn/cloud-deploy/pull/16
