### ISSUE TITLE
CAPTCHA enabled on fourth try not third

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2632]
CAPTCHA has always been set to activate on the third attempt of quick downloads however last time and this time of testing it's now on 4 it's probably still not a high number but wondering why it's changed and will it change again?

Steps to reproduce:

Select any gridded collection to be added to step 2. On step 2 subset to a small bounding box and only a day or two for temporal extent.

Proceed to step 3 and select download when the pop up for registering the download opens close it and click the download button again and repeat until the CAPTCHA is activated.

What should happen:

CAPTCHA is activated on the third download

What does happen:

CAPTCHA is activated on the fourth downlaod

**Comment by gsatimos** [comment]
Hey @anguss00 (@kereid mentioned to me that you have had a quick look at this) I'm looking into this issue and what I'm seeing in the code doesn't seem to match the intended behaviour in [DownloadAuthService.groovy
](https://github.com/aodn/aodn-portal/blob/master/grails-app/services/au/org/emii/portal/DownloadAuthService.groovy)
It appears that this is only allows _x_ number of downloads every _y_ minutes before challenging the user with a captcha. Does that compute?

**Comment by gsatimos** [comment]
oh, wait, kinda makes sense now. Might need to just check what config's being run in eb for the prod portal
