### ISSUE TITLE
Bounding box not displayed at high zoom levels NEAR the antimeridian line

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2634]
Steps to reproduce:

Add any collection (to check download works can add NIWA Squid collection) to be taken to step 2, zoom in to -179.5ish, -43ish Draw a bounding box

What should happen:

Box is displayed on the map and applied to the collection

What does happen:

The box does show when drawn but spatial extent fields are populated and if proceed to step 3 and download the download succeeds

Notes: If a box is drawn on the right of the antimeridian it is displayed and after that a box drawn to the left it will be displayed.

**Comment by pmbohm** [comment]
There is indeed a bug where Bbox drawing at higher zoom levels sometimes stops drawing the bounds when the antimeridian is involved. 

The antimeridian has always been a problem for OL and it seems that as we are on version 2.13.1 and the current version is v4.6.5 we should not invest time attempting to fix a problem in OL code. 

The bad decision of OL to draw or not to draw occurs in `getShortString` in SVG.js
