### ISSUE TITLE
Wrong no-temporal message shown for bathymetry layer

### ISSUE THREAD

**Issue by akashisama** [aodn/aodn-portal#2635]
### Steps to reproduce:
Add Deakin bathymetry layer

### What should happen:
Info message shown: "Spatial subsetting only for this data collection"

### What does happen:
Warning message shown: "The data collection has no temporal information"

### Note
The following function from NcWmsPanel.js is used to determine whether to show the info message or the warning message. Evidently it's not working like it was supposed to.
``` JavaScript
   shouldHaveTemporalExtent: function() {
        var metadata = this.dataCollection.data.metadataRecord.data;
        return (metadata.temporalExtentBegin.length > 0) && (metadata.temporalExtentEnd.length > 0);
    }
````

**Comment by kereid** [comment]
@akashisama I don't think this have ever worked properly then as I don't recall ever seeing the "should" message

**Comment by pmbohm** [comment]
#### The check is good

If metadata tells us that there should be Temporal information in the dataset then there must be temporal information. The Portal shows `The data collection has no temporal information` when the getFilters request returns zero TimeSeries values. 
The problem in this case is that the metadata is describing the temporal extent the underlying data was collected or similar and not the dates contained within the Deakin Bathy dataset loaded into the portal. 

The only fix is to always use the one message `Spatial subsetting only for this data collection`

**Comment by pmbohm** [comment]
Fixed by https://github.com/aodn/aodn-portal/commit/ccc2dc46390265fcc6a70bd75e2e1a322860fe6f
