### ISSUE TITLE
Depth Service display in GFI forever loading

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2642]
I believe the new depth service was released into systest this round? Just as I stopped testing due to the WPS showstopper, the last thing I checked was the depth service and found the following:

Steps to reproduce:

Add any collection to the map to be taken to step 2.

Click anywhere on the map to open the GFI

What should happen:

When the GFi opens there is a display showing the depth/height t the click point and the lat and long.

What does happen:

Just shows: "loading....."

**Comment by jonescc** [comment]
This PR was forgotten: https://github.com/aodn/chef-private/pull/2763

**Comment by pblain** [comment]
Fixed by Alex

**Comment by akashisama** [comment]
*fixed by Phil, I just deployed it
