### ISSUE TITLE
Spurious Google Analytics Event

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#2643]
## Steps to reproduce
Go to google analytics
Select BEHAVIOR
Select Events
Select Top Events 
Select (Event Category) DataCollections

## What happens
There's an event action named "Feature Information"

## What should happen
Depends what the event is.  Is it a download? If so it needs renaming. Is it a GFI  request? If so it should be under the "FeatureInfo" event category. Let me know what's going on with this and we can decide what to do about it.

![analytics 5](https://user-images.githubusercontent.com/2802359/40158172-4ead3f04-59e6-11e8-8bde-a87d162da8da.png)

**Comment by pmbohm** [comment]
This is GetFeatureInfo. 
Unfortunately @bhasin85 has included it at https://github.com/aodn/aodn-portal/blame/master/web-app/js/portal/lang/en.js#L308 without noticing the previously added https://github.com/aodn/aodn-portal/blame/master/web-app/js/portal/lang/en.js#L308

I'll look at whats 'untaggleable'

**Comment by pmbohm** [comment]
@pblain 
### History

 1. in **2016** I wrote code  with a disconnect between the labels. 
      * `getfeatureInfoAnchorTrackingCategory` in code vs `featureInfoTrackingCategory` in the language file en.js.
1. This would have resulted in the category being either empty or being the category string being`getfeatureInfoAnchorTrackingCategory` ?

1. Six months latter @bhasin85 put in a fix for the incorrect code entry and defined it as  `getfeatureInfoAnchorTrackingCategory: "Feature Information"`

### Possible fix
I'll create a pull request that changes this to `getfeatureInfoAnchorTrackingCategory: "FeatureInfo"`

**Comment by pmbohm** [comment]
### Postnote
There are two seperate events being tracked or were intended to be tracked
1. Clicking on the map to open a GFI poup
1. Clicking a link within the GFI results

**Comment by pmbohm** [comment]
Screen shot of how it is now. Its possible to see the GFI open and then the mailto link clicked on
<img width="916" alt="screen shot 2018-05-23 at 3 25 24 pm" src="https://user-images.githubusercontent.com/1066981/40404946-c124c28a-5e9d-11e8-9e4d-92fdff930941.png">
