### ISSUE TITLE
Date/Time filter on step 2 only applied to currently selected layer of a collection

### ISSUE THREAD

**Issue by ggalibert** [aodn/aodn-portal#2644]
**What to do:**
1. In step 1 select CARS dataset
2. In step 2, `Subset` tab, select a different date to be displayed than the default one, say `2009-08-28 00:00:00:000 UTC `.
![screenshot from 2018-05-18 14-54-04](https://user-images.githubusercontent.com/3498686/40216855-da5bea02-5aac-11e8-9c39-58e84f8a72dc.png)

3. In the `Layer` tab select a different layer than the default one, say `csiro_cars_weekly_url/PSAL`
4. Click on the WMS layer to bring the getFeature window.

**What happens:**
The getFeature window shows that the date is still set to its default value `Sat, 26 Dec 2009 00:00:00 GMT`
![screenshot from 2018-05-18 14-54-58](https://user-images.githubusercontent.com/3498686/40216876-0d8a4e50-5aad-11e8-9b38-0f3f2e2baa2e.png)
If I go back to the default layer `csiro_cars_weekly_url/TEMP` the date/time hasn't changed from what we previously set in the `Subset` tab.

**What should happen:**
When a date/time as been selected for display in the `Subset` tab, it should apply to all layers in the `Layer` tab and not only the currently selected one. It is important that one should be able to switch from layer to layer for the same date/time.

**Comment by lwgordonimos** [comment]
Closing as we have a backlog item now @pblain
