### ISSUE TITLE
Second click of grey button hides collection info on step 1

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2651]
Steps to reproduce:

Add any collection, go back to step 1 and click the select button again for the same collection then go back to step 1 again.

What should happen:

Still see all the details like geographic extent and parameters etc.

What does happen:

Only see title and select button for collection

See https://github.com/aodn/aodn-portal/issues/2399 was fixed not sure when it may have come back....

**Comment by jonescc** [comment]
Resolved by https://github.com/aodn/aodn-portal/pull/2653
