### ISSUE TITLE
NetCDFOutput fails with weird error message

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2652]
I'm just opening this for discussion as a bug as it's been open before but with a different error, and it was closed but I'm not sure why - the close message doesn't help, someone might recall why it was closed.

https://github.com/aodn/aodn-portal/issues/2480

https://github.com/aodn/aodn-portal/issues/2467

Steps to reproduce: 

Add ANMN Temperature and salinity time-series as this is set up for netcdfoutput

Do not apply any subsets to get all data to download

Proceed to step 3 and select download as netcdf

What should happen:

Either get all the data or it's too much and get email notification

What does happen:

It fails with this new error:

Process failed during execution org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next. ResultSet not positioned properly, perhaps you need to call next.

**Comment by jonescc** [comment]
New bug as we recently tried to fix the old one (running out of memory)

**Comment by jonescc** [comment]
A fix was applied in https://github.com/aodn/geoserver-build/pull/270.  So this sounds like an issue with that fix.

**Comment by pblain** [comment]
@kereid - is this happening in prod - or just systest?

**Comment by pblain** [comment]
@kereid - thanks!
