### ISSUE TITLE
Latitude/Longitude of Depth Service

### ISSUE THREAD

**Issue by akashisama** [aodn/aodn-portal#2655]
This is possible a bug or possibly not. The new depth service isn't working quite the same as the old one. But the new way may be better. I guess this needs a decision by JPSR as to which functionality is correct.

**Steps to reproduce:** 

1. Add ANMN Temperature and salinity time-series as this is set up for netcdfoutput
1. Click anywhere on the map

**What Used To Happen:**

The latitude and longitude displayed in the FeatureInfo box are the same as the latitude and longitude in the the "Point timeseries" textboxes on the sidebar.

**What Now Happens:**

The latitude and longitude displayed in the FeatureInfo box show the location of the depth data that has been returned, which is a slightly different location to the location that was clicked (which is what is shown in the sidebar).

With the way it is now there's an inconsistency between what is clicked and what is seen in the featureinfo box. But with the old way the information given in the featureinfo box isn't technically correct: we don't actually know the depth at that latitude and longitude.

**Comment by ggalibert** [comment]
The new way looks correct to me.

**Comment by pmbohm** [comment]
@pblain is happy with this situation
