### ISSUE TITLE
Depth in file is wrong

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2658]
Steps to reproduce:

Add CARS Australia collection to the map check the csv at a point option and select a single depth for the from and to values i.e. 10m to 10m proceed to step 3 and download as csv.  ONce download is complete open the file

What should happen:

Depth column shows the depth selected

What does happen:

Depth column shows 5000m 

Note if I select 5000-5000 there is no data displayed on the map so assuming there shouldn't be data for 5000m?

**Comment by ggalibert** [comment]
> Note if I select 5000-5000 there is no data displayed on the map so assuming there shouldn't be data for 5000m?

There is no climatological data (what is displayed) at this depth. However the file includes seasonal means for which there is data there.

**Comment by ggalibert** [comment]
This issue is also valid when you select a range for multiple depths, say 0 to 50m.
