### ISSUE TITLE
CSV at point click should override polygon

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2660]
This is in Production

Steps to reproduce:

Add a gridded data collection and on step 2 select polygon and draw a polygon

Then select CSV at a point and click a point on the map

What should happen:

Point should populate csv at point field and be a single point on the map, then only show Timeseries Lat/Lon on step 3

What does happen:

Csv at point fields are populated but the click is like the beginning of drawing a polygon and then on step 3 it shows both spatial co-ordinates and timeseries at lat/lon (only csv is the download option which is correct)

**Comment by gsatimos** [comment]
@kereid can I confirm that this issue I've outlined below is a side-issue that also needs to be addressed? 

### Issue: Detailed Information dialog box not working with polygon
On step 2 when `bounding box` is selected, it is possible at any time to `single-click` the map to show a `detailed information` dialog box. 
When `polygon` is selected, it is not possible to show the same `detailed information` dialog box because a `single-click` on the map will just trigger the start of a new polygon.

**Comment by kereid** [comment]
@gsatimos yes I guess it is! So perhaps the polygon drawing too functionality needs to be changed? i.e. a double click to start it to distinguish polygon start vs GFI click. Perhaps a question for @pblain as it's possibly an enhancement rather than a bug fix?

**Comment by gsatimos** [comment]
agreed @kereid. I'll raise it with @pblain tomorrow.

**Comment by gsatimos** [comment]
@kereid oh wait, it's not obvious (at least wasn't obvious to me) but it's possible to bring up the point information when using the polygon option by doing a `double-click` instead of a `single-click` like it is for `bounding-box`

Just wondering, with this in mind, does this change/resolve the original issue at alll?

**Comment by kereid** [comment]
@gsatimos I'd say still an an issue as it's not consistent - the GFI can be opened with a single click in Pan mode, and after drawing a bounding box so doesn't make sense it's different for polygon

**Comment by gsatimos** [comment]
cool - I'll discuss with pete.

**Comment by pblain** [comment]
Well spotted. The single click to trigger the pop-up (GFI) must be consistent regardless of spatial extent type.  How would anyone guess that it changes to a double click after selecting polygon? Must always be single click.

Bounding boxes are created with a click and drag.
Can we initiate a polygon with click and drag? i.e. start the first side of the polygon by clicking and dragging. Then on release you're drawing the next side of the polygon.

This would mean that it's:

- **_always_** single click for the pop-up
- **_always_** click-and-drag to start a bbox/polygon

**Comment by gsatimos** [comment]
@pblain sounds very logical. I'll try to implement it like that.

**Comment by gsatimos** [comment]
@pblain I think I've wrangled the polygon into working properly but would like to demo it quickly to you when you're in.

**Comment by gsatimos** [comment]
Added features to polygon-type constraint to make it more consistent with how rectangle constraint works
- single-click-drag+release to start drawing polygon 
- subsequent single-click adds new point
- subsequent double-click finishes drawing 
- feature info popup now works with polygon (this wasn't working appearing previously)
- whenever polgon is not being drawn, a single click on the map brings up feature info dialog (as per rectangle constraint)
- dialog dismissed on user clicking [x] but also when new polygon starts being drawn (as per rectangle constraint)

Handling antimeridian issues

This was fairly difficult. Tried a few options but settled on an option that seemed the least worst
- if user attempts to draw a polyon line across antimeridian, the drawing is cancelled and a red error line displayed
- if a user starts drawing a polyon on the opposide side of the antimeridian from where the map is centred, then the map gets re-centered.
