### ISSUE TITLE
'Zoom to collection' should be using the filtered WMS spatial extent rather than the whole collection extent

### ISSUE THREAD

**Issue by xhoenner** [aodn/aodn-portal#2663]
Not sure whether that issue already exists somewhere else @kereid ?

1. Go to the [AODN portal](https://portal.aodn.org.au/search).
1. Select the Argo data collection, go to step 2.
1. In the Subset tab, filter by platform number, e.g. 1900055. Users can't easily see where CTD profiles for that particular platform were collected.
1. Going to the Layer tab and clicking on the 'Zoom to collection' button doesn't zoom in on the filtered WMS layer, rather it uses (I suspect) the spatial extent of the entire data collection. It would be much more practical for users if that logic were implemented the other way around.

**Comment by kereid** [comment]
@xhoenner - No issue regarding this suggestion that I know about - makes sense though.

**Comment by pblain** [comment]
Makes good sense to me. Added to the backlog here: https://github.com/aodn/backlog/issues/903
