### ISSUE TITLE
Bounding box not removed if drawn when gridded collection loading

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2664]
Steps to reproduce:

Add any gridded collection to the map , when taken to step 2 draw a bounding box while collection is loading. Wait until collection finishes loading and then click reset bounding box.

What should happen:

Bounding constraints are reset and bounding box display removed from map

What does happen:

Bounding constraints are cleared but bounding box remains displayed on the map

**Comment by craigrose** [comment]
When user has completed drawing the bounding constraint filter values are applied to selection.  For some collections the initial load of allowed filter values can take some time and they will not be ready for applying the bounding box.  This is particularly the case for temporal filters on large collections.  When this happens the array holding the temporal values is undefined causing premature halting of the bounding constraint drawing such that the filters do not have a reference to the bounding constraint on the map.  Hence the box cannot be cleared when the spatial reset is used.
