### ISSUE TITLE
layer contour option is wrong

### ISSUE THREAD

**Issue by ocehugo** [aodn/aodn-portal#2665]
How to Reproduce:

1. Select HF Radar (say WA).
2. Zoom into the area.
3. Select layer tab in step 2.
4. Select any contour/colormap option.

Result:
1. Contours will be pixelated, not smoothed.
2. Contours will barely visible and with a fixed colour (grayish) instead of a colormap.

Expected:
1. Smoothed contours.
2. Coloured contours.

Browser: Chrome/Linux
![screenshot-1](https://user-images.githubusercontent.com/1202691/42482730-9c1c8838-842c-11e8-8e93-2dfddd501caf.png)

**Comment by ggalibert** [comment]
From the GODIVA interface (uses ncWMS) one can indeed see that the contour is being smoothed, however it is not being coloured. I don't think we could have it coloured.

Example with boxfill: http://thredds.aodn.org.au/thredds/wms/IMOS/ACORN/gridded_1h-avg-current-map_QC/ROT/2017/12/31/IMOS_ACORN_V_20171231T233000Z_ROT_FV01_1-hour-avg.nc?LAYERS=VCUR&ELEVATION=0&TIME=2017-12-31T23%3A30%3A00.000Z&TRANSPARENT=true&STYLES=boxfill%2Frainbow&COLORSCALERANGE=-1%2C1&NUMCOLORBANDS=250&LOGSCALE=false&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image%2Fpng&SRS=EPSG%3A4326&BBOX=113.15197,-33.433849,115.741219,-30.150743&WIDTH=256&HEIGHT=256

![imos_acorn_v_20171231t233000z_rot_fv01_1-hour-avg nc](https://user-images.githubusercontent.com/3498686/42485868-dea2a290-843c-11e8-9c39-fb539cce1585.png)

Same example with contour: http://thredds.aodn.org.au/thredds/wms/IMOS/ACORN/gridded_1h-avg-current-map_QC/ROT/2017/12/31/IMOS_ACORN_V_20171231T233000Z_ROT_FV01_1-hour-avg.nc?LAYERS=VCUR&ELEVATION=0&TIME=2017-12-31T23%3A30%3A00.000Z&TRANSPARENT=true&STYLES=contour%2Frainbow&COLORSCALERANGE=-1%2C1&NUMCOLORBANDS=250&LOGSCALE=false&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image%2Fpng&SRS=EPSG%3A4326&BBOX=113.15197,-33.433849,115.741219,-30.150743&WIDTH=256&HEIGHT=256

![imos_acorn_v_20171231t233000z_rot_fv01_1-hour-avg nc contour](https://user-images.githubusercontent.com/3498686/42485875-e53c0434-843c-11e8-8a4d-94e6676d61dd.png)

**Comment by ggalibert** [comment]
@jonescc correct me if I'm wrong but these discrepencies might come from different versions of ncWMS in current THREDDS and ncWMS abomination.

**Comment by ggalibert** [comment]
Looks like newer version of ncWMS do not smooth contour anymore: https://github.com/Reading-eScience-Centre/ncwms/issues/10 . ncWMS now makes use of EDAL which has implemented this behaviour https://github.com/Reading-eScience-Centre/edal-java/issues/12

This problem might not be in our hands unfortunately.

**Comment by pblain** [comment]
Moved here: https://github.com/aodn/content/issues/350 (I think it's more content related)

**Comment by ggalibert** [comment]
@pblain I don't think this is a content issue. I asked @jonescc what he thinks about this but I think the expected result is tied to what ncWMS decide to do and which version of ncWMS we use.

Contrary to @ocehugo I don't think the expected contour should be smoothed anyway (the original data is not smoothed) and this same decision has been decided in newest ncWMS. 

As to colour of contour, it might be a good idea but again it's in ncWMS hands and this is probably a detail of low priority.

Overall, I'mhappy to leave this issue closed.

**Comment by pblain** [comment]
@ggalibert  OK- that makes sense. I'll tag as "won't fix". We can revisit it depending on what happens with ncWMS.
