### ISSUE TITLE
SST units not useful

### ISSUE THREAD

**Issue by ocehugo** [aodn/aodn-portal#2666]
Hi,

The current portal behaviour on SST visualization is to show SST data with raw units: Kelvin.

From the user perspective, this is suboptimal. Everyone is used to see data in Celsius. Would be hard to just poke a simple decorator on top to do C=K-273.15 !?

**Comment by ggalibert** [comment]
This is a content issue. Will close and open a new issue in content repo.

**Comment by ggalibert** [comment]
See https://github.com/aodn/content/issues/343
