### ISSUE TITLE
Incorrect message : "No data is available using your chosen subset."

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#2667]
## Steps to reproduce
1. On step 1 select IMOS - SRS Satellite - SST L3S - 01 day composite - night time
2. On step 2 select a small patch covering a little bit of data (see below)
3. Go to step 3

## What happens
Message that reads "No data is available using your chosen subset."

## What I expected
I chose a bounding box covering data that I can see on the map - so I would expect that I could download it.

![open access to ocean data 2](https://user-images.githubusercontent.com/2802359/42487699-7a7113de-8445-11e8-9a8f-fe044c54fe07.png)

![open access to ocean data 3](https://user-images.githubusercontent.com/2802359/42487706-80f880e8-8445-11e8-8757-bda54a4466dd.png)

**Comment by craigrose** [comment]
This is most easily duplicated by entering:
N=-24.66, W=172.4, E=173.95, S=-26.5
From = 1992-03-21 15:20 UTC
To = 2018-07-09 15:20 UTC

**Comment by craigrose** [comment]
For collections in the groupings NOAA-17, NOAA-18 and NOAA-19 the west and east bounds needs to be updated in the catalog meta data to encompass all the data points.

**Comment by craigrose** [comment]
Referred to content issue: https://github.com/aodn/content/issues/345
