### ISSUE TITLE
Propagate time constraint in step 1 to step 2

### ISSUE THREAD

**Issue by ocehugo** [aodn/aodn-portal#2679]
Currently, if the user selected a date window in step 1, the date is not propagated to step 2. 

This creates a hassle when selecting multiple products: the user has to select the date window for every product added.

Reproduce:
a. Select a date window in step 1.
b. Select a product (say SST).
c. IN step 2, the dates are still the entire range of data available.

Expected:
c. Should be automatically selected based on step 1 dates.

Use cases:
Say the user want all HF-Radar in Australia for two weeks time. It has to click in all products and change the date ranges in all of them.

**Comment by pblain** [comment]
Ha. Sounds easy doesn't it? It's a bit trickier than it sounds - but something needs doing! Already in the backlog: https://github.com/aodn/backlog/issues/22 (since 2015)

**Comment by ocehugo** [comment]
Hi @pblain, OK.
However, aodn/backlog && aodn/backlog#22 are 404/non existent!

**Comment by pblain** [comment]
@ocehugo - added you as a member - try now
