### ISSUE TITLE
Nearest neighbour in date window when invalid

### ISSUE THREAD

**Issue by ocehugo** [aodn/aodn-portal#2680]
The current behaviour of the portal in step 2 when data is not available at a certain date is to extend the date window to the entire dataset (backward or forward).

Reproduction Example:
1. Go Step 1
2. select IMOS IMOS - SRS Satellite - SST L3S - 01 day composite - night time
3. Next/step 2
4. Select dates from 2013-02-28 to 2013-03-25 --> both dates are invalid.
5. Click next/step3 
6. Download data.

What happened:
Although the boxes are red, indicating invalid dates, the user can click forward to step 3 and donwload data that lies outside of the seleciton dates.
No warning is raised and the dataset is selected in the entire valid range (1993-2018).

What I Expected to Happen:
A warning before step 3 and/or a nearest neighbour date selection. 

This way, when the user selected invalid dates, they are provided with a proper data window. Obviously, the nearest neighbour "forward from date-start/backward from date-end" has to be used, so as to include only the data within the user request.

**Comment by pblain** [comment]
@ocehugo - You make a good point here. 

One procedural thing ... If you could log bugs in the following format that would be great. You have all the right info here, it just makes it easier for the person fixing it if we log bugs in a consistent format:
https://github.com/aodn/internal-discussions/wiki/Logging-Bugs

**Comment by pblain** [comment]
@ocehugo - good idea. Maybe there's a neat way of doing this (don't want to go too crazy). But if there's an easy way to streamline it and create some consistency that would be good.

**Comment by pblain** [comment]
Enhancement

**Comment by pblain** [comment]
Move to Backlog: https://github.com/aodn/backlog/issues/901

**Comment by pblain** [comment]
https://github.com/aodn/aodn-portal/issues/2680#issuecomment-407974199

Looks like you can: https://blog.github.com/2016-02-17-issue-and-pull-request-templates/
