### ISSUE TITLE
Click at point populates Point timeseries 

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2681]
This will probably get sorted with the address of https://github.com/aodn/aodn-portal/issues/2660 and migh actually be the same issue just a different way of putting it...

Steps to reproduce:

Add a gridded collection such as ACORN and draw a bounding box, then decide you would like Timeseries at a point so click on the collection note that the point timeseries is populated - but rightly so is not activated (as for all the portal knows you just want the GFI) then check the box to turn it on.

Proceed to step 3

What should happen:

See Timeseries at latlong applied

What does happen:

See Spatial and timeseries both indicating they are applied.

![timeseriespatial](https://user-images.githubusercontent.com/2906602/43234790-8a988a34-90c1-11e8-8170-1ec3e09098b9.png)

**Comment by kereid** [comment]
Apologies for the horrid colour in the image too I'm having Chrome screen issues....

**Comment by gsatimos** [comment]
can confirm that the fix for this will be coming with https://github.com/aodn/aodn-portal/issues/2660
