### ISSUE TITLE
ALA temporal filter not applied to map

### ISSUE THREAD

**Issue by anguss00** [aodn/aodn-portal#2697]
### Steps to reproduce the issue
1. Go to step 2, select ALA Occurances layer
2. Select a time range different from the default
3. Observe the map data

### Expected behaviour
Map is updated when the temporal extent is changed

### Actual behaviour
Map does not respond to changes in the temporal extent filter

**Comment by pmbohm** [comment]
which environment?

**Comment by anguss00** [comment]
Closing as will be incorporated in ALA project work
