### ISSUE TITLE
inconsistent display of spatial filter on step 3

### ISSUE THREAD

**Issue by gsatimos** [aodn/aodn-portal#2704]
This issue tracker is only for AODN Portal issues.

### Steps to reproduce the issue
1. select a collection on step 1 e.g. `IMOS - SRS Satellite - SST L3S - 01 day composite - night time`
2. draw bounding box on step 2 and move to step 3 (observe the format of the spatial filter displayed to the user)
3. go back to step 2 and select `Point Timeseries` then move to step 3 (observer the format of the spatial filter)

### Expected behaviour
Ideally, the format of the coordinates should be the same

### Actual behaviour
Bounding box sample: `Spatial: 116.807W -16.744S 119.619E -14.371N`
Timeseries sample: `Timeseries at Lat/Lon: -20.4355,115.9277`

Note that the bounding box unnecessarily uses `N/S` and `E/W` which is redundant since this is already explicit because coordinates work with `+/-` to denote this.

Understandably, the `N/S E/W` notation might be useful for the user in which case they should _both_ use it (and be consistent)

**Comment by gsatimos** [comment]
@pblain could you confirm that this should be fixed at some point? would be good to know because I'm updating the email that users receive on completion of a subset and it might be good to gear the email output of subset parameters to match with what the user sees in the portal.
https://github.com/aodn/backlog/issues/882

**Comment by ggalibert** [comment]
Well spotted @gsatimos . The use of signs and N/S or E/W notation is actually incompatible. For example `-14.371N` doesn't make sense, it is either `-14.371` or `14.371S`.

I think the confusion came from step 2 where you have W=116.807 ; S=-16.744 ; etc... and while this is correct, putting the letter at the end of the coordinate in step 3 is confusing and incorrect.

Maybe we could stick to the notation with signs which implies that North is positive and East positive. 

In addition, it is a best practice to usually start with latitude and then longitude.

In the case of a bounding box, we usually give the upper left coordinate first and then the lower right one.

**Comment by gsatimos** [comment]
After discussing this with @ggalibert there's another inconsistency that should be fixed with this ticket.
Timeseries coordinates are represented with latitude first _and then_ longitude while bounding box is represented with _longitude first_

Here's a proposed sample of how it could look:
Timeseries: `Timeseries at Lat/Lon: -20.4355,115.9277`
Bounding box: `Spatial: From Lat/Lon -5.58,102.13 to Lat/Lon -22.11,124.98`

@ggalibert does that look correct with the bounding box being from top-left (_maxLat_, _minLon_) to bottom-right (_minLat_, _MaxLon_)?

@pblain would you concur?

**Comment by ggalibert** [comment]
@gsatimos - now that I see it written for the bounding box example the "From Lat/Lon... to Lat/Lon..." might suggest both values of Lat/Lon are increasing so maybe bottom-left to top-right would be more relevant:

Bounding box: `Spatial: From Lat/Lon -22.11,102.13 to Lat/Lon -5.58,124.98`

Otherwise looks great.

**Comment by ccmoloney** [comment]
I will update the WPS emails (request accepted, error & download available) emails to be consistent.
