### ISSUE TITLE
Both Pan control and bounding box selected

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2706]
This issue tracker is only for AODN Portal issues.

### Steps to reproduce the issue
1. Add any collection.
2. When taken to step 2 draw a bounding box and then click the pan control button. 
3. Remove the collection and go back to step 1
4. Re-add the collection

### Expected behaviour
After re-adding and user taken back to step 2 the pan control should still be active

### Actual behaviour
Both bottons are active

This is in Systest

**Comment by ccmoloney** [comment]
@kereid Should the bounding box remain when you remove the collection?

**Comment by kereid** [comment]
@ccmoloney yes the bounding box should remain when you remove the collection as the bounding box is applied to anything on the map so "in real life" if someone removed the collection they may have more on the map that the bounding box should still be applied to

**Comment by ccmoloney** [comment]
Should be resolved by: https://github.com/aodn/aodn-portal/pull/2718
