### ISSUE TITLE
Pointer on step 2 changes now

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2707]
This issue tracker is only for AODN Portal issues.

Only in systest; logging this as it seems like a good addition but I am unsure of where it has come from and why and so who knows what else has been introduced...

### Steps to reproduce the issue
1. Add a gridded collection to the portal 
2. Watch the pointer on step 2 while collection loads

### Expected behaviour
Usually pointer just stays as a cross and the only loading spinner is next to the collection name on the subset panel

### Actual behaviour
See a blue loading spinner in place of the cross but does not match the loading spinner on the subset panel.

**Comment by anguss00** [comment]
Closing now, but adding the fix-later tag as should be revisited in the future to ensure consistent behaviour between NCWMS and WMS collections
