### ISSUE TITLE
Js Console error in step 2, SRS GHRSST layer

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2710]
### Steps to reproduce the issue
1. Turn on firebug or appropriate developer tool depending on browser
2.Add an SRS OCModis collection 
3. Taken to step 2

### Expected behaviour
No error in console

### Actual behaviour
See Uncaught TypeError: Cannot read property 'clone' of undefined
    at constructor.max (portal-all.js?v=4.38.12:16248)

Similar to https://github.com/aodn/aodn-portal/issues/1131 ?

**Comment by ccmoloney** [comment]
I haven't been able to reproduce this yet.

**Comment by ccmoloney** [comment]
Unable to reproduce at this point.  Will re-open if it occurs again.
