### ISSUE TITLE
Preview images of Colour Scheme of gridded collections are broken

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2727]
Seeing in systest

### Steps to reproduce the issue
1. Add any gridded collection on step 2 proceed to the Layer tab in the subset panel,
2. Open the dropdown
3.

### Expected behaviour
See the different previews for each colour

### Actual behaviour
All the previews look the same

### Screenshots.

![broken colours](https://user-images.githubusercontent.com/2906602/45604802-4c617800-ba7b-11e8-8c34-5b7265db5a76.png)

**Comment by kereid** [comment]
Also just realised in that screenshot the Parameter changing is broken too - assuming these are coming from the same place.

**Comment by lwgordonimos** [comment]
Closing here, and continuing discussion in internal issue, as this is platform/deployment related.
