### ISSUE TITLE
GA bathymetry download not reporting errors

### ISSUE THREAD

**Issue by jonescc** [aodn/aodn-portal#2762]
### Steps to reproduce the issue
1.  Attempt to download from production api endpoint

### Expected behaviour
Should get an error registering the job as the latest api is not yet in prod and the old api returns an error (datasets not specified)

### Actual behaviour
Says job has been registered correctly (and you wait for an email which never comes)

**Comment by ccmoloney** [comment]
Response is a HTTP 200 - but it reports that an error has occurred.

**Comment by gsatimos** [comment]
@ccmoloney I had my face on the issue for PRing... have you just usurped a PR bear?
