### ISSUE TITLE
Duplicate collections show in step 1

### ISSUE THREAD

**Issue by lwgordonimos** [aodn/aodn-portal#2770]
This issue tracker is only for AODN Portal issues.

### Steps to reproduce the issue
1. On step 1, do a keyword search for "penguin fledglings"
2. Note that there is a duplicate record, with the difference being the organisations list
3.

### Expected behaviour
There can be only one

### Actual behaviour
There are two results shown for the same collection

### Screenshots.
![image](https://user-images.githubusercontent.com/19319040/50326600-5ba30680-053f-11e9-95d4-bae0c99cdb62.png)

### What version of the aodn portal are you using?
Portal v4.38.324

### Which browser are you using?
Google Chrome

### Any extra information that might be useful in the debugging process.
N/A

**Comment by pmbohm** [comment]
The share link for one record has come in as `https://portal.aodn.org.au/search?uuid=oai:data.aad.gov.au:IMOS_11068-iso-mcp2`

**Comment by pmbohm** [comment]
Waiting on AAD to help fix the metadata import which currently return no results

**Comment by pmbohm** [comment]
AAD have fixed their servers
https://data.aad.gov.au/oai/provider?verb=ListIdentifiers&from=1900-01-15&metadataPrefix=iso&set=iso-mcp
Returns three unique records.
