### ISSUE TITLE
Share Link on step 3 is ugly and broken

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2773]
Currently on Production and Systest

Steps to reproduce:

Add any collection to the map and proceed to step 3 select the share link copy and paste the link in new tab

What should happen:

Portal loads step 2 with the collection

What does happen:

Seeing 

This site can’t be reached aodn-portal-ci-eb-aodn-portal-prod.dev.aodn.org.au’s server IP address could not be found.
Try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN

Probably same as #2627 and #2628

**Comment by akashisama** [comment]
fixed by https://github.com/aodn/cloud-deploy/pull/304
