### ISSUE TITLE
Share link not using Production Urls

### ISSUE THREAD

**Issue by pmbohm** [aodn/aodn-portal#2777]
### Steps to reproduce the issue
1. Add a collection on portal.aodn.org.au
2. On step 3 look at the share link

### Expected behaviour
Share link should be using 'portal.aodn.org.au'

### Actual behaviour
EG Argo is https://aodn-portal-ci-eb-aodn-portal-prod.dev.aodn.org.au/search?uuid=4402cb50-e20a-44ee-93e6-4728259250d2

Also the AODN logo links to https://aodn-portal-ci-eb-aodn-portal-prod.dev.aodn.org.au

**Comment by ccmoloney** [comment]
Resolved in production
