### ISSUE TITLE
Share links for Antarctic Division records don't use the portal Geonetwork UUID 

### ISSUE THREAD

**Issue by pmbohm** [aodn/aodn-portal#2778]
### Steps to reproduce the issue
1. Search for "Satellite tracking of Emperor penguin fledglings" which is harvested from AAD
2. Look at the share link.

### Expected behaviour
The UUID for all records imported from AAD should be a AODN Geonetwork UUID

### Actual behaviour
The UUID for all imported records is the AAD's metadata UUID

### Portal
portal.aodn.org.au

<img width="1302" alt="screen shot 2019-01-15 at 4 26 45 pm" src="https://user-images.githubusercontent.com/1066981/51160535-7704f580-18e2-11e9-8e82-0edf23404cf3.png">

See: https://github.com/aodn/aodn-portal/issues/2770

**Comment by pmbohm** [comment]
This is blocked by Geonetwork 2.10 behaviour. The uuid used by Portal is the (only) uuid returned by Geonetwork2
Todo: See if Geonetwork 3 is the same

**Comment by pmbohm** [comment]
AAD contacted. A fix will need to come from thier end.

We have an issue with our portal due to an inconsistency of ID's returned by the harvest.


https://data.aad.gov.au/oai/provider?verb=ListRecords&from=1900-01-15&metadataPrefix=iso&set=iso-aodn

Heres an extract from the above URL:


```
<header>
    <identifier>AADC-00099-iso-mcp2</identifier>
    <datestamp>2019-01-15T02:43:25Z</datestamp>
    <setSpec>iso-aodn</setSpec>
</header>
<metadata>
<mcp:MD_Metadata .......>
    <gmd:fileIdentifier>
    <gco:CharacterString>46c810e8-40fd-4e5f-b950-b2393d862455</gco:CharacterString>
    </gmd:fileIdentifier>
    <gmd:language>
```

The problem is our Geonetwork gets out of whack because the identifiers do not match.

**Comment by kereid** [comment]
This has come up again today due to broken link in a story (different collection), seems that this has not been fixed as the url still uses the wrong identifier. 

After a chat with @jonescc we have concluded that the issue might be a Geonetwork issue and needs to be clarified on correct behaviour for OAI-PMH harvester.  Then once clarified will know whether AAD need to fix or AODN need to fix in Geonetwork

**Comment by gsatimos** [comment]
I posted a question regarding this yesterday on the geonetwork-users mailing list.
https://sourceforge.net/p/geonetwork/mailman/geonetwork-users/thread/ME2PR01MB4577DC486C4FE82B073287D5D34C0%40ME2PR01MB4577.ausprd01.prod.outlook.com/#msg36605780

That was 16 hours ago and no bites yet. I'll update here if anything comes in.

**Comment by gsatimos** [comment]
update on this. There's been no action on the ticket mentioned above.

**Comment by gsatimos** [comment]
still no update on this. @jonescc do you think we should see about deving our fork to fix?

**Comment by jonescc** [comment]
Perhaps try the developer list.  They should have an opinion.

**Comment by gsatimos** [comment]
I've[ posted the same question on the geonetwork-dev list](https://sourceforge.net/p/geonetwork/mailman/geonetwork-devel/thread/ME2PR01MB4577A8BD17ADDA0FA9EBC6D4D3460%40ME2PR01MB4577.ausprd01.prod.outlook.com/#msg36615368). I guess we'll wait and see

**Comment by jonescc** [comment]
Thats weird - I'm on those mailing lists and I haven't seen this come through.  May be waiting for a moderator to approve.  Need to check tomorrow.

**Comment by gsatimos** [comment]
this from mimecase console. Maybe some issue 
![image](https://user-images.githubusercontent.com/35054330/54566771-eeabe980-4a25-11e9-828a-b48d48bf15c9.png)

**Comment by jonescc** [comment]
The more I think about it the more this looks like a bug to me.  The metadata record contained in the OAI-PMH response should be indexed like any other metadata record of the contained standard. We can also try raising and issue in github/creating a PR.

**Comment by ccmoloney** [comment]
Please raise a github issue (@jonescc) - or otherwise get some help.

**Comment by jonescc** [comment]
The OAI-PMH specification requires unique OAI-PMH repository identifiers for items in the repository that may be retrieved in different formats: https://www.openarchives.org/OAI/openarchivesprotocol.html#UniqueIdentifier

I can't see anything in there that says that metadata needs to use the same identifier and the requirement to use a URI for the OAI-PMH repository identifier to me suggests that this doesn't make sense to suggest this.  The example included in this section does not use the same identifier: https://www.openarchives.org/OAI/openarchivesprotocol.html#Record uses a different identifier in the metadata record (dublin core in this example) to the OAI-PMH repository identifier.

So I don't think that AAD are doing anything wrong supplying different identifiers as the spec appears to support this.

**Comment by jonescc** [comment]
Ok, so looking at the behaviour in GeoNetwork 3.6 and re-reading @pmbohm's problem description below, I can't find anything that is actually broken here/out of whack due to the OAI-PMH identifier being used instead of the metadata identifier.   Its just not what we were expecting to be used.   I don't think this is worth pursuing with GeoNetwork.  If we really want the metadata identifier to be used we can just index that ourselves and use it.

**Comment by jonescc** [comment]
Closing as I don't think this is worth pursuing.

**Comment by pmbohm** [comment]
@kereid From https://portal.aodn.org.au/sitemap I can see three 'weird' looking Uuid's
https://portal.aodn.org.au/search/uuid/AADC-00099-iso-mcp2
https://portal.aodn.org.au/search/uuid/underway_ship_data-iso-mcp2
https://portal.aodn.org.au/search/uuid/IMOS_11068-iso-mcp2

The thing is they all work now! ?

Was there another one maybe in portal-rc at testing time, that didnt work?

**Comment by kereid** [comment]
Yes I believe they work because AAD did the work you asked them to originally :-) the broken link was https://portal.aodn.org.au/search?uuid=oai:data.aad.gov.au:underway_ship_data-iso-mcp2so-mcp2 if you need it?

**Comment by pmbohm** [comment]
Nice happy ending!
