### ISSUE TITLE
Cannot download collection with no date range

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2786]
Seeing in Systest:

There is a new message (Your date range selection has errors and cannot be applied) I have been seeing in Systest that I don't recall it being demoed at the review so not sure how it's come in - and it hasn't been a problem until I got to the Deakin collection test case.

Steps to reproduce:

Add https://portal-systest.aodn.org.au/search?uuid=8d3ccf63-ee85-41cd-917e-933624a50b2e to the map look at the subset panel and then proceed to step 3

What should happen:

Only message displayed on Step 2 is "The data collection has no temporal information" 

Only message displayed on Step 3 is "The full collection will be downloaded.  Please consider filtering the collection" Yet the download button is still active and user could download the whole lot if they require as this collection will never have a date range.

What does happen:

Messages displayed on Step 2 in the subset panel: 

"The data collection has no temporal information"
 And 
"No data is available using your chosen subset"

On Step 3 

See This field is required Your date range selection has errors and cannot be applied

No data is available using your chosen subset which in turn leads to the Download button being greyed out and non-functional.

**Comment by kereid** [comment]
Maybe something to do with how this was solved? https://github.com/aodn/aodn-portal/issues/2783

**Comment by kereid** [comment]
Or maybe this but this was completed early last month so not sure why it would have not shown itself before this round of testing https://github.com/aodn/backlog/issues/901

**Comment by pmbohm** [comment]
@kereid Only reproducible if a spatial filter is added

**Comment by kereid** [comment]
Oh weird I must have had a bounding box drawn on there when testing it. But it still should work if a user draws a bounding box over where the data is.

**Comment by pmbohm** [comment]
Absolutely. There is a reliance on metadata information to remove for starters, as metadata tells us there should be temporal info for this collection.
