### ISSUE TITLE
Collection with no temporal extent shows as loading via the curser

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2788]
This has been like this fooorreeeeveeerrrrr just figured it wasn't too much of an issue, and did used to be worse but that was fixed in https://github.com/aodn/aodn-portal/issues/2620 however today @lwgordonimos was trying to check some functionality of the collection for me in dev tools and the collection doesn't give anything back when drawing a bounding box for the GFI so it's not just superficial

Steps to reproduce:

Add Deakin collection https://portal.aodn.org.au/search?uuid=8d3ccf63-ee85-41cd-917e-933624a50b2e to the portal. On step 2 look at the collection title bar and hover the curser on the map

What should happen:

Loading spinner shows on collection title bar and that's it.

What does happen:

Loading spinner shows on collection title bar and also the curser is permanently spinning on the map

**Comment by craigrose** [comment]
This is corrected in current systest
