### ISSUE TITLE
Collection with broken link not removed by Online Resource Monitor 

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2789]
This might be similar to what occurred in 2017 https://github.com/aodn/aodn-portal/issues/2508 

Steps to reproduce:

Refresh portal

Pick a collection to change eg soop sst near real time and click the "more" link on step 1 to be taken to the metadata record.

Login to systest geonetwork http://catalogue-systest.aodn.org.au/geonetwork/srv/eng/main.home

Find collection in geonetwork - search soop sst near

Click edit and scroll all teh way to the bottom of the record and change the second link up from thh bottom "online resource" from geoserver to beoserver.

Click save and exit

Wait for a while back in the portal (usually around half an hour think I've been waiting over an hour at the time of logging this)

What should happen:

Collection placed onto "bad" list

What does happen:

Collection is still in normal result list

**Comment by craigrose** [comment]
I note that systest has an incorrect point of truth url (localhost:8080 ... ) whereas production has correct url.  How can this come about when we harvest systest from production?  Perhaps a clue to why the collection is not making it to the bad list?

**Comment by kereid** [comment]
@craigrose I can't remember why.... but that's because I changed the link not the cause of it not getting moved

**Comment by craigrose** [comment]
We could not duplicate the problem.  Making erroneous changes to the record correctly puts it into bad health.  There are no log entries like following suggesting the 'beoserver' change was never made?
```
catalina.out:2019-04-09 09:32:12,098 INFO  [org.fao.geonet.monitor.onlineresource.MetadataRecordInfo] - Record uuid='ca15915b-38c5-4e95-8d25-9cc42c4dd485' title='IMOS - SOOP-Sea Surface Temperature (SST) Sub-facility - Near real-time data' changes status from 'UNKNOWN' to 'FAILED'. Reason/s= [WFS GetFeature request results in exception for uuid='ca15915b-38c5-4e95-8d25-9cc42c4dd485', url='http://xeoserver-systest-internal.aodn.org.au/geoserver/ows?service=WFS&version=1.0.0&request=GetFeature&maxFeatures=1&outputFormat=csv&typeName=soop_sst_nrt_trajectory_map#url', error='xeoserver-systest-internal.aodn.org.au' stack='
```
