### ISSUE TITLE
Collection with broken link not removed by Online Resource Monitor 

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2794]
Although the title is the same as #2789 it's not I can guarantee that..

Instructions are the same though:

 Refresh portal

Pick a collection to change eg soop sst near real time and click the "more" link on step 1 to be taken to the metadata record.

Login to systest geonetwork http://catalogue-systest.aodn.org.au/geonetwork/srv/eng/main.home

Find collection in geonetwork - search soop sst near

Click edit and scroll all the way to the bottom of the record and change the second link up from the bottom "online resource" from geoserver to beoserver.

Click save and exit

Wait for a while back in the portal (usually around half an hour think I've been waiting over an hour at the time of logging this)

What should happen:

Collection placed onto "bad" list

What does happen:

Collection is still in normal result list - however when user tries to download the collection as unsubsetted NetCDFs there is an error 

Host for address 'http://beoserver-systest-internal.aodn.org.au/geoserver/ows?typeName=soop_sst_nrt_trajectory_map&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=INTERSECTS(geom%2CPOLYGON((112.0166015625%20-27.9501953125%2C112.0166015625%20-25.6650390625%2C114.6533203125%20-25.6650390625%2C114.6533203125%20-27.9501953125%2C112.0166015625%20-27.9501953125)))&PROPERTYNAME=url' not allowed

**Comment by gsatimos** [comment]
The Online Resource Monitor wasn't running in systest (no logging of monitor activiity) which explains everything. I restarted `tomcat_geonetwork_systest` on `4-aws-syd` and it immediately started normal monitoring operations.

@kereid by doing this, it will have re-initialised so all records will start from `healthy`.

I'll raise a new ticket for investigating why the online resource monitor didn't engage.

**Comment by gsatimos** [comment]
@kereid I'm closing this since I fixed the immediate problem and created an issue ticket to investigate the underlying cause
