### ISSUE TITLE
Improve contrast/line thick of states in the geographic boundary box

### ISSUE THREAD

**Issue by ocehugo** [aodn/aodn-portal#2843]
Several people doing the workshop couldn't locate the states in the geographic boundary box in step 1. When you zoom in this becomes more clear but at the default zoom level it's very hard to see the lines. This thing is also dependent on the brightness of the monitor.

This is an accessibility issue.

### Steps to reproduce the issue
1. Go step 1, select geographical boundary facet.
2. Lines of states are very hard to see.

### Expected behaviour
Improved contrast of the states boundarys

### Actual behaviour
Australian states are clearly defined.

### What version of the aodn portal are you using?
03/03/2020

### Which browser are you using?
Chrome

**Comment by pmbohm** [comment]
It might be time to show more general land information at higher zoom levels. Cities, roads, rivers etc.
Rather than render them into the baselayers we could add more helper layers.

**Comment by ocehugo** [comment]
see https://github.com/aodn/backlog/issues/1615
