### ISSUE TITLE
Ordering of facets in search results on Step 1 is incorrect

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2856]
Steps to reproduce:

Look at any result on Step 1 of the Portal. 

What should happen:

Order of facets is

Parameter
Date Range
Organisation
Platform

What does happen

Order has been changed to 

Parameter
Date Range
Platform
Organisation

Brief history is that users seeing more organisations is much more important than the platform so this has somehow inadvertently been changed and needs to be reverted 

Full history here:

https://github.com/aodn/backlog/issues/661

https://github.com/aodn/aodn-portal/issues/2484

**Comment by pmbohm** [comment]
It wasn't inadvertent. I just saw the opposite problem occur. Like this screenshot on the first page. I guess it could easily be the other way around if other records bubble up in popularity. I'll swap it back around or this will be discussed by everybody for hours
<img width="1004" alt="Screen Shot 2020-05-14 at 1 58 33 pm" src="https://user-images.githubusercontent.com/1066981/81891435-c00aae00-95eb-11ea-9d5c-71ff7d7e1d7d.png">
