### ISSUE TITLE
Step 3 blank if bounding box drawn over 2 collections

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2857]
In systest only Chrome Version 81.0.4044.138 

a weird one but not unheard of https://github.com/aodn/aodn-portal/issues/2410 .

Steps to reproduce:

Select Glider from platform on step 1 then from results select delayed to add or Real-time - order makes no difference.

Draw a bounding box anywhere over data and go to step 3 (all should look fine), go back to step 2 and add the other collection not added yet and proceed to step 3

What should happen: 

See download options for both collections 

What does happen:

Step 3 is a big white blank panel

**Comment by pmbohm** [comment]
confirmed

**Comment by pmbohm** [comment]
Useful note:
The layer **IMOS - Australian National Facility for Ocean Gliders (ANFOG) - Real-time glider deployments** is 4th from the top in the `status is unchanged 'FAILED'` for the longest time for the last 30 days

https://service.au.sumologic.com/ui/#/dashboard/1a3QHvpPlnvkB9Crpo549ofPVM4jbznwzxLTSh1CeuMhgyByJj1GCQGRUM5k

**Comment by ccmoloney** [comment]
Need to try to reproduce and identify the cause.

**Comment by pmbohm** [comment]
Tried again 27/5 to reproduce with systest. No luck

**Comment by kereid** [comment]
Closing as we cannot reproduce
