### ISSUE TITLE
Colouring of bottom panel changed 

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2858]
Only in Systest

Steps to reproduce:

Add any collection to be taken to step 2

What should happen:

There is apparently a bottom panel which has just been white and so appeared the Previous nad next buttons were integrated into the whole page. So bottom panel should be white filled

What does happen:

The panel has been changed to grey

**Comment by pmbohm** [comment]
It needs to be grey so that the search results are comprehendable especially now as abstract is expandable and results shuffle.
I notice the layout of the `prev` `next` buttons arent very nice so i will adjust.

**Comment by pmbohm** [comment]
fixes https://github.com/aodn/aodn-portal/issues/2855
