### ISSUE TITLE
FilterPanel refactor

### ISSUE THREAD

**Issue by jkburges** [aodn/aodn-portal#286]
* `createFilter` - the contents of this function looks like it should really belong to `BaseFilter` (or some sort of 'factory' class) no?
* coding standard - should be `if (something)` not `if(something)`.  Likewise for `for`, `while` etc.
* `FilterPanel` should really be just about the view.  Consider encapsulating `activeFilters`, and the code that goes with it (potentially `_makeWFSURL`?), in to a 'model' class;
* `_makeDownloadURL` - if (wfsLayer) do something; else do something else; - should this behaviour be pushed in to `layer`, with a function such as `layer._getDownloadURL()` (it's related to the above, obviously).

**Comment by dnahodil** [comment]
I think the issues raised here have all now been addressed.
