### ISSUE TITLE
Second layer of a multi-WMS collection is not being displayed

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2874]
### Steps to reproduce the issue
1. Add  https://portal.aodn.org.au/search?uuid=f0904e61-2e15-4346-bb0e-638366b7e626 to the map
2. Proceed to Layer tab and switch between default layer and the other one

### Expected behaviour
See both collections displayed on the map

### Actual behaviour
The first is displayed yet there is nothing for the second - tracks by aircraft

Email trail for background:

Just raising something that I think might be a portal bug with a particular layer being harvested from the IMAS catalogue into the AODN Portal Catalogue. (I'm not positive, but have checked our portal's log files and can't see any obvious issues).

The collection is https://portal.aodn.org.au/search?uuid=f0904e61-2e15-4346-bb0e-638366b7e626

The collection has two WMS layers
1) aerial extent of Macrocystis on the east coast of Tas surveyed by aircraft (the main layer)
2) tracks taken by the aircraft while surveying

For some reason, the second WMS layer (imas:MS_Aerial_surveys_Macrocystis_TRACKS) won't display in the Portal. It's really odd because it displays just fine in Geoserver OpenLayers (http://geoserver.imas.utas.edu.au/geoserver/imas/wms?service=WMS&version=1.1.0&request=GetMap&layers=imas%3AMS_Aerial_surveys_Macrocystis_TRACKS&bbox=146.81872789%2C-43.64612021%2C148.36381498%2C-40.81442205&width=419&height=768&srs=EPSG%3A3857&format=application/openlayers) and I've tried loading the WMS layer in desktop GIS software which also works perfectly. "Zoom to collection" in the Portal is also working for it, so it's as though it's there but just not visible?

It's not a big deal to remove this WMS layer as it's mostly just useful for display purposes, but I thought it was worth raising in case there's an underlying Portal issue. As mentioned, I couldn't see anything in our Portal logs to indicate an issue with the layer, but the devs may see something at your end?

FWIW there are a number of IMAS-harvested multi-WMS layers in the AODN portal which work just fine (e.g. https://portal.aodn.org.au/search?uuid=c4597a97-1ff5-410c-b23b-b5e2e3944610)

**Comment by pmbohm** [comment]
@anguss00 Any chance you could merginate?

**Comment by kereid** [comment]
@pmbohm @anguss00 where's this one at?

**Comment by anguss00** [comment]
Completed @kereid, sorry I'll close

**Comment by kereid** [comment]
Ah ok thanks - @pmbohm can you please add some commentary as to what the issue was and how it was fixed with adding "https" (?) in and whether it is something that IMAS could resolve themselves if it happens again. This will be useful information to have so that 1. I can go back to Emma to advise and 2. If I see it again with a different contributor in the future I can quickly advise.

**Comment by pmbohm** [comment]
Yes ok @kereid 
Its essential that URL's in metadata (that the portal will use) always have the correct protocol, secure or non secure. IE HTTP vs HTTPS.

There's two places that this can be a problem. 

- If it's not an exact match with 'known host's the URL will be disallowed.
- In portal code, if requests return a redirect like a 302 the redirect is not followed. The same requests when using a browser will be handled gracefully and seem to just work.

**Comment by anguss00** [comment]
Reopening as in my local dev environment, the primary layer works correctly (which fixes an issue with layers in prod currently), but the _TRACKS secondary WMS doesn't show anything on the portal when selected. The requests to imas geoserver throw back 200s but the tiles do not show any data

**Comment by anguss00** [comment]
See https://geoserver.imas.utas.edu.au/geoserver/wms?LAYERS=imas%3AMS_Aerial_surveys_Macrocystis_TRACKS&VERSION=1.1.1&FORMAT=image%2Fpng&EXCEPTIONS=application%2Fvnd.ogc.se_xml&TILED=true&SERVICE=WMS&REQUEST=GetMap&STYLES=&QUERYABLE=true&SRS=EPSG%3A4326&BBOX=0,0,45,45&WIDTH=256&HEIGHT=256

**Comment by pmbohm** [comment]
What about constructing a 'getFeatureCount' request. Draw a BBOX on the area of interest

**Comment by anguss00** [comment]
Drawing over australia returns 2 features - so they exist, but are not being shown. Emma says that there are other multi-WMS layers which are functional so I'll compare

**Comment by pmbohm** [comment]
Their own Geoserver demo uses the workspace in the URL

https://geoserver.imas.utas.edu.au/geoserver/ **imas** /wms

The metadata also needs it.

**Comment by anguss00** [comment]
cool thanks @pmbohm, so that is an update on Emma's end?

**Comment by pmbohm** [comment]
nope. thats not it...
It seems the request doesn't respond to EPSG:4326

**Comment by pmbohm** [comment]
This works with EPSG:3857

https://geoserver.imas.utas.edu.au/geoserver/imas/wms?service=WMS&version=1.1.0&request=GetMap&layers=imas%3AMS_Aerial_surveys_Macrocystis_TRACKS&bbox=146.81872789%2C-43.64612021%2C148.36381498%2C-40.81442205&width=419&height=768&srs=EPSG%3A3857&FORMAT=image%2Fpng

**Comment by pmbohm** [comment]
Change it to EPSG%3A4326 and its empty

https://geoserver.imas.utas.edu.au/geoserver/imas/wms?service=WMS&version=1.1.0&request=GetMap&layers=imas%3AMS_Aerial_surveys_Macrocystis_TRACKS&bbox=146.81872789%2C-43.64612021%2C148.36381498%2C-40.81442205&width=419&height=768&srs=EPSG%3A4326&FORMAT=image%2Fpng

**Comment by anguss00** [comment]
So do we hardcode that in the portal request? Just looking now

**Comment by pmbohm** [comment]
Yes the map is in EPSG:4326 and the layers all must be able to be rendered as EPSG:4326 by their corresponding WMS server. The getCaps should say what projections it can deliver

**Comment by anguss00** [comment]
OK so the IMAS geoserver lists EPSG:4326 as a valid projection through the main getcapabilities document. So is it just a matter of communicating to IMAS to change the layer to use 4326?

**Comment by kereid** [comment]
So am I going back to Emma?

**Comment by jachope** [comment]
Carry Forward from Iteration 204

**Comment by pmbohm** [comment]
@kereid  Reponse to send to Emma

It seems that the layer 'imas:MS_Aerial_surveys_Macrocystis_TRACKS' is in the EPSG:3857 projection, and that Geoserver is not handling to reproject.
EPSG:4326 is a requirement for the AODN portal and all layers are assumed to be in this projection and initialised as such in the Openlayers maps. Consequently request coming from the AODN Portal are specifying EPSG:4326 and using a BBOX wildy different to those used in the EPSG:3857 projection.

The solution is probably in this section of the Geoserver config https://docs.geoserver.org/latest/en/user/data/webadmin/layers.html#coordinate-reference-systems

**Comment by kereid** [comment]
@pmbohm thanks I've sent her an email with this information

**Comment by kereid** [comment]
Exactly the issue. Emma has sorted the collection and it all looks good.
