### ISSUE TITLE
Tooltip popup on Step 1 to get more abstract information appears in random places

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2879]
### Steps to reproduce the issue
1. Open Portal and proceed to step 1
2. Hover over the title bar for any collection

### Expected behaviour
Tooltip pop displays at mouse pointer or close to it, indicating click the title bar for more information

### Actual behaviour
Popup just opens in really random places on the screen - (infinite scroll caused this perhaps?)

**Comment by kereid** [comment]
Also noted same thing happens when hovering pan control and bounding box buttons on step 2

**Comment by pmbohm** [comment]
Can't reproduce in Chrome/Firefox on Mac.
Is this repeatable after closing and re-starting the browser @kereid ?

**Comment by kereid** [comment]
Yes but I think it's perhaps screensize related? I can't get screenshots on my large monitor so I moved the browser to my small screen and then the popup showed at the actual hoverpoint
