### ISSUE TITLE
Refactor of StylePanel

### ISSUE THREAD

**Issue by jkburges** [aodn/aodn-portal#288]
I think #242 has to be fixed before this can be done, as `StylePanel` is also a shared instance.

Currently, `Portal.details.StylePanel` has some special handling in it for NcWMS layers, e.g.:

    if (layer.isNcwms()) {
        this.ncwmsColourScalePanel.makeNcWMSColourScale(layer);
    }
    else {
        this.ncwmsColourScalePanel.hide();
    }

I think we really should be trying to avoid this kind of if/else logic wherever possible.
Keeping `StylePanel`, I suggest introducing a subclass say `NcWmsStylePanel`, which has an extra component (the `ColourScalePanel`).

We could then have `layer.getStylePanel()` which returns the appropriate implementation depending on what kind of layer it is.

**Comment by dnahodil** [comment]
Closing this as is has had recent attention and should be in a much better state than it was

**Comment by jkburges** [comment]
Still there: https://github.com/aodn/aodn-portal/blob/master/web-app/js/portal/details/StylePanel.js#L76

**Comment by dnahodil** [comment]
Aww man. I thought we'd tidied all that up :(
