### ISSUE TITLE
Portal is not displaying links from GN3 correctly on step 3

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2880]
### Steps to reproduce the issue
1. Add https://portal.aodn.org.au/search?uuid=e850651b-d65d-495b-8182-5dde35919616 to the Portal
2. Proceed to Info tab on step 2 look at link to acoustic data viewer
3. Proceed to Step 3 look at link to acoustic data viewer

### Expected behaviour
The link on step 3 should be displayed like Acoustic Data Viewer (preview and download raw data) as it is on step 2

### Actual behaviour
It is displayed as simply acoustic.aodn.org.au

**Comment by ccmoloney** [comment]
Any progress on this Phil?

**Comment by pmbohm** [comment]
@ccmoloney  I missed this completely sorry. Only watched the backlog repo. Looking now
