### ISSUE TITLE
GeoNetwork Link broken then fixed, causes Step 3 to be blank

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2882]
This is a weird one because it's probably only me that will ever see it... But just logging as I've never seen it before, not to say it's not always been like it (or since GN3 came in) as today I think I randomly re-picked that broken collection - I don't specifically ever check the collection after I've changed the link to check the ORM.  It may also never be seen in production if it is a GN3 issue due to the way Systest is set up for now.

### Steps to reproduce the issue
1. Add any collection I often select SOOP SST Near Real time
2. Draw a bounding box over the collection and go to step 3 to make sure step 3 appears as it should. 
3. Then open it in catalogue-systest.aodn.org.au and go in edit the geoserver link to beoserver and close and save wait until the check is done then change it back and wait until it goes back on to the healthy list 
4. Add collection to map and draw a bounding box anywhere and then proceed to step 3

### Expected behaviour
Tell us what should happen
Step 3 appears normal with title download button subsets applied etc

### Actual behaviour
Tell us what happens instead
Step 3 is a big blank white space
### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

Logging now as I've already typed this up but waiting for a different collection to go bad then healthy to check it's reproducable

**Comment by kereid** [comment]
I can confirm this is reproducible on other collections

**Comment by pmbohm** [comment]
This bug is the result of circumstances that do not occur in production.
Additionally, if investigation still required, can we wait until Systest is released again?
@ccmoloney

**Comment by kereid** [comment]
Hi @pmbohm that's what I suspected as it's due to my testing. Happy for it to be closed as it will only ever occur in Systest like you mention and no one would change links in prod the way I do

**Comment by pmbohm** [comment]
I wouldn't let you test drive my car !
