### ISSUE TITLE
Large csv download failing

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2890]
### Steps to reproduce:

Add this collection https://portal-systest.aodn.org.au/search?uuid=7e13b5f3-4a70-4e31-9e95-335efa491c5c

Then go straight to step 3 and select download as csv.

Wait….it will take a while.

It definitely worked on the 1st March, 

### Expected behaviour
CSV downloads but doesn't open properly because it is so large

### Actual behaviour
Getting a failed network error message

### What version of the aodn portal are you using?
4.42.58 Systest 
### Which browser are you using?
Chrome Version 89.0.4389.90 (Official Build) (64-bit)

### Any extra information that might be useful in the debugging process.
Not sure if it is a result of the elastic beanstalk policies being implemented or just a coincidence

**Comment by craigrose** [comment]
duplicate: https://github.com/aodn/aodn-portal/issues/2935
