### ISSUE TITLE
Step 3 blank when SOOP collections have been added and a bounding box drawn

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2892]
I have logged this in the past so have ignored it probably my last two test rounds, but it seems to be easily reproducible now which has been a problem in the past and so not resolved.

### Steps to reproduce the issue
1. Add any SOOP collectino I have seen it for SST near-real time and XBT
2. Draw a bounding box anywhere on step 2 either over the collection or where it isn't 
3. Proceed to step 3

### Expected behaviour
Go to step 3 and see collection details and filter (bounding box co ordinates) appliedTell us what should happen

### Actual behaviour
Step 3 is a big blank white space

**Comment by craigrose** [comment]
See this note: 
https://github.com/aodn/issues/issues/1240#issuecomment-1210150483

The problem seems to have been corrected. Usually these are content issues. Many causes, same symptom.
