### ISSUE TITLE
Investigate why organisation faceted search results (besides IMOS) are broken

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2914]
This issue tracker is only for AODN Portal issues.

### Steps to reproduce the issue
1. Click any organisation (not IMOS) from a result in the default list on step 1 not from the left panel but from each individual collection
2.
3.

### Expected behaviour
Results are narrowed to only include those which have the organisation in them

### Actual behaviour
Get info pop up indicating "the search returned no results" 

### What version of the aodn portal are you using?
Actually seeing this in prod - but I have a test case to check it however I could have selected IMOS which is working or a platform which is working so not sure when it got to prod will update test case to ensure all facets are clicked in future

### Which browser are you using?
Chrome Version 99.0.4844.51 (Official Build) (64-bit)

**Comment by craigrose** [comment]
Can't replicate this. We need more precise description of what collection and filters to try it on.
