### ISSUE TITLE
Shopping cart function displaced when user rego enabled on small screen

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2915]
This issue tracker is only for AODN Portal issues.

### Steps to reproduce the issue
1. Open Portal on a small screen (will add actual size later) and add any collection
2. Look at the top bar
3.

### Expected behaviour
Should see the user rego function and the shopping card function

### Actual behaviour
Only see the user rego function and there is no shopping trolley and no way to scroll acress to find it

### Screenshots.
<img width="638" alt="No trolley" src="https://user-images.githubusercontent.com/2906602/157373249-8d203105-ae48-4236-a445-bd4bacbec0ce.png">

### What version of the aodn portal are you using?
4.42.80

### Which browser are you using?
Chrome

**Comment by craigrose** [comment]
@kereid @Chetnamann
The design of the Portal is not responsive, so it is unsurprising that layout will be disrupted on small screen devices. 

An extensive rebuild of the UI would probably be needed to make it responsive so I have closed this.

To test responsiveness use tools like Firefox responsive design mode. eg An iPhone 12:

![image](https://user-images.githubusercontent.com/40220935/223336999-e9413849-173b-4e5f-a063-e4af9171e769.png)
