### ISSUE TITLE
Get Feature Info is not displaying Depth or lat/long at click point

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2920]
This issue tracker is only for AODN Portal issues.

### Steps to reproduce the issue
1. Add any collection to the portal
2.Click any point on step 2

### Expected behaviour
In the get feature window can see the depth at the click point and the lat long at which the point is

### Actual behaviour
Just says loading

### What version of the aodn portal are you using?
4.42.85 Systest - it is in prod - does this come from a Geoserver currently at this point in time 28/4/22 1532 geoserver -123 is showing as down in nagios but static is up...

**Comment by gsatimos** [comment]
did this get fixed? it looks like it's working now @kereid ?

**Comment by kereid** [comment]
@gsatimos yes looks good again maybe just a hiccup? So will close this issue
