### ISSUE TITLE
URLs don't work T83787 

### ISSUE THREAD

**Issue by Chetnamann** [aodn/aodn-portal#2932]
Test case link: T*#&*&https://aodn.testrail.com/index.php?/tests/view/83787&group_by=cases:section_id&group_id=5&group_order=asc

Comments:

https://portal.aodn.org.au/search?uuid=c1344979-f701-0916-e044-00144f7bc0f4

https://portal.aodn.org.au/search?uuid=b4e742f9-58e5-46b8-b365-15430ea45599

These links don't work.

### Steps to reproduce the issue
1. click on the links below:
https://portal.aodn.org.au/search?uuid=c1344979-f701-0916-e044-00144f7bc0f4

https://portal.aodn.org.au/search?uuid=b4e742f9-58e5-46b8-b365-15430ea45599

2. An error will be displayed on the page.

### Expected behavior
The page should load without error

### Actual behaviour
Shows an error

### What version of the aodn portal are you using?
Portal v4.42.96

### Which browser are you using?
Chrome

**Comment by craigrose** [comment]
@atkinsn @Chetnamann 
https://catalogue-imos.aodn.org.au/geonetwork/srv/eng/q?_cat=portal:IMOS
The records are in catalogue-imos but not in the portal:IMOS category so are not being harvested.
I note that there is a note to the effect that the these are superseded records. Maybe the tests need to be updated?

**Comment by atkinsn** [comment]
Yes, those collections have been replaced by others.

So above need to be replaced by the following:
https://portal.aodn.org.au/search?uuid=8e594cd1-363a-4b58-b741-9fa3624adb77
and 
https://portal.aodn.org.au/search?uuid=06b09398-d3d0-47dc-a54a-a745319fbece

**Comment by Chetnamann** [comment]
Thanks @craigrose @atkinsn will update the tests now

**Comment by evacougnon** [comment]
test now updated, closing this issue
