### ISSUE TITLE
CSV at a point - Link works T83804

### ISSUE THREAD

**Issue by Chetnamann** [aodn/aodn-portal#2934]
This issue tracker is only for AODN Portal issues.

### Steps to reproduce the issue
1.Add gridded collection (such as satellite or radar) switch on point at csv and subset to one day

2. Proceed to step 3 and download as CSV

3. Once receive email notification click the link in the email

### Expected behaviour
Taken to WPS status page

### Actual behaviour
Doesn't go to WPS status page

### What version of the aodn portal are you using?
4.42.96

### Which browser are you using?
Chrome

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by craigrose** [comment]
https://portal.aodn.org.au/search?uuid=10fcb776-d331-4a04-ac1f-4a48fa050385

**Comment by craigrose** [comment]
The test case for T83804 has been deleted because it is already tested here: https://aodn.testrail.com/index.php?/tests/view/84278

Since that test passes I'll close this.

**Comment by craigrose** [comment]
Also updated the test case to have more clarity.
