### ISSUE TITLE
CSV Can be greater than 1 million rows T83807

### ISSUE THREAD

**Issue by Chetnamann** [aodn/aodn-portal#2935]
This issue tracker is only for AODN Portal issues.

### Steps to reproduce the issue
Add an ANMN timeseries to map on step one, proceed straight to step 3 and click download as CSV

### Expected behaviour
Get the CSV and it has more than 1 million rows (however Excel won't actually open them all!)

https://github.com/aodn/aodn-portal/issues/2518

### Actual behaviour
Tell us what happens instead

### Screenshots.
Cannot see more than 1 million rows, or any notification to download data

### What version of the aodn portal are you using?
4.42.96

### Which browser are you using?
chrome

**Comment by evacougnon** [comment]
update, I ran this test on 22/02/2023, I could start the download without any issue. 
I had to stop the download before it completed but reached 23+ GB, I'll make sure the download finishes next time I run the test

**Comment by craigrose** [comment]
https://portal.aodn.org.au/search?uuid=d887e71a-71dc-4851-94a9-920f7b7cc7e5

**Comment by craigrose** [comment]
This test may need to be refactored to be more practical. ie try to avoid having to wait many hours to get the result?

**Comment by craigrose** [comment]
Updated the test to download a smaller file just over 1 million rows. This takes about 3 mins and is only 250MB.
