### ISSUE TITLE
"Select a style" text missing from the UI page

### ISSUE THREAD

**Issue by Chetnamann** [aodn/aodn-portal#2938]
T83974
Change Colour Scheme of Layer

### Steps to reproduce the issue
1.On Step 1 select a data collection that will have options to change eg - SRS SST GHRSST or OceanCurrent gridded collection.

2. From "create a subset" select the Layer tab

3. Click the arrow next to "select a style" to open the drop down list

4. Select a style (colour map) from the list

### Expected behaviour
Should see "select a style" to open drop down list

### Actual behaviour
The expected result works, however, there is no "select a style" displayed on the page. The style is selected by clicking on arrow next to drop down menu whose default displays "boxfill/rainbow"

### What version of the aodn portal are you using?
4.42.97

### Which browser are you using?
chrome

**Comment by craigrose** [comment]
Update the test with the correct instructions

**Comment by craigrose** [comment]
Test case was updated
