### ISSUE TITLE
Portal systest - unexpected logo

### ISSUE THREAD

**Issue by evacougnon** [aodn/aodn-portal#2940]
This issue tracker is only for AODN Portal issues.

This is based on the test ["Logos for each individual record"](https://aodn.testrail.com/index.php?/tests/view/83948)

### Steps to reproduce the issue
1. Select the "CSIRO O&A Catch Operations Data Overview (1965 - present)" collection on step 1 on portal systest
2. Look at the logo on the right of the collection (below "select")

### Expected behaviour
Should see the CSIRO logo in grey scale

### Actual behaviour
Display a map of the western Pacific

### Screenshots.
What I get on systest:
![Screenshot from 2023-02-23 08-30-44](https://user-images.githubusercontent.com/5467402/220764379-37ba294a-da69-4a73-aac0-c49bf2d1ca47.png)

What I get on production (what is correct)
![Screenshot from 2023-02-23 08-31-18](https://user-images.githubusercontent.com/5467402/220764389-15f8c734-9aec-4e6e-abe3-f8a03882090d.png)

### What version of the aodn portal are you using?
4.42.97

### Which browser are you using?
Chrome

### Any extra information that might be useful in the debugging process.
This is only happening on systest, production looks fine as per the screenshot above.
This is happening on several (maybe all?) CSIRO collection

**Comment by craigrose** [comment]
@evacougnon I think this is normal. 

**In systest**: The records are harvested from catalogue-portal. The harvester uses the logo associated with the category that the record is assigned to. If the record is not assigned to a category then it will use the logo of the site that it got the record from, which in this case is [catalogue-portal](https://catalogue-portal.aodn.org.au/geonetwork/images/logos/f70bcf2a-72e0-489c-b979-bab25cf47b3a.png)

**In prod**: The CSIRO harvesters get the logo from the source site https://marlin.csiro.au/geonetwork

**Comment by evacougnon** [comment]
Thanks @craigrose , I will update the test case so we check the CSIRO logo via prod instead of systest
