### ISSUE TITLE
datatrawler collections not available for download

### ISSUE THREAD

**Issue by evacougnon** [aodn/aodn-portal#2943]
This issue tracker is only for AODN Portal issues.

For ref: https://aodn.testrail.com/index.php?/tests/view/84289

### Steps to reproduce the issue
1. datatrawler collection step 2:  https://portal-systest.aodn.org.au/search?uuid=c836a6dc-eba7-28c3-e043-0200007fdbdb
2. check the filters
3. go to step 3
4. click download and accept the licence

### Expected behaviour
Filters available on step 2
Email received once data are ready for download

### Actual behaviour
No filters on step 2 and include the warning " there is a problem with the availability of this collection"
No email received (even a day later)

### What version of the aodn portal are you using?
4.42.97

### Which browser are you using?
Chrome

### Any extra information that might be useful in the debugging process.
I had a chat with @atkinsn  and there might be something wrong with the setting of the filters on our side. It seems we're getting this error on several CSIRO collections. Note that I didn't check all the csiro collections so it may happen to all of them

**Comment by craigrose** [comment]
This issue has been resolved.
