### ISSUE TITLE
T83986 Get Feature Images are Resized

### ISSUE THREAD

**Issue by Chetnamann** [aodn/aodn-portal#2945]
This issue tracker is only for AODN Portal issues.

### Steps to reproduce the issue
Add collections that have pictures or graphs in the Get feature/detailed information popup window (SRS Bio-optical data base has graph) - search for organisation - csiro land and water flagship

Open Get feature/detailed information (GFI) popup window

Change GFI size (by first clicking on the pin symbol, top right corner of the popup window)

### Expected behaviour
Pictures are resized in the GFI to always be wholely visible (at least horizontally)

### Actual behaviour
After selecting the collection, there is no option to choose organisation.

### What version of the aodn portal are you using?
[4.42.97]

### Which browser are you using?
chrome

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by craigrose** [comment]
Update the test case
Wrong dataset? Or use a different filter?

https://portal.aodn.org.au/search?uuid=97b9fe73-ee44-437f-b2ae-5b8613f81042

**Comment by craigrose** [comment]
Refactored to make it clearer which collection to use and remove the reference to organisation
