### ISSUE TITLE
 T84008 Special Characters not displaying correctly in filters 

### ISSUE THREAD

**Issue by Chetnamann** [aodn/aodn-portal#2946]
This issue tracker is only for AODN Portal issues.

### Steps to reproduce the issue

Add collection on step 1: https://portal-systest.aodn.org.au/search?uuid=e41efa35-03f0-4dea-be98-2a69e46b510b

On step 2, check for Site Name with special characters, such as: 'Aguadu' with an accent on the last letter

(optional) Also check https://portal-systest.aodn.org.au/search?uuid=ec424e4f-0f55-41a5-a3f2-726bc4541947 for weird autofill thing in ecoregion

### Expected behaviour
Should see Aguadu with an accent above the last u (special character)

GH #622

### Actual behaviour

couldn't see any site name with special characters such as "aguadu"

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of the aodn portal are you using?
[4.42.97]

### Which browser are you using?
google chrome

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by craigrose** [comment]
Can't replicate

![image](https://user-images.githubusercontent.com/40220935/223306129-9ac032ba-a4b2-46d4-9328-11f5109aecba.png)

**Comment by craigrose** [comment]
Also deleted "(optional) Also check https://portal-systest.aodn.org.au/search?uuid=ec424e4f-0f55-41a5-a3f2-726bc4541947 for weird autofill thing in ecoregion" from the test case.
