### ISSUE TITLE
Filter options should be check box  T84021

### ISSUE THREAD

**Issue by Chetnamann** [aodn/aodn-portal#2947]
This issue tracker is only for AODN Portal issues.

### Steps to reproduce the issue
Add any collection that has multiple subsetting options such as IMOS SOOP-Sea Surface Temperature (SST) Sub-facility - Near real-time data

Select an option that is either true or false (boolean)

### Expected behaviour
Should be selected using a check box not a radio button

### Actual behaviour
doesn't have an option to choose boolean value such as true or false
GH #583

### What version of the aodn portal are you using?
4.42.97

### Which browser are you using?
google chrome

**Comment by craigrose** [comment]
Maybe this test needs more clarity on what to select. ie one of these:

![image](https://user-images.githubusercontent.com/40220935/223302065-bb948e4c-fa56-48fc-b966-9e27fa3b88f1.png)

**Comment by craigrose** [comment]
Updated the test case for clarity.
