### ISSUE TITLE
T84037 Drawing Bounding box over 2 collections should not have JS error 

### ISSUE THREAD

**Issue by Chetnamann** [aodn/aodn-portal#2948]
This issue tracker is only for AODN Portal issues.

### Steps to reproduce the issue
Add Argo and AusCPR Zooplankton collections to the map

Open Firebug (or monitor appropriate to browser version) open console option

Draw a bounding box over where the 2 collections overlap

### Expected behaviour

Should not see any console errors

GH #943

### Actual behaviour

Console errors were seen.

### What version of the aodn portal are you using?
4.42.97

### Which browser are you using?
chrome

**Comment by craigrose** [comment]
Can't replicate
