### ISSUE TITLE
T84043 Status filter always displays data

### ISSUE THREAD

**Issue by Chetnamann** [aodn/aodn-portal#2949]
This issue tracker is only for AODN Portal issues.

### Steps to reproduce the issue
Add ANFOG (Gliders) Realtime collection (narrow down results by selecting glider from the platform facets)

From the status drop down select 'in progress' (status 'completed' does not exist anymore)

NOTE: if testing in rc, filter for status may not be set up (mark as block if that's the case -- only if testing in RC)

### Expected behaviour
Should ideally see some form of the collection displayed
Might be different in rc: there are many filters set up that do not relate to visible data yet

GH#1050

### Actual behaviour
data displayed but unable to follow instructions: as there is no status drop down  

"From the status drop down select 'in progress' (status 'completed' does not exist anymore)" 

Not sure if this test is  valid anymore.

### What version of the aodn portal are you using?
Provide the portal version number or commit ID4.42.97

### Which browser are you using?
google chrome

**Comment by craigrose** [comment]
https://portal.aodn.org.au/search?uuid=a681fdba-c6d9-44ab-90b9-113b0ed03536
Is this only a problem in systest - ie filter somehow not configured correctly?
