### ISSUE TITLE
T84044 Incorrect date string does not give js console error 

### ISSUE THREAD

**Issue by Chetnamann** [aodn/aodn-portal#2950]
This issue tracker is only for AODN Portal issues.

### Steps to reproduce the issue
Add any SRS Collection

Turn on firebug (for Firefox - other browser use appropriate dev tool)

Click in start date field and type 2014-01-4 and then click enter

### Expected behaviour
Should not see console error - TypeError: localDate.getFullYear is not a function

GH #1069 + GH #2249

### Actual behaviour
console showed errors.

### What version of the aodn portal are you using?
4.42.97

### Which browser are you using?
chrome

**Comment by craigrose** [comment]
Can't replicate
