### ISSUE TITLE
 T84056 Dates selected must be in logical order

### ISSUE THREAD

**Issue by Chetnamann** [aodn/aodn-portal#2951]
steps to reproduce issue:

Add argo to the map,

Select an end date, then attempt to select a start date to be a date after the end date just selected.

Also test with ncwms collection

Expected behaviour
Dates after end date on the calendar popup are greyed out and cannot be selected or box highlighted red and a pop up appears indicating error in order of dates.

GH #1163 + #1218 + #2233

Actual behaviour
Dates after end date on the calendar popup are greyed out and cannot be selected but no pop-up appears or no box highlighted red.

What version of the aodn portal are you using?
4.42.97

Which browser are you using?
google chrome

**Comment by craigrose** [comment]
Can't replicate
