### ISSUE TITLE
No error after number filter set : T84084

### ISSUE THREAD

**Issue by Chetnamann** [aodn/aodn-portal#2952]
This issue tracker is only for AODN Portal issues.

### Steps to reproduce the issue
6/10/2021 NOAA decommissioned find another collection next round of testing..

Add a layer to the map which has a number filter (e.g. NOAA Drifters)
Choose the 'between' option in the drop-down of the number filter
Enter a number in the first text field but leave the second text field empty I usually just put 1 in the first and 11 in the second and wait
Click off the form controls to apply the filter
Then repeat by adding a one to the end of the end date to make sure the data comes back on i.e. 1-11, 111, 1111, 11111, (usually appears now)

### Expected behaviour
The filter shouldn't be applied if it will generate invalid CQL and should not see broken tiles

GH#1696

### Actual behaviour

can't find  the 'between' option in the drop-down of the number filter

### What version of the aodn portal are you using?
4.42.97

### Which browser are you using?
chrome

**Comment by craigrose** [comment]
https://portal.aodn.org.au/search?uuid=f9b50e93-df47-4317-8f1f-f3ed2fed7093

**Comment by craigrose** [comment]
The test has been refactored for a new collection.
