### ISSUE TITLE
Date filter on step 1 not bringing all the collections

### ISSUE THREAD

**Issue by evacougnon** [aodn/aodn-portal#2955]
This issue tracker is only for AODN Portal issues.

### Steps to reproduce the issue
1. Step 1 of Portal systest https://portal-systest.aodn.org.au/search
2. Expend Date (UTC) facet
3. Select start date of 01/01/2022 and end date of 01/03/2023
4. Click "Go"

### Expected behaviour
List all the collections with data  matching the time window selected in the filters

### Actual behaviour
Only 5 collections returned
- IMOS - Phytoplankton Abundance and Biovolume (reference stations)
- IMOS - Combined Biogeochemical parameters (reference stations)
- IMOS - Zooplankton Abundance and Biomass (reference stations)
- Statewide Marine Habitat Map 2023
- NSW Estuarine Macrophytes
There should be many more including:
- IMOS - Animal Tracking Facility - Satellite Relay Tagging Program - Near real-time data with quality-controlled locations
- IMOS - Australian National Facility for Ocean Gliders (ANFOG) - Real-time glider deployments

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of the aodn portal are you using?
4.42.102

### Which browser are you using?
Chrome

### Any extra information that might be useful in the debugging process.
As a check, the same query was run on prod (version 4.42.97), 7 collections returned, still not enough and the above 2 collections weren't listed either
Associated test: https://aodn.testrail.com/index.php?/tests/view/84347

**Comment by Chetnamann** [comment]
![imos collection](https://github.com/aodn/aodn-portal/assets/122066242/364aa77b-c8ed-416c-ab7c-796e46485056)

**Comment by Chetnamann** [comment]
still the same issue

What version of the aodn portal are you using?
4.42.104

Which browser are you using?
Chrome

**Comment by craigrose** [comment]
closing duplicate
