### ISSUE TITLE
Content.ftl not rendering images

### ISSUE THREAD

**Issue by xhoenner** [aodn/aodn-portal#2961]
This issue tracker is only for AODN Portal issues.

### Steps to reproduce the issue
1. Select Platform in Step 1 --> Biological Platform --> land-sea mammals. Select any collection and go to Step 2
2. In Step 2 click on a point or a trajectory on the map. A content.ftl window pops up, however the .gif image at the bottom of the window doesn't load up despite the link to OceanCurrent being valid 

### Expected behaviour
The image should get displayed

### Actual behaviour
A broken image icon is displayed instead

### Screenshots.
![image](https://github.com/aodn/aodn-portal/assets/3443821/fa64b487-92c0-4f1b-aa41-d96211e877ca)

### What version of the aodn portal are you using?
4.42.109

### Which browser are you using?
Tried on Chrome and Firefox

**Comment by vfisaac** [comment]
@xhoenner I have tested this (sorry for the insane delay) and no longer appears to be an issue. can you please confirm?

<img width="731" alt="image" src="https://github.com/user-attachments/assets/21fc61ae-c319-4065-b639-46979417a491">

**Comment by xhoenner** [comment]
Indeed, this was fixed through https://github.com/aodn/geoserver-config/pull/796 and then https://github.com/aodn/backlog/issues/5885.
