### ISSUE TITLE
THREDDS NetCDF subset service with Z?

### ISSUE THREAD

**Issue by ggalibert** [aodn/aodn-portal#307]
It looks like the THREDDS NetCDF subset service doesn't allow the user to subset a gridded dataset vertically : http://thredds.aodn.org.au/thredds/ncss/grid/climatology/CARS/2009/eMII-product/CARS2009_Australia_weekly.nc/dataset.html . It looks like this should be possible to achieve : http://www.unidata.ucar.edu/projects/THREDDS/tech/interfaceSpec/NetcdfSubsetService_4_3.html#Vertical but maybe the GUI needs to be modified to allow the user to set the desired vertical range?

Thanks

**Comment by pblain** [comment]
Moved to correct repo
