### ISSUE TITLE
packaging/namespacing of code

### ISSUE THREAD

**Issue by jkburges** [aodn/aodn-portal#363]
Currently, the packing/namespacing of code in the portal is not well defined.

For example, on the server side, most (if not all) of our classes come under the `au.org.emii.portal` package, which as a result, essentially becomes useless information.

On the client side, we have for example some of the search classes under `Portal.ui.search` and some others under `Portal.search`.

The above examples result in:

1. classes are more difficult to find because either related classes are scattered, or packages/directories contain a lot of unrelated classes;
2. the high level structure of the application is not clear (from looking at the code).

'1' can to a certain extent be alleviated with an IDE that allows one to search for classes, so IMHO it's not *that* big of a problem.  '2' however is.  We could be taking advantage of what the languages offer to make our code self-documenting, but at a high level.

## Package by Feature
One approach is to "package by feature".  That is, group classes by the feature that they are implementing.  So, in the front end, we may have something like:

```javascript
Portal.visualise
Portal.search
Portal.download
```

Then at a the next level down, under `visualise`, we have:

```javascript
Portal.visualise.map
Portal.visualise.filter
Portal.visualise.details
Portal.visualise.feature
```

It has been pointed out that some things are shared between packages (it's ok for there to be dependencies) but may not be standalone features as such.  e.g. the store which is now used by both the map and the download, where would it belong in this approach?

## Package by Layer
The main alternative approach is to "package by layer".  That is, have separate layers for the different software layers, e.g. `model`, `view`, `controller` - and indeed this is what grails does at the highest level.

There are advantages and disadvantages to both approaches.  Personally, I'm a fan of "Package by Feature" and I think we could do this for our javascript code.  Not so sure about the server side, as grails obviously forces some conventions on to us about which directories things have to go in (but we can still use java packaging).

Which ever way we go, I think having *some sort* of strategy would be better than what we've got currently.

[This article](http://www.javapractices.com/topic/TopicAction.do?Id=205) goes in to a bit more detail, but it also is pro "package by feature", so please do your own research if you want balance!  I think out of all the points that the linked article gives, it is the following that I agree with the most:

<blockquote>
Higher Level of Abstraction<br/>
Staying at a high level of abstraction is one of programming's guiding principles of lasting value. It makes it easier to think about a problem, and emphasizes fundamental services over implementation details. As a direct benefit of being at a high level of abstraction, the application becomes more self-documenting : the overall size of the application is communicated by the number of packages, and the basic features are communicated by the package names. The fundamental flaw with package-by-layer style, on the other hand, is that it puts implementation details ahead of high level abstractions - which is backwards.
</blockquote>

**Comment by pmbohm** [comment]
The total refactor discussed above wont happen. 
ExtJS3.4 has been shown to be non upgradable
The next major refactor is a re-write which also is a long way off.
