### ISSUE TITLE
Select columns for download

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#486]
Xav would like a feature that allows users to select the columns they get in their downloaded (WFS) file.  Currently they get all columns.

**Comment by pblain** [comment]
Columns of no interest to users will be removed by default - in a separate enhancement.  Any other columns can easily be removed in a spreadsheet or similar.

**Comment by smancini** [comment]
Could we add this feature in the backlog?
It was there before  aodn/backlog#29 but then it has been closed.
Should it be reopened?

**Comment by pblain** [comment]
Added it here: https://github.com/aodn/backlog/issues/396
