### ISSUE TITLE
Map view - removing a data collection before its filters have loaded gives JS error

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#563]
[Portal Build Info]
    Base URL:      http://123.aodn.org.au/aodn123
    Build date:    10/10/2013 17:09
    Version:       3.4.0-rc1
    Instance name: AODN
    Environment:   prerelease

**How to reproduce**
Go to 123.aodn.org.au
Add a data collection with WFS data
*Before the filters have loaded* remove the data collection with the red cross icon

**What does happen**
Javascript errors are displayed in the console:
`TypeError: layer.map is null` (or similar, depending on browser)

**What should happen**
No errors should be encountered.

**Comment by kereid** [comment]
App version: 4.5.0
            Build date: Fri May 22 14:04:54 AEST 2015
            Build number: 13
            Git ref: 72b9e6b8cbedd3738bc5e2bc21d4df04c529e2e0

Reopening this one as I have seen the error TypeError: this.el.dom is undefined
	

...eturn this.rendered?(this.el.dom.value=(Ext.isEmpty(a)?"":a)):""},setValue:funct...

**Comment by pmbohm** [comment]
@kereid Cant reproduce. My guess is the latest accordion work has touched this code.

**Comment by kereid** [comment]
I can still see it - do you mean code on your machine that hasn't been released into this version?
