### ISSUE TITLE
Too hard to add and configure data collections in the portal

### ISSUE THREAD

**Issue by jkburges** [aodn/aodn-portal#638]
## How It Is

Currently, the steps that one has to go through to get a data collection to display and be configured in the portal are:

1. harvest data in to postgresql database
2. configure geoserver layers (for both WMS and WFS layers)
3. configure geonetwork record (which must reference layers from (2))
4. login as admin
5. run wms/wfs scanner against geoserver
6. configure filters for new layer (against the WMS layer)
7. configure the WMS layer to be linked to the WFS layer (for download)
8. configure the WMS layer to be linked to an AODAAC product if appropriate (more workflow getting AODAAC data together)
9. update spatial-search for any new feature types so that they can be searched spatially

I believe, in general, that the above approach is onerous and error prone for the administrators of "data collections".

## Problems

More specifically, I can think of the following problems:

* an admin user has to interact with three different systems (i.e. geoserver, geonetwork and the portal)
    * different UIs - learning the nuances, workflows of each
    * different terminology used in each, i.e. layer vs catalogue records vs data collection 
    * write access to all three systems, creating a security/management overhead
* references between the records (e.g. WMS/WFS URLs) created in the three systems must match up, providing a lot of opportunity for mistakes when first creating them, or for config to "rot" as things get moved around but not updated in all places
* portal config screens, in general, are not particularly user friendly (IMHO - but I challenge us to conduct usability tests against the config/admin screens!)

## Let's Fix It
Much effort has gone in to end-user usability of the 123 portal, and the results speak for themselves.  We have made step 1 above (harvesting) itself much easier (I hope) by providing project officers with a VM, automating talend deployments etc.

However, the usability for admin users (of the portal, but also of the whole portal ecosystem) has certainly been neglected.

I think we can do much better here.  If we don't, we run the risk of having our data collections stagnate or be in error, because it's too hard to add or change things, as well as alienating the admin users who are forced to go through the above process. 

Ideally, without going in to specifics, in order to add or edit a data collection:

* an admin user would have to interact with only one system
* configuration details, such as layer names, URLs etc, would have to be entered in only one place
* the UI would be subject to usability tests as with the 123 portal "front-end".

Fight!

**Comment by danfruehauf** [comment]
I think after the scanners are off, now the process is significantly simpler. Still not perfect - but you have another ticket for that on #1630 which is highlighting the current "hardships".

**Comment by jkburges** [comment]
Yes, I think the process is now covered by the first 3 steps in the OP.
