### ISSUE TITLE
Time selection on new time slice on 123 portal

### ISSUE THREAD

**Issue by ggalibert** [aodn/aodn-portal#674]
This only happens after the time slice selector PR was merged. This can be tested on http://dfruehauf.emii.org.au:8080/aodn-portal/

What to do :
Select ACORN QC'd Rottnest metadata record on step 1.
Select any time from the time combo list (either in start or end).

Expected behaviour :
The time combo list is collapsed showing the currently selected time and the relevant layer is displayed with full date "Displaying ... " below documented.

Experienced behaviour :
The relevant layer is displayed with full date "Displaying ... " below documented but the time combo list is not collapsed automatically after the click and one needs to click outside the time combo list to collapse it.

Comment:
The original behaviour of that time combo list was such that after clicking, it would collapse but the map wouldn't be updated and one had to click outside the combo list to make the change happen on the map. The current behaviour is better than the original but is not yet optimal.

**Comment by smancini** [comment]
Not relevant anymore
