### ISSUE TITLE
AODAAC Download timing out

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#767]
[Portal Build Info]
    Base URL:      http://portal-123.aodn.org.au/aodn123
    Build date:    13/12/2013 10:45
    Version:       3.10.0-rc2
    Instance name: IMOS
    Environment:   prerelease

Steps to reproduce:

Refresh 123 portal add IMOS SRS Satellite - L2P GHRSST-SSTsubskin etc SST to map, seelct dates on start : 15/09/2013 end : 17/09/2013 then go to step 3 enter email and select download as ASCII text. Because there will be too much data should get this message which is fine:

Hi,

The data subset job you initiated on the Integrated Marine Observing System (IMOS) Portal seems to have failed.

Please re-check the parameters you chose and retry running the job.

Error message:
The requested job will have too much data. You have requested roughly 1 times the maximum output size.

Parameters:
ProductId: 1
Output format: txt
Date range start: 2013-09-15 00:00:00.0
Date range end: 2013-09-17 00:00:00.0
Time of day start: 0000
Time of day end: 2400
Lat range start: -50.0
Lat range end: -3.0
Long range start: 110.0
Long range end: 160.0

If you require assistance with the IMOS Portal please contact info@emii.org.au

--
IMOS is supported by the Australian Government through the National Collaborative Research Infrastructure Strategy and the Super Science Initiative.

If you require assistance with the IMOS Portal please contact us at info@emii.org.au

But then if you go back to step 2 and draw a smaller bounding box in the general area of Tas or near enough to Lat range start: -46.7587890625
Lat range end: -36.1240234375
Long range start: 140.8447265625
Long range end: 152.5341796875
 then go to step 3 and select download in ASCII

What should happen:

Get results of aggregation after a while

What does happen:

Get this error in email

Hi,

The data subset job you initiated on the Integrated Marine Observing System (IMOS) Portal has expired with no progress (Job started: 12/19/13 10:38:50 AM).

This generally indicates a server issue so you are free to try your subset again. If you continue to experience the problem please notify us via info@emii.org.au

Job parameters:
ProductId: 1
Output format: txt
Date range start: 2013-09-15 00:00:00.0
Date range end: 2013-09-17 00:00:00.0
Time of day start: 0000
Time of day end: 2400
Lat range start: -41.001953125
Lat range end: -36.607421875
Long range start: 139.5263671875
Long range end: 154.3798828125

If you require assistance with the IMOS Portal please contact info@emii.org.au

--
IMOS is supported by the Australian Government through the National Collaborative Research Infrastructure Strategy and the Super Science Initiative.

If you require assistance with the IMOS Portal please contact us at info@emii.org.au

Reported by Rog.

**Comment by dnahodil** [comment]
Closing as AODAAC is no longer available in Portal 1-2-3.

n.b. the Portal 2.x tag seems to be a mistake based on the version # that @kereid reported.
