### ISSUE TITLE
Removing data collections quickly results in JS errors

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#938]
**Steps to reproduce**
Add some data collections to the map (at least 2, but more might make it easier to reproduce this bug)
Go to step 2
Place your mouse over the 'x' button  which removes collections from the map
Click quickly and repeatedly on the 'x' as each layer moves up so you remove them all

**What happens**
They are all removed _but_ you get JS errors in the console

**What should happen**
All removed without errors

**Comment by smancini** [comment]
Testing
